### ISSUE TITLE
pcap_agent.tcl serach for gre incapsulated traffic

### ISSUE THREAD

**Issue by Andrey-Zakharow** [Security-Onion-Solutions/security-onion#1003]
Hello Doug ,
Thank you for your great product, i have faced with some issue - our company use GRE incapsulation for monitoring interface. And when i am trying to collect data in Sguil (i mean by pressing "right click" -> "wireshark") i got an empty .raw file in /tmp directory.

After hours of digging i have found the solution (for gre) - i have added next lines into /usr/bin/pcap_agent.tcl : 
`package require ip`
and in "if" expression (# Use ip or vlan for the filter):
`    if {$proto != "6" && $proto != "17"} {

        set tcpdumpFilter "(ip and host $srcIP and host $dstIP and proto $proto) or (vlan and host $srcIP and host $dstIP and proto $proto)"
    } else {

       set srcIPtoHex [ip::toHex $srcIP]
       set dstIPtoHex [ip::toHex $dstIP]
       set srcPortHex [format %4.4X $srcPort]
       set dstPortHex [format %4.4X $dstPort]
       set protoHex [format %4.4X $proto]

       set tcpdumpFilter "proto gre and ((ip\[54:4]=$srcIPtoHex or ip\[58:4]=$dstIPtoHex) and ip\[62:2]=0x$srcPortHex and ip\[64:2]=0x$dstPortHex and ip\[51:1]=0x$protoHex)"
    }
`
Numbers in the square brackets near 'ip' is offset and size of the field. IPv4 address is 4 bytes long. Because GRE add 42 bytes overhead (20 bytes first IP header, 8 bytes GRE header, 14 bytes encapsulated Ethernet header), we taking normal IP source/destination offset (see here) and adding it.
So : 
ip[54:4] equals Source IP
ip[58:4] equals Destination IP
ip[62:2] equals Source port
ip[64:2] equals Destination port
and ip[51:1] equals protocol

After all this changes i have got correct .raw data file in /tmp dir.

But i am a newbie in TCL scripting , so i have just replaced next expression : 
`(ip and host $srcIP and host $dstIP and port $srcPort and port $dstPort and proto $proto) or ((vlan and host $srcIP and host $dstIP and port $srcPort and port $
dstPort and proto $proto)`
Because i am not sure is it possible to use "or" 3 times in one expression.

So could you please advice how it should look (with 3 "or" expr.) ?

**Comment by dougburks** [comment]
Hi @Andrey-Zakharow,

This Issue Tracker is not the correct place for questions like this.  Instead, please use our security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!
