### ISSUE TITLE
CapMe: transcript data sometimes overruns the transcript window

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1007]

**Comment by weslambert** [comment]
I ran into an issue with a PCAP today -- pulling it resulted in the data from the transcript running across the page (to the right, past the white boundary, to the end of the browser window) -- is this what you are referring to?

Thanks,
Wes

**Comment by dougburks** [comment]
Hi Wes,

Yes, that's exactly what I'm referring to.  I ran into it while testing a new version of Sguil, so I was originally thinking it was related to the new version of Sguil, but maybe not.

**Comment by dougburks** [comment]
Steps to duplicate this issue:

- replay some traffic:
```
sudo tcpreplay -ieth1 -M10 /opt/samples/bredo*
```

- go to ELSA and search for "tibs 1032"

- click Info, Plugin, getPcap, and authenticate to CapMe

**Comment by weslambert** [comment]
I was able to fix this by modifying the following in `/var/www/so/capme/.css/capme.css`

.txtext_src {
  **display: inline-block;
  width: inherit;
  overflow: hidden !important;
  text-overflow: ellipsis;**
  color: #0000ff;
}

.txtext_dst {
  **display: inline-block;
  width: inherit;
  overflow: hidden !important;
  text-overflow: ellipsis;**
  color: #ff0000;
}

I'll submit a pull request when I get a chance.

Thanks,
Wes

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/3OoHpAmfObM/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2016/10/securityonion-capme-20121213.html
