### ISSUE TITLE
Country not show

### ISSUE THREAD

**Issue by chupyy** [Security-Onion-Solutions/security-onion#1011]
Dear Master
Please help 

after installed securityonion-14.04.5.1.iso everything working execpt country not show
screenshot like this : http://www.plikimage.com/image/21

Thanks a lot

**Comment by dougburks** [comment]
Hi @chupyy ,

Please send questions/problems to our security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
