### ISSUE TITLE
bro manager crash

### ISSUE THREAD

**Issue by birka1** [Security-Onion-Solutions/security-onion#1012]
hi
just install SecurityOnipn 
i notice that bro is not working , when i try to start it i'm getting this error:

so@so-virtual-machine:$ sudo nsm_sensor_ps-start --only-bro
Starting: Bro
removing old policies in /nsm/bro/spool/installed-scripts-do-not-touch/site ...
removing old policies in /nsm/bro/spool/installed-scripts-do-not-touch/auto ...
creating policy directories ...
installing site policies ...
generating cluster-layout.bro ...
generating local-networks.bro ...
generating broctl-config.bro ...
generating broctl-config.sh ...
updating nodes ...
Error: error occurred while trying to send mail: send-mail: /usr/sbin/sendmail not found
starting manager (was crashed) ...
manager terminated immediately after starting; check output with "diag"

i  have 2 server  

1. master
2. sensor

what i'm doing wrong ?

**Comment by dougburks** [comment]
Hi @birka1 ,

Please send all questions/problems to our security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
