### ISSUE TITLE
server master - high utilization

### ISSUE THREAD

**Issue by birka1** [Security-Onion-Solutions/security-onion#1016]
hi

i have server master installed on a VM with 
8 cpu 
32 gb ram
300 gig HD 

the server utilization is very high , in some cases it used all the 32 gb memory and the all the cpu is over 70% most of the time 

when it's get's to 32 gig memory  , i can't  work with the gui until the memory is go dwon

why is it happen ? as far as i understand this should not happened in this kind of enviroment .

this is example from now 

%Cpu0  : 71.8 us, 27.1 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  1.2 si,  0.0 st
%Cpu1  : 76.7 us, 20.9 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  2.3 si,  0.0 st
%Cpu2  : 65.1 us, 32.6 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  2.3 si,  0.0 st
%Cpu3  : 75.6 us, 21.1 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  3.3 si,  0.0 st
%Cpu4  : 80.7 us, 15.9 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  3.4 si,  0.0 st
%Cpu5  : 78.3 us, 17.4 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  4.3 si,  0.0 st
%Cpu6  : 80.9 us, 14.6 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  4.5 si,  0.0 st
%Cpu7  : 76.1 us, 19.3 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  4.5 si,  0.0 st
KiB Mem:  32947264 total, 23162472 used,  9784792 free,    45216 buffers
KiB Swap: 12579836 total,  3238916 used,  9340920 free.   257088 cached Mem

**Comment by weslambert** [comment]
@birka1 ,

Please see the Support page on the Security Onion Wiki:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Support

Thanks,
Wes
