### ISSUE TITLE
Suricata Hyperscan

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1020]
https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Hyperscan

http://suricata.readthedocs.io/en/latest/performance/hyperscan.html

https://github.com/michalpurzynski/nsm-build/blob/master/build_suricata_pkgs.sh

**Comment by theflakes** [comment]
Is Hyperscan included with Suricata on SO now? I've seen dramatic performance, even in Docker, when using it?

With the inclusion of AVX 256 in the newer AMD Epyc it should show good performance increase on AMD I would think with a much higher possible core count.

thanks
