### ISSUE TITLE
question on dailylogs directory (perhaps a documentation addition as well)

### ISSUE THREAD

**Issue by ckozler** [Security-Onion-Solutions/security-onion#1022]
Hi there!

First off, wonderful application! It really ties together nicely and I really appreciate the work done here

I had one quick question about the dailylogs directory - I realize these are the pcaps from snort but what I cant seem to find is what would happen if I deleted them? They are extremely large, for obvious reasons, so I'd like to know what I can do with these once the day has passed.

Does this directory feed anything? Or is once the data is in Elsa and Squert, I can purge this? What would I lose by deleting this

I could not seem to find anything in the docs about this, just a couple maillist posts on Google but nothing concrete for what I am asking here

Thanks!

**Comment by weslambert** [comment]
Hi @ckozler 

Please send questions/problems to the security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks,
Wes
