### ISSUE TITLE
[Bro] Crash report because of whitelisted IP Addresses

### ISSUE THREAD

**Issue by daniejstriata** [Security-Onion-Solutions/security-onion#1025]
Hi, Each time the SO sever starts up I get notified about a Bro crash.

==== stderr.log
Warning: Kernel filter failed: Bad address
1480078500.864111 /opt/bro/share/bro/securityonion/./bpfconf.bro, line 81: BPFConf filename set: /etc/nsm/seconion-master-eth0/bpf-bro.conf (seconion-master-eth0-5)
1480078500.940905 processing suspended
1480078500.940905 processing continued
1480078505.882175 Failed to open GeoIP City database: /usr/share/GeoIP/GeoIPCity.dat
1480078505.882175 Fell back to GeoIP Country database
1480078505.882175 Failed to open GeoIP Cityv6 database: /usr/share/GeoIP/GeoIPCityv6.dat
KILLED
1480081002.312112 received termination signal
1480081002.312112 1363512 packets received on interface eth0, 0 dropped

When I look at:
/etc/nsm/seconion-master-eth0/bpf-bro.conf and /etc/nsm/rules/bpf.conf

I see the following IPs added:
!(host 10.1.1.1)&&
!(host 10.1.1.2)&&
!(host 10.1.1.3)&&
!(host 10.1.1.4)&&
!(host 10.1.1.5)

There is internal IP addresses. Why does the GEOIP try to run on it? Am I whitelisting internal IP addresses in the wrong file?

Regards,
Danie

**Comment by weslambert** [comment]
@daniejstriata 

Please see the Support page on the Security Onion Wiki:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Support

Thanks,
Wes
