### ISSUE TITLE
NSM: remove chown from /usr/sbin/so-bro-cron

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1030]
On large sensors with lots of Bro logs, chown takes more than 5 minutes and the 5-minute cron jobs are piling up:
https://groups.google.com/d/topic/security-onion/V8hjVrKARss/discussion

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/commit/67aa7fa3e3b4b83249aa016ea5411a636f839418

**Comment by weslambert** [comment]
What is this script for?  To just load in changes from securityonion.conf and pass them on to broctl?  I'm assuming the chown was there to make sure that /nsm/bro has the appropriate permissions at every run?

**Comment by dougburks** [comment]
/etc/cron.d/bro runs every 5 minutes and calls so-bro-cron.  so-bro-cron runs /opt/bro/bin/broctl cron, which is a cron job required by Bro.

When we transitioned from running Bro as root to running Bro as a non-root user, so-bro-cron needed to chown the Bro files so that the sguil user could access them properly.  If that chown takes more than 5 minutes, then the cron jobs pile up.  

At this point, all users should have their Bro files owned by sguil, so I think we can safely remove this.  The chown will still happen on initial Bro startup via /usr/sbin/nsm_sensor_ps-start, it just won't happen every 5 minutes anymore to avoid disk thrashing and process pileups.

**Comment by weslambert** [comment]
Thanks for the clarification, Doug!

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/P67KxOYDuWs/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2016/12/securityonion-nsmnow-admin-scripts.html
