### ISSUE TITLE
Segmentation fault /opt/xplico/bin/trigcap

### ISSUE THREAD

**Issue by bugcrash** [Security-Onion-Solutions/security-onion#1045]
bugcrash@seconion:/opt/xplico/bin$ /opt/xplico/bin/trigcap
trigcap v1.1.0
Part of Xplico Internet Traffic Decoder (NFAT).
See http://www.xplico.org for more information.

Copyright 2007-2011 Gianluca Costa & Andrea de Franceschi and contributors.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

usage: /opt/xplico/bin/trigcap [-v] -f <input_file> -t <pkt num> -b <pkt numbers before> -a <pkt numbers after> -o <output_file> [-h]
	-v version
	-f input pcap file
	-t trigger packet number
	-b packet numbers before trigger packet
	-a packet numbers after trigger packet
	-o output pcap file
	-h this help

bugcrash@seconion:/opt/xplico/bin$ gdb -q /opt/xplico/bin/trigcap
Reading symbols from /opt/xplico/bin/trigcap...(no debugging symbols found)...done.
(gdb) r -f `ruby -e 'puts "A" * 9024'`
Starting program: /opt/xplico/bin/trigcap -f `ruby -e 'puts "A" * 9024'`
trigcap v1.1.0
Part of Xplico Internet Traffic Decoder (NFAT).
See http://www.xplico.org for more information.

Copyright 2007-2011 Gianluca Costa & Andrea de Franceschi and contributors.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7822943 in _IO_vfprintf_internal (s=<optimized out>, format=<optimized out>, 
    ap=ap@entry=0x7fffffffb7b8) at vfprintf.c:1661
1661	vfprintf.c: No such file or directory.
(gdb) info reg rdi
rdi            0x4141414141414141	4702111234474983745
(gdb)

**Comment by dougburks** [comment]
Hi @bugcrash ,

Are you trying to report an issue within Xplico itself? If so, please submit it to the Xplico developers directly.

Per the Xplico wiki:

"Don't hesitate to report bugs to bug[@]xplico.org and/or use the forum."
http://wiki.xplico.org/doku.php?id=xplico

Thanks!

**Comment by bugcrash** [comment]
@dougburks 
 Because securityonion is using the code. Why wait for the third party to fix the issue.

**Comment by dougburks** [comment]
I've submitted this to bug@xplico.org on your behalf.

**Comment by dougburks** [comment]
No response yet from bug@xplico.org, so I've also posted this to:
http://forum.xplico.org/viewtopic.php?f=4&t=572

**Comment by dougburks** [comment]
Still no response from bug@xplico.org or http://forum.xplico.org/viewtopic.php?f=4&t=572, so I've emailed Gianluca Costa personally.

**Comment by gnlcosta** [comment]
Fixed: https://github.com/xplico/xplico/commit/f9ecb24c0b2c451faa24b1ffe57b587616ffdcef

**Comment by bugcrash** [comment]
@gnlcosta 
still missing snprintf() for -o argument.

**Comment by gnlcosta** [comment]
Ooops.
Right.
Thanks.

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2017/01/xplico-120-now-available-for-security.html
