### ISSUE TITLE
Segmentation fault /opt/xplico/bin/xplico

### ISSUE THREAD

**Issue by bugcrash** [Security-Onion-Solutions/security-onion#1050]
bugcrash@seconion:/opt/xplico/bin$ ./xplico -h
xplico v1.1.1
Internet Traffic Decoder (NFAT).
See http://www.xplico.org for more information.

Copyright 2007-2014 Gianluca Costa & Andrea de Franceschi and contributors.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

This product includes GeoLite data created by MaxMind, available from http://www.maxmind.com/.

usage: xplico [-v] [-c <config_file>] [-h] [-s] [-g] [-l] [-i <prot>] -m <capute_module>
	-v version
	-c config file
	-h this help
	-i info of protocol 'prot' 
	-g display graph-tree of protocols
	-l print all log in the screen
	-s print every second the deconding status
	-m capture type module
	NOTE: parameters MUST respect this order!

bugcrash@seconion:/opt/xplico/bin$ gdb -q /opt/xplico/bin/xplico
Reading symbols from /opt/xplico/bin/xplico...(no debugging symbols found)...done.
(gdb) r -c `ruby -e 'puts "A" * 9024'`
Starting program: /opt/xplico/bin/xplico -c `ruby -e 'puts "A" * 9024'`
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
xplico v1.1.1
Internet Traffic Decoder (NFAT).
See http://www.xplico.org for more information.

Copyright 2007-2014 Gianluca Costa & Andrea de Franceschi and contributors.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

This product includes GeoLite data created by MaxMind, available from http://www.maxmind.com/.
Files limits: 65000/65000
Limits not changed

Program received signal SIGSEGV, Segmentation fault.
__GI_getenv (name=0x7ffff7557df3 "", name@entry=0x7ffff7557df1 "TZ") at getenv.c:85
85	getenv.c: No such file or directory.
(gdb) i r rbx
rbx            0x4141414141414141	4702111234474983745

**Comment by dougburks** [comment]
Hi @bugcrash ,

Are you trying to report an issue within Xplico itself? If so, please submit it to the Xplico developers directly.

Per the Xplico wiki:

"Don't hesitate to report bugs to bug[@]xplico.org and/or use the forum."
http://wiki.xplico.org/doku.php?id=xplico

Thanks!

**Comment by bugcrash** [comment]
@dougburks 
 Because securityonion is using the code. Why wait for the third party to fix the issue.

**Comment by dougburks** [comment]
I've submitted this to bug@xplico.org on your behalf.

**Comment by dougburks** [comment]
No response yet from bug@xplico.org, so I've also posted this to:
http://forum.xplico.org/viewtopic.php?f=4&t=572

**Comment by dougburks** [comment]
Still no response from bug@xplico.org or http://forum.xplico.org/viewtopic.php?f=4&t=572, so I've emailed Gianluca Costa personally.

**Comment by gnlcosta** [comment]
Fixed: https://github.com/xplico/xplico/commit/f1ae1b7c40df2b75fe1c8ab1ab8619d5885369f5

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2017/01/xplico-120-now-available-for-security.html
