### ISSUE TITLE
Remote PCAP storage

### ISSUE THREAD

**Issue by markkania** [Security-Onion-Solutions/security-onion#1053]
We currently have a pretty old server that we can utilize for a sensor that only has about a TB of space.  

We do however have an additional 10TB of space on a CIFS that we can utilize.

My question is, is it possible to mount a CIFS share on a sensor and store all PCAP remotely on the CIFS?

**Comment by weslambert** [comment]
@markkania 

Please see the Support page on the Security Onion Wiki:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Support

Thanks,
Wes
