### ISSUE TITLE
sostat: check for stuck ELSA cron.pl

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1061]
Related to https://github.com/Security-Onion-Solutions/security-onion/issues/1059, we need an additional sostat check in the ELSA section which displays the age (or start time) of the running cron process as well as archive errors in the log.

**Comment by weslambert** [comment]
Are there any specific archive errors to look out for?  I'm was thinking a grep for 'failed|* ERROR|Duplicate entry' would suffice, but did you have anything else in mind?  Would a lookup of saved_results (based on a duplicate qid error in web.log) be useful as well?

**Comment by dougburks** [comment]
Hey Wes,

Sounds good, thanks!

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/iVG7tc4eAZI/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2017/06/securityonion-sostat-20120722.html
