### ISSUE TITLE
ELSA - group by node - click on a host in the list - presents random host data (never the one I clicked).

### ISSUE THREAD

**Issue by marcusliberto** [Security-Onion-Solutions/security-onion#1064]
ELSA - group by node - click on a host in the list - presents random host data (never the one I clicked).  Any recommendations to begin troubleshooting?

**Comment by dougburks** [comment]
Hi @marcusliberto ,

Please see the Support page on our wiki:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Support
