### ISSUE TITLE
Service Unavailable Error: Cant  access ELSA  and squert. 

### ISSUE THREAD

**Issue by abiodunjames** [Security-Onion-Solutions/security-onion#1070]
I installed security onion on an ubuntu AWS instance.  I tried to SSH -X forward using (ssh -X username@myinstance.com) so that I can access ELSA and squert on my client's browser.
When I go to https://localhost on my client's chrome browser I get this on ELSA

![image](https://cloud.githubusercontent.com/assets/14722744/22466973/00394282-e7c3-11e6-8787-a695402279cd.png)

And squert refuses to log me in. It keeps throwing  connection failed.
![image](https://cloud.githubusercontent.com/assets/14722744/22467008/25b12214-e7c3-11e6-9d39-c2e14585075d.png)

I have tried to search what could be the cause. No clue

**Comment by dougburks** [comment]
Hi @abiodunjames ,

It sounds like you installed Security Onion, but perhaps you didn't run Setup?  Make sure you're following all steps in the Installation Guide:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Installation

If you have further questions or problems, please use our security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

**Comment by abiodunjames** [comment]
Hi dougburks.
I did run setup. I was able to configure username and password for sguil, elsa and squert. I installed sguil client and connected to my security onion server and i was able to view report.

![image](https://cloud.githubusercontent.com/assets/14722744/22467640/b6fc8482-e7c5-11e6-9903-14c3c96e6708.png)

**Comment by dougburks** [comment]
Looking at your original post, it sound like you're running `ssh -X` and then opening your client's browser (outside of the ssh tunnel) and pointing it to localhost.  If that's the case, that connection won't get forwarded across the ssh tunnel.  It will connect to localhost on your client where there is no sguild or database to connect to.

You can either:

- use `ssh -X`, then spawn a browser *inside* of the ssh session and point it to localhost

OR

- use ssh's -L option to forward ports across the ssh tunnel, then open your client browser and point it to localhost

**Comment by abiodunjames** [comment]
Thanks man. It worked like charm. 
I used ssh -L 8080:localhost:443 username@my-server.com
