### ISSUE TITLE
Xplico graphs not loading

### ISSUE THREAD

**Issue by ID1010TERROR** [Security-Onion-Solutions/security-onion#1078]
I was recently going over "The Practice of Network Security Monitoring" book where it talks about Xplico, I'd already reviewed much of the PCAP data, then it brought me to a point where I am supposed to be able to utilize "Graphs" on DNS Traffic, however it doesn't allow me to view a graph, it just shows radial buttons with "hours days weeks months years" none of which seem to do anything.

[Image](http://en.zimagez.com/full/b7ae80ddd2ac316b817defaa1cf6b7546b5be3c1f6b3d1336924c0fb25bf0a9df65d14086b263718d36197e460a53f1e7a70bd0be7d5d076.php)

**Comment by weslambert** [comment]
Jay,

Please pose your question to the Security Onion mailing list:

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks,
Wes

**Comment by ID1010TERROR** [comment]
Done
