### ISSUE TITLE
Installation of Security Onion stuck at Keyboard Layout screen

### ISSUE THREAD

**Issue by espmagik** [Security-Onion-Solutions/security-onion#1079]
Within the keyboard layout screen portion of the installation, the screen gets cut off and I can't click on the "Continue" button. Has anyone experienced this before? Please help

**Comment by weslambert** [comment]
Please pose your question to the Security Onion mailing list:

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks,
Wes

**Comment by dougburks** [comment]
Hi @espmagik ,

From https://github.com/Security-Onion-Solutions/security-onion/wiki/Security-Onion-14.04-Release-Notes:

The Keyboard Layout screen may be larger than your screen resolution and so the Continue button may be off the screen to the right like this:
https://launchpadlibrarian.net/207213663/Screenshot_wilyi386deskmanual_2015-05-22_13%3A05%3A41.png
You can simply slide the window over until you see the Continue button. For more information, please see:
https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1458039
