### ISSUE TITLE
Perl module for Elsa missing after securityonion setup 

### ISSUE THREAD

**Issue by tidiosky** [Security-Onion-Solutions/security-onion#1084]
Hi Every body, Help will be very good.

I'm experience security onion installation in production mode on a virtual environement. 
I tried to install securityonion-14.04.5.1 ISO but no success, installation crashed. So I have decided to Security Onion on Lubuntu 14.04 LTS. After the installation, i have run sosetup. After sosetup, Apache2 won't start and then Squert, Elsa, Snorby won't too. This is the last output of /var/log/apache2/error.log
[apache2.txt](https://github.com/Security-Onion-Solutions/security-onion/files/790502/apache2.txt)

This the third day i'm dealing with issue ! Please help.

**Comment by dougburks** [comment]
Hi @tidiosky ,

Please use the security-onion list for issues like these:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!
