### ISSUE TITLE
Installer crashes with non english language

### ISSUE THREAD

**Issue by alexdevlm** [Security-Onion-Solutions/security-onion#1085]
On a same VirtualBox (latest version) hardware configuration, installer crashes with non english language. Tested with french and german. When english is selected, installer runs well.

![installer_crash_fra](https://cloud.githubusercontent.com/assets/25979720/23257634/ff712bb2-f9c4-11e6-851a-6dbc938643e2.PNG)
![installer_crash_ger](https://cloud.githubusercontent.com/assets/25979720/23257636/02fd4b80-f9c5-11e6-8e5b-74714d210f9d.PNG)

**Comment by dougburks** [comment]
Hi @alexdevlm ,

We're only able to support English at this time.

**Comment by alexdevlm** [comment]
> We're only able to support English at this time.

Is it written somewhere ?

**Comment by dougburks** [comment]
I've added a note to the Installation Guide:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Installation#language

and to the FAQ:
https://github.com/Security-Onion-Solutions/security-onion/wiki/FAQ#why-does-the-installer-crash-when-selecting-a-non-english-language
