### ISSUE TITLE
Updating ruby to 2.x

### ISSUE THREAD

**Issue by vsboost** [Security-Onion-Solutions/security-onion#1089]
Is there any drawback in upgrading ruby from 1.9.3p484 to 2.x,

Wanting to install bettercap on my SO box but it fails because of old version.

Thanks

**Comment by weslambert** [comment]
vsboost,

I'm not sure upgrading Ruby would affect anything, but I can't say that an upgrade would be supported.

If you have any other questions, please pose them to the Security Onion mailing list:

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists#security-onion

Thanks,
Wes

**Comment by vsboost** [comment]
Thanks
