### ISSUE TITLE
Unable to access Internet after setting up security onion

### ISSUE THREAD

**Issue by vanshikamadan** [Security-Onion-Solutions/security-onion#1091]
When I installed Security Onion on my Ubuntu 14.04 rather than on Virtual Machine, it was successfully installed but after rebooting I was not able to connect to Internet. What can I do to have access of internet ?

This issue tracker is primarily used to track issues that need to be fixed and are added to our Roadmap:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Roadmap

If you are creating an issue just to ask a question, you will likely get faster and better responses by posting to our mailing list instead:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

If you have found a bug in Security Onion, you can continue with creating an issue here, but please make sure you have done the following:
- duplicated the issue on a fresh installation of the latest version
- include sostat-redacted output when relevant
- provide information about your system and how you installed Security Onion

**Comment by dougburks** [comment]
Hi @vanshikamadan ,

Did you see this?

"If you are creating an issue just to ask a question, you will likely get faster and better responses by posting to our mailing list instead:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists"

Please post your question to our mailing list.

Thanks!
