### ISSUE TITLE
VirtualBox enviroment question/bug

### ISSUE THREAD

**Issue by NitescuLucian** [Security-Onion-Solutions/security-onion#1096]
Hello guys,

I am runing a security onion solution as a production on vitualbox enviroment (Windows Host).

The problem is that snort logs _only_ the host and other VMs that are on the Host and the host machine and I can nt monitor my entire network. What informations should I give you? What should I do?

**Comment by weslambert** [comment]
Nitescu,

This issue tracker is primarily used to track issues that need to be fixed
and are added to our Roadmap:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Roadmap

If you are creating an issue just to ask a question, you will likely get
faster and better responses by posting to our mailing list instead:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks,
Wes
