### ISSUE TITLE
ELSA Query list??

### ISSUE THREAD

**Issue by Gaz494** [Security-Onion-Solutions/security-onion#1097]
Hi all,

Relatively new to SO. Has anyone written any form of syntax list or cheat sheet/noddy guide for ELSA at all? I'm able to drill down through data relatively easy, but looking at using the query field for more in depth analysis, with a view to having a list of frequent queries written in python to make things quicker for the analysts.

Thanks in Advance

Gaz

**Comment by dougburks** [comment]
Hi @Gaz494 ,

Please see the following:

https://github.com/Security-Onion-Solutions/security-onion/wiki/ELSA

https://github.com/Security-Onion-Solutions/security-onion/wiki/ELSAQueryTips

https://github.com/mcholste/elsa/wiki/Documentation

If you have further questions or problems, please use our mailing list:

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!

**Comment by Gaz494** [comment]
Thanks Doug, that's a huge help

Gaz
