### ISSUE TITLE
vmware + security onion + Internet connection

### ISSUE THREAD

**Issue by steversa57** [Security-Onion-Solutions/security-onion#1099]
Hello all,

I was just wondering if you could help me, I have just installed security onion on my vmware pro 12, at first phase of configuration I had Internet connection but when I implement the second phase of the configuration I lost my Internet connection inside the VMware? I changed my network from NAT to the bridege and tried all the option but still security onion cant connect to the Internet?
This is the link which I used as a guidance for configuration:
https://github.com/Security-Onion-Solutions/security-onion/wiki/VMWare-Walkthrough

I would greatly appreciate if someone can help me to resolve this issue as I need to do a school project and Im using security onion as my project to monitor my network traffics.

Cheers,
Steve

**Comment by weslambert** [comment]
Hi @steversa57,

If you are creating an issue just to ask a question, you will likely get faster and better responses by posting to our mailing list instead:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks,
Wes

**Comment by steversa57** [comment]
Sorry dude, I have just posted in your mailing list now.

Many Thanks,
Steve
