### ISSUE TITLE
How to bridge Windows to an AWS Security Onion Instance running OpenVPN

### ISSUE THREAD

**Issue by ssfirehawk** [Security-Onion-Solutions/security-onion#1100]
I'm configuring an SO server in AWS and found a helpful guide that helped me build bridged OpenVPN connections between my clients and server. The Linux documentation was excellent and worked great, with the exception of RHEL, which I shelved for now. I'm attempting to do the same with some Windows inistances that exist in AWS as well and the documentation is limited to say the least. I downloaded AWS and configured the OpenVPN client configuration file similarly to how I configured the Linux variants. I created and exported the keys to the Windows server, and dropped them into the OpenVPN "Easy-RSA" file. The client configuration file has the key names added and dev-node "MyTap" specified.  is I renamed the Windows TAP that was built to "MyTap". Ive also built an NDIS 6.0 TAP as I was reading this: http://www.sans.org/reading-room/whitepapers/detection/security-onion-cloud-client-network-security-monitoring-cloud-34335. 

I associated a secondary interface to dual home the server and tied both Taps I created to a secondary interface that had reachability into the AWS environment. The bridge is built fine, I configure the bridge with a 10.8.0.x address and point the default gateway to the existing OpenVPN server on my SO box. I've kinda been trying everything I can come across to get some kind of reachability into the 10.8.0.0 network

Currently my pings fail and all I see are ARP's looking for 10.8.0.X network coming from my TAP's. 

Is there any kind of How-to' guide that I haven't come across on how to configure a Windows box to be a client in an AWS Security Onion Deplyment?

**Comment by dougburks** [comment]
Hi @ssfirehawk ,

This issue tracker is for tracking issues (bugs that need to be fixed).

General support questions like this should go to our mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!

**Comment by ssfirehawk** [comment]
Sorry, I wasn't paying attention. I'll find  where this goes.
