### ISSUE TITLE
Squert will not display on remote PC

### ISSUE THREAD

**Issue by fullagame** [Security-Onion-Solutions/security-onion#1104]
Attempting to access Squert outside of localhost and I am getting a blank dashboard. Whitlisted the IP of the remote PC to so-allow for all options. 

![image](https://user-images.githubusercontent.com/29268981/26911901-a6a9c0ea-4bde-11e7-9f70-5bf245997814.png)

**Comment by weslambert** [comment]
You'll want to make sure you are using a Chromium-based browser, such as
Chrome.  If you still have issues, please post to the mailing list.

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists#mailing-lists

Thanks,
Wes
