### ISSUE TITLE
Apache service is unable to start and hence all the cool web GUIs are unavailable.

### ISSUE THREAD

**Issue by bmalik4444** [Security-Onion-Solutions/security-onion#1105]
Hi,

I had an issue accessing ELSA yesterday. It would show up but the right pane of the window would say, "Service unavailable" which was odd. CapMe and Squert were accessible yesterday. I read another post on here which suggested that the user may not have followed through the post installation steps. Since I am picking this up after another admin, I decided to re-run the Security Onion setup through the desktop. I made sure I enabled ELSA to run. The setup completed successfully. 

I tried to access the web interface locally from the security onion, and nothing showed up. I realized Apache2 wasn't running so I ran "sudo service apache2 restart" 
![capture](https://user-images.githubusercontent.com/29615522/27410229-d53cc876-56ab-11e7-923c-5fbce8cc5f10.PNG)

So I decided to read the error logs... and this is what's in the apache error logs...

![capture1](https://user-images.githubusercontent.com/29615522/27410284-3ec6779c-56ac-11e7-898f-f4ede487932d.PNG)

I am not sure what to do. I ran sudo soup to make sure its updated. Still no luck. 

here's a list of ELSA pacakages installed using dpkg -l |grep elsa

![capture3](https://user-images.githubusercontent.com/29615522/27410339-8d2934ce-56ac-11e7-9ff4-e3802f00f811.PNG)

I would not only welcome further troubleshooting steps, but also extremely appreciate it. 
Thanks,

**Comment by dougburks** [comment]
Hi @bmalik4444 ,

We use this Issue Tracker to track bugs and enhancements.  Support requests like this should go to our mailing list instead:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!
