### ISSUE TITLE
soup: handle situations where apt prompts to keep/replace file

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1108]
Occasionally Ubuntu releases updates which will prompt the user to keep or replace a file.  During a normal interactive soup, the user can answer the prompt and everything is fine.  However, if the user runs `sudo salt '*' cmd.run 'soup -y'`, then the salt minion runs `soup -y` and it will most likely just hang there waiting for user input.

**Comment by weslambert** [comment]
Maybe something like:

**Comment by dougburks** [comment]
Yes, but we need to make sure we understand the behavior and how it applies to at least these two separate cases:

1.  This discussion started when Phil mentioned a recent example of `unattended-upgrades`.  In this example, it's probably safe to accept the default and allow the new version of the file to be installed.

2.  Suppose a user modifies some Ubuntu file in /etc, then Ubuntu upgrades the package, and it overwrites their changes.  At the very least, the user needs to know that the file was overwritten so that they can reapply their custom changes.

This will require some testing and experimentation to see if there are any other corner cases out there.

**Comment by dougburks** [comment]
commit:
https://github.com/dougburks/elastic-test/commit/cb6678199cac9a0ee601a2218ef53a7580bd21d6

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/-PAX_MBFj18/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2017/08/securityonion-sostat-20120722.html
