### ISSUE TITLE
CAPME: SO/ELK, Second ES query didn't return a protocol field.

### ISSUE THREAD

**Issue by Behkxyz** [Security-Onion-Solutions/security-onion#1110]
When trying to click ANY _id from ANY log on SO/ELK implementation it opens the CAPME tab, instead of showing the BRO or PCAP it sends the following message:

<img width="607" alt="captura de pantalla 2017-06-28 a la s 18 32 48" src="https://user-images.githubusercontent.com/26779181/27664994-3add7570-5c30-11e7-9180-7ba7c59b2090.png">

**This is under a distributed environment, which I understand is unsupported**, so I do not know if this issue will be closed for that, but I want to be completely honest on what I'm doing.

My guess is that the ID is associated to a log from the sensor which is not present on the console and that's why it can't find it, sadly there is not enough logs that leads me to a conclusion.

I tried to replicate the /nsm/sensor_data/ directory on the console, perhaps it's trying to locally gather it but it's not the case.

Thanks,

**Comment by weslambert** [comment]
Hi @Behkxyz  ,

As you mentioned, setup of Elastic on Security Onion is not yet supported within a distributed environment.

Additionally, we use this Issue Tracker to track bugs and enhancements. Support requests like this should go to our mailing list in the future:

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks,
Wes
