### ISSUE TITLE
NSM: nsm_sensor_ps-restart --sensor-name=$i --only-pcap should only restart pcap

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1118]
nsm_sensor_ps-restart currently has a logic bug when combining --sensor-name and --only-pcap:
```
 --sensor-name*)
                        SENSOR_NAME="$SENSOR_NAME $(echo $1 | cut -d "=" -f 2)"
                        SKIP_BRO=yes
                        SKIP_OSSEC_AGENT=yes
                        ;;

      --only-pcap)
                        SKIP_INVERT=yes
                        SKIP_PCAP=yes
```
This results in nsm_sensor_ps-restart restarting both pcap and bro instead of just pcap.

This logic bug probably manifests for other --only-? options as well.

This logic bug probably manifests in other nsm_sensor_ps-? scripts as well.

**Comment by dougburks** [comment]
Potential fix:
https://groups.google.com/d/topic/security-onion/lwpkJmfDKVA/discussion

**Comment by dougburks** [comment]
@petiepooo, can you take a look at https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/commit/48f84381119563ae172471ea2d9951dc30abc044 and make sure I properly applied your suggested changes from https://groups.google.com/d/topic/security-onion/lwpkJmfDKVA/discussion?

Thanks!

**Comment by dougburks** [comment]
Pete's recommendations for testing from https://groups.google.com/d/topic/security-onion/lwpkJmfDKVA/discussion:
```
My recommendation for testing:
====================
Create test VM with multiple monitoring NICs
activate SecurityOnion in advanced mode listening on at least 2 NICs
run nsm_sensor_ps-status --sensor-name=[yourhost-em2] --only-prads
  note that it shows status for ossec, bro, and prads (error condition)
do the same for stop, start, and restart commands (optional)
run nsm_sensor_ps-status --sensor-name=[yourhost-em2] --only-bro
run nsm_sensor_ps-status --sensor-name=[yourhost-em2] --only-ossec-agent
  note that it shows status for ossec and bro (nonsense options allowed)
run nsm_sensor_ps-status --only-prads
  note that it shows status for prads on all interfaces (baseline)
run nsm_sensor_ps-status --only-prads --only-bro
  note that it shows status for bro and for prads on all interfaces (advanced baseline)
install the patch
run nsm_sensor_ps-status --sensor-name=[yourhost-em2] --only-prads
  note that it shows status for just prads on [em2] (fix works)
do the same for stop, start, and restart with other processes (fix works)
run nsm_sensor_ps-status --sensor-name=[yourhost-em2] --only-bro
run nsm_sensor_ps-status --sensor-name=[yourhost-em2] --only-ossec-agent
  note that it shows OOPS message (new check)
run nsm_sensor_ps-status --only-prads
run nsm_sensor_ps-status --only-prads --only-bro
  note that baseline behavior is the same)
```

**Comment by petiepooo** [comment]
@dougburks, I didn't test the start/stop/restart scripts, but changes to nsm_sensor_ps-status work as expected.  I used --only-snort-agent instead of --only-prads for testing...
I also tested the changes in commit 5309f5a to nsm_sensor, and I no longer get the OOPS there when given --start plus a --sensor_name.
Thanks!

**Comment by weslambert** [comment]
Looks good from my testing 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/10/securityonion-nsmnow-admin-scripts.html
