### ISSUE TITLE
Incorrect PulledPork BlackList File Location

### ISSUE THREAD

**Issue by fatalglitch** [Security-Onion-Solutions/security-onion#1120]
Fresh install to "Production" mode, and Pulled Pork complains about errors being unable to write to the blacklist file.

Unable to open /usr/local/etc/snort/rules/iplists/default.blacklist for writing! - No such file or directory
 at /usr/bin/pulledpork.pl line 1215.
        main::blacklist_write('HASH(0x1c3fbd0)', '/usr/local/etc/snort/rules/iplists/default.blacklist') called at /usr/bin/pulledpork.pl line 2136

While this isn't by itself catastrophic, it prevents Pulled Pork from truly completing, and therefore any disabledsid's don't get properly handled.

The fix is to modify PulledPork configuration and change the path of the below two config entries:

black_list=/etc/nsm/rules/black_list.rules
IPRVersion=/etc/nsm/rules/iplists

**Comment by callahant** [comment]
In all truth, I don't remember. I had no internet when initially setting up the system, so I had to go manually into the Snort configuration to add my feeds with my oinkcode. I may have manually enabled it at that time.
