### ISSUE TITLE
Squert view tab crashed and didn't come back up

### ISSUE THREAD

**Issue by macfred88** [Security-Onion-Solutions/security-onion#1123]
Hello all,

Thank you for all your wonderful support. for the past 2 weeks i've been experiencing an issue with my security onion Squert View tab. It crashed and didn't come back up. I tried sudo soup with no luck..
I reinstalled the master server module ... no luck...
I increased the Max size on php... no luck
I have about 1.5 TB hard drive and about 12 Gig RAM. 6 cores ...

I ran sudo sostat-redacted and there is no issues.. no disk being maxed out...

I don't know what to do next... Please Help!

Thank you very much. God Bless

This issue tracker is primarily used to track issues that need to be fixed and are added to our Roadmap:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Roadmap

If you are creating an issue just to ask a question, you will likely get faster and better responses by posting to our mailing list instead:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

If you have found a bug in Security Onion, you can continue with creating an issue here, but please make sure you have done the following:
- duplicated the issue on a fresh installation of the latest version
- include sostat-redacted output when relevant
- provide information about your system and how you installed Security Onion

**Comment by weslambert** [comment]
@macfred88,

Please pose your issue to the Security Onion mailing list as opposed to
this issue tracker:

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks,
Wes

**Comment by macfred88** [comment]
I will do that now.


Thank you Wes,


Regards,


Fred Michael

________________________________
