### ISSUE TITLE
Kibana Stop to show alerts.

### ISSUE THREAD

**Issue by JAEP2** [Security-Onion-Solutions/security-onion#1131]
Hello all,

I hope this is the correct place to write my issue.
Kibana stop to show alerts, I check the logs of elasticserach and kibana and seems everything is OK.

Everything seems OK, nsm status, logs, etc. Only I can see alerts from 24 hours before, but no recent alerts appear on the Kibana Panels..

Thanks in advanced for your help.

J.A

**Comment by dougburks** [comment]
Please send a detailed email to our mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
