### ISSUE TITLE
sostat: provide Docker container interface correlation

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1136]
Correlate value found within container in /sys/class/net/eth0/iflink to that of value found in /sys/class/veth*/ifindex to more easily identify which external Docker interface belongs to which container.

Essentially, automation of the following:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Docker#networking

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/16zMHfswwWE/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2017/10/securityonion-sostat-20120722.html
