### ISSUE TITLE
NSM: increase process priority for sniffing processes

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1138]
We should increase the process priority for sniffing processes like Snort, Suricata, Bro, and netsniff-ng.

https://www.nixtutor.com/linux/changing-priority-on-linux-processes/

**Comment by petiepooo** [comment]
The extremely-high performance systems go so far as to lock processes to exclusive CPU cores to avoid moving caches around on NUMA systems.  http://www.ksingh.co.in/blog/2016/09/08/working-with-numa-cpu-pinning/

**Comment by dougburks** [comment]
Yes, also see:
https://github.com/pevma/SEPTun
