### ISSUE TITLE
Setup: when running with -f option, validate sosetup.conf before making changes to system

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1159]

**Comment by dougburks** [comment]
At minimum, make sure we can't accidentally pass so-email.conf to sosetup.

Also, as we add new features to sosetup which requires new items in sosetup.conf, there should probably be a version check so that somebody doesn't try to automate today's sosetup with a sosetup.conf from 2 years ago.

**Comment by glallen01** [comment]
Maybe something like this could be useful:
```
$ anyconfig_cli -I shellvars -O json sosetup.conf 2>/dev/null | jq .
{
  "IDS_ENGINE": "snort",
  "DOMAIN": "example.com",
  "LOG_SIZE_LIMIT": "10000000000",
  "OSSEC_AGENT_LEVEL": "5",
...
$ anyconfig_cli -I shellvars -O json --gen-schema sosetup.conf 2>/dev/null  | jq .                                                                                                                                                                      4 ↵
{
  "type": "object",
  "properties": {
    "IDS_ENGINE": {
      "type": "string"
    },
    "DOMAIN": {
      "type": "string"
    },
...
```
[anyconfig](https://github.com/ssato/python-anyconfig) can read the shellvars into json, validate against a json schema to validate input, check types, and ensure all the right vars are set.

Then the schema could be customized to include something like the following for specific type and range validation: ```
{"HOME_NET": {"type": "array","items": { "type": "string","oneOf": [{"format": "ipv4"},{"format": "ipv6"}]}}}```

**Comment by dougburks** [comment]
Thanks for the suggestion @glallen01 !
