### ISSUE TITLE
NSM: Add new script to clear sensor backlog

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1162]
Sensors can sometimes develop a backlog of unified2 files under /nsm/sensor_data/.  
The goal us to provide a simple script to clear the backlog, instead of having to manually perform the required steps.

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/mMBhKRASWe4/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2017/11/securityonion-nsmnow-admin-scripts.html
