### ISSUE TITLE
soup: if Elastic enabled, copy /etc/apt/preferences.d/securityonion-docker

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1166]
It appears that the 14.04.5.4 ISO image remaster process removed /etc/apt/preferences.d/securityonion-docker.  This is preventing soup from downloading new Docker images.  soup needs to check if Elastic is enabled and, if so, copy /etc/apt/preferences.d/securityonion-docker.

**Comment by S1LM4R** [comment]
Is there a solution to this? After running sudo soup my 14.04.5.4 Kibana no longer runs.

Thanks

**Comment by dougburks** [comment]
Hi @S1LM4R ,

I'm not sure that this issue is causing your Kibana issue.

To troubleshoot your issue, please create a new thread on the security-onion group with "Elastic Beta" in the subject and include detailed info:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-sostat/commit/2541a96f7c7bb45e213668b97adab721f139fd27

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/bXbiG530iw8/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2017/11/securityonion-sostat-20120722.html
