### ISSUE TITLE
Squert: remove search link from context menu

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1169]
In Squert, selecting an indicator brings up a context menu and that menu has a search link that can query Elasticsearch.  However, our preferred method is to pivot directly to Kibana using the Kibana hyperlink.  To avoid confusion, remove the search link.

**Comment by dlee35** [comment]
@dougburks would you like to remove ':: SEARCH'  from the selection all together in Squert? If so, I'll comment out the appropriate rows in the mkPickBox function and issue a pull.

**Comment by dougburks** [comment]
Sounds good, thanks @dlee35 !

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion-squert/commit/f8a69178ff0f58f200d47e0fcebeeb4df75e3162

**Comment by dougburks** [comment]
16.04.4.1 RC2 submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/-PUvZkUTlro/discussion

**Comment by dougburks** [comment]
Security Onion 16.04.4.1 ISO image now available!
https://blog.securityonion.net/2018/05/security-onion-160441-iso-image-now.html
