### ISSUE TITLE
Mounting /nsm via NFS causes hard lockup of entire OS at regular intervals

### ISSUE THREAD

**Issue by sempervictus** [Security-Onion-Solutions/security-onion#1174]
Fresh install of the current ISO (experimental stack with ELK) to a KVM VM, with 24G of RAM and 12 cores, using suri and FPC locks up the OS at 1900 EST on the dot, presumably  during logfile/pcapfile rollover. NFS is being served from the underlying host via the bridge interface, and its not a lot of IO per se (using BPF to filter out hadoop traffic and the like). The host system is Arch, so "current" aside from the 4.9 kernel (grsec patched).
Nfs options are:
```
/srv/nfs/nsm       192.168.1.3(rw,no_root_squash,crossmnt,no_subtree_check,no_wdelay,sync)
```
for the server, and:
```
192.168.1.2:/srv/nfs/nsm  /nsm nfs noatime,sync,intr,rsize=32768,wsize=32768,clientaddr=192.168.1.3  0 0
```
for the client's fstab.

The host reports no errors, netdata graphs show NFS and underlying ZFS to be _well_ within request tolerances and suddenly dropping to zero at 1900 as the VM freezes. The VM itself is hard locked, even mouse input is out. Would be nice to run in a terminal so i could see dmesg, but over SSH, it a kernel message is generated, it never gets to STDERR
This is a pretty rational use case for situations where the core functionality of the instance can be placed into a 16G VM with the actual data volumes going to "smarter storage" mounted via NFS/Ceph/SMB/etc, and where the FPC volumes might make it impractical to perform daily offloads to larger/distributed storage.

I've disabled mmap'ed IO to no avail, and can occasionally cause this with nsm_sensor_ps-restart.
Will continue to try and narrow it down, but this doesnt seem related to the ELK piece (ES shouldn't even be doing bad things to itself on some regular 24h interval), nor did i see docs in the wiki for the approach.

**Comment by dougburks** [comment]
Hi @sempervictus ,

Please post this to our mailing list to see if others have experienced similar issues with NFS:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!

**Comment by petiepooo** [comment]
Cross-ref:
https://groups.google.com/d/msg/security-onion/GPX8pS6VVuo/RIindMOOAwAJ

**Comment by dougburks** [comment]
We generally recommend against using NFS.
