### ISSUE TITLE
sostat: clean up error/output when performing Docker interface correlation

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1175]
Clean up sostat output when directory does not exist when performing Docker interface correlation.  

For example:

ls: cannot access /sys/class/net/eth2/iflink: No such file or directory
ls: cannot access /sys/class/net/eth3/iflink: No such file or directory

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-sostat/commit/0c090a7b160d2bd94b95549c33cba5872ff509ff

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/9ewDhTcD_gE/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2017/12/securityonion-sostat-20120722_19.html
