### ISSUE TITLE
Update ElasticSearch to use a single document _type per index

### ISSUE THREAD

**Issue by rcgraves** [Security-Onion-Solutions/security-onion#1178]
Needed for ElasticSearch 6+. 

See also https://github.com/rocknsm/rock/issues/197 and https://www.elastic.co/guide/en/elasticsearch/reference/6.x/removal-of-types.html

**Comment by dougburks** [comment]
Hi @rcgraves ,

Yes, this is already on our list for RC1:
https://github.com/Security-Onion-Solutions/security-onion/issues/1172

Thanks!
