### ISSUE TITLE
Need to move ELSA related files to NAS.

### ISSUE THREAD

**Issue by syedzairani** [Security-Onion-Solutions/security-onion#1183]
I have follow guide "Adding new disk" but not working. My Security Onion is use only for ELSA. While the archive files are getting bigger. I need to move them to NAS. I have mounted a shared folder from NAS. The issue is. I cannot store the ELSA related files such as logs, databases, and sguil archive. Can somebody guide me.

This issue tracker is primarily used to track issues that need to be fixed and are added to our Roadmap:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Roadmap

If you are creating an issue just to ask a question, you will likely get faster and better responses by posting to our mailing list instead:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

If you have found a bug in Security Onion, you can continue with creating an issue here, but please make sure you have done the following:
- duplicated the issue on a fresh installation of the latest version
- include sostat-redacted output when relevant
- provide information about your system and how you installed Security Onion

**Comment by dougburks** [comment]
Please post your question to our mailing list instead:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
