### ISSUE TITLE
URGENT : soup won't upgrade existing mgmnt node - security updates

### ISSUE THREAD

**Issue by natan00013** [Security-Onion-Solutions/security-onion#1185]
Hi,
I can't manage to upgrade the management node. Once I ran soup and rebooted it, the load screens still shows up :
52 packages can be updated.
41 updates are security updates.
Running apt list --upgradable shows a pile of non-upgraded packages including securityonion-*
Please, help.

**Comment by weslambert** [comment]
@natan00013,

Please pose your question to the Security Onion mailing list:
http://groups.google.com/group/security-onion

In your post, please include the output of sostat redacted, attaching as a plain text file (or using a service like Pastebin.com), as well as the output of soup when it is run.

Thanks,
Wes
