### ISSUE TITLE
After soup on federation server Kibana fails to load. Your Kibana index is out of date, reset it or use the X-Pack upgrade assistant

### ISSUE THREAD

**Issue by gmaniakbg** [Security-Onion-Solutions/security-onion#1200]
Hello All After an update we lost Kibana visualization and dashboards. We where greeted by Your Kibana index is out of date, reset it or use the X-Pack upgrade assistant. I attempted to reset the index and create a new one but that does not resolve the problem. We attempted to reset the elastic instillation to no avail. sostat redacted included any insight what is going on is greatly appreciated
[sostat-redacted.txt](https://github.com/Security-Onion-Solutions/security-onion/files/1677562/sostat-redacted.txt)

.

**Comment by dougburks** [comment]
Hi @gmaniakbg ,

Please see:
https://github.com/Security-Onion-Solutions/security-onion/wiki/elastic-rc1.

If you have further questions or problems, please use the mailing list instead of this issue tracker.
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!

**Comment by gmaniakbg** [comment]
Thx Doug. Worked like a charm.
