### ISSUE TITLE
Validate HOME_NET during install/setup

### ISSUE THREAD

**Issue by ckozler** [Security-Onion-Solutions/security-onion#1205]
Hello -

During a fresh install tonight I made a typo in one of my addresses - I had something to the effect of 732.01.33.0/24

I think it'd be ideal to validate this in the setup screens to make sure each IP block provided is valid. A simple regex would suffice I imagine.

Albeit my own fat finger, this error was immediately evident to me so I chased my tail for the better part of a couple hours trying to figure it out. HOME_NET is configured in at least 2 separate places that I could find and the one that had me stumped was the config for bro

There may be some stuff in the docs perhaps but I could not locate anything that could point me in the right direction. While this probably would affect a small target user base, it could deter someone from using it or trialing it before buying. 

Thank you so much for providing an insanely useful and straightforward tool. Perhaps the straightforwardness of the config is what I had become accustomed to until my fat finger :-)

**Comment by dougburks** [comment]
Hi @ckozler ,

Replies inline.

> During a fresh install tonight I made a typo in one of my addresses - I had something to the effect of 732.01.33.0/24
> 
> I think it'd be ideal to validate this in the setup screens to make sure each IP block provided is valid. A simple regex would suffice I imagine.

I agree we should validate HOME_NET in Setup.  Here's what I'm thinking:

- put user's HOME_NET into an empty file called `home_net.conf`
- have Snort test it with: `snort -Tc home_net.conf`

I've added this issue to our Roadmap:
https://github.com/Security-Onion-Solutions/security-onion/wiki/2018

> Albeit my own fat finger, this error was immediately evident to me so I chased my tail for the better part of a couple hours trying to figure it out. HOME_NET is configured in at least 2 separate places that I could find and the one that had me stumped was the config for bro
> 
> There may be some stuff in the docs perhaps but I could not locate anything that could point me in the right direction. While this probably would affect a small target user base, it could deter someone from using it or trialing it before buying.

HOME_NET is documented on the PostInstallation page:
https://github.com/Security-Onion-Solutions/security-onion/wiki/PostInstallation

> Thank you so much for providing an insanely useful and straightforward tool. Perhaps the straightforwardness of the config is what I had become accustomed to until my fat finger :-)

Thanks!
