### ISSUE TITLE
Stuck: Promiscuous Mode NIC not seeing any traffic -- possible restriction with multiple MAC addresses same port?

### ISSUE THREAD

**Issue by antijackal** [Security-Onion-Solutions/security-onion#1210]
This may or may not be an issue with Security Onion, and I'm a newbie so I'll take any wisdom you can provide. I've followed instructions to the letter with the VMware 12 Workstation setup, adding the extra NIC, setting it in Bridged mode, running the Security Onion Setup, selecting that NIC (eth1) as the sniffer.

I tested the setup with Wireshark (admin mode of course), selected that NIC, and nothing. Completely stuck for the past 3 days and not able to get any packets. I feel like I'm missing something, but again I'll take any direction I can get on this. I know others have run into this because I've seen multiple posts with this same issue, but no resolutions. Help!

Best,
Antijackal

**Comment by dougburks** [comment]
Hi @antijackal ,

For support requests like these, please keep discussion on the mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!
