### ISSUE TITLE
ISO Image Stuck on Splash Screen

### ISSUE THREAD

**Issue by dustin2551** [Security-Onion-Solutions/security-onion#1222]
Hello my ISO image is stuck on splash screen. I installed older version but, it did'nt help. I try pressed the Esc key but, nothing happens.

**Comment by dougburks** [comment]
Hi @dustin2551 ,

Please post this question to our mailing list instead:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!

**Comment by dustin2551** [comment]
Okay
