### ISSUE TITLE
docker version?

### ISSUE THREAD

**Issue by glira** [Security-Onion-Solutions/security-onion#1233]
Do you have plans to port to docker?

**Comment by dougburks** [comment]
Hi @glira,

We are currently integrating the Elastic stack using Docker:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Docker

We expect to start moving our Ubuntu packages to Docker containers.

If you have any further questions, please send them to our mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!
