### ISSUE TITLE
NSM: sensor cleanup fails when there are a high number of pcaps

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1234]
https://groups.google.com/d/topic/security-onion/3Ex_cha8Ghw/discussion

https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/compare/master...tom564:patch-1

**Comment by amberwils** [comment]
hi

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/oExsbe8xBcw/discussion

**Comment by dougburks** [comment]
published:
https://blog.securityonion.net/2018/04/securityonion-nsmnow-admin-scripts.html
