### ISSUE TITLE
so-import-pcap - improve single pcap use case

### ISSUE THREAD

**Issue by websecusa** [Security-Onion-Solutions/security-onion#1239]
Hi,
I like the use of mergecap, but only if there are multiple pcaps to process.  I tried to run the so-import-pcap on a single netcapture.pcap (VERY LARGE PCAP), and mergecap is used.

Just thought that maybe if there is a single pcap used, that you may want to not use the mergecap feature.

Hope that this helps.  Security Onion is GREAT!!

**Comment by dougburks** [comment]
Hi @websecusa ,

I realize it may seem a little strange to mergecap a single pcap.  However, it does actually provide a useful function.  By running mergecap on that single pcap, it actually validates that the user has passed a file that is a valid pcap with no corruption. If it's an invalid or corrupted file, then mergecap will fail and so-import-pcap will not try to process any further.

Is running mergecap on your netcapture.pcap causing a problem?

**Comment by dougburks** [comment]
Just pushed a commit yesterday that should improve the single pcap use case:
https://github.com/Security-Onion-Solutions/securityonion-elastic/commit/47e1b1beeb4b7f404cd193d13a3656aac9ef7ee0

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/FDJ66pUgH8E/discussion

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/05/elastic-672-now-available-for-security.html
