### ISSUE TITLE
local snort rules not with security onion on hyper-v

### ISSUE THREAD

**Issue by maartendr2018** [Security-Onion-Solutions/security-onion#1246]
HI all,

I have recently installed security onion using the ISO on a hyper-v virtual machine. After going through the setup twice to install all services needed i tried to adjust some local snort rules to test the setup. I've configured snort locally and tried to test this by opening sguil and sending some traffic. However no alerts are received.
What i have done.
- in securityonion.conf
	adjusted the setting LOCAL_NIDS_RULE_TUNING to yes
- in local.rules	
	created a test rule to trigger on any ICMP traffic
	alert icmp any any <> any any (msg:"Testing ICMP traffic";sid:10001;)
	I tested the rule by doing: sudo snort -T -c /etc/nsm/rules/local.rules
	The rules is detected and I receive a "snort successfully validated the configuration".
- executed rule-update command.
	in the output of the command it does indicate LOCAL_NIDS_RULE_TUNING is set to yes. 
	However i don't see any output saying the file is written or processed. I'm not sure i should see one.
	In sid_change.log i do not see any rules being added with sid 10001 nor find my icmp any any

My sensor interface is currently eth1. When i start wireshark and trace interface eth1 I do see the ICMP traffic.
When i start sguil and open testmyids.com in my browser i do receive an alert. So i think snort is working fine for downloaded rules.
I did read some post indicating issues when running security onion on hyper-v but they all seemed to be related to the span port (mostly on 2012) and this seems OK here.
I assume many have this setup on Hyper-v, so there must be a solution.

Kind regards,

Maarten
[Sostat.txt](https://github.com/Security-Onion-Solutions/security-onion/files/1973654/Sostat.txt)

**Comment by dougburks** [comment]
Hi Maarten,

This appears to be a duplicate of the email you sent to our mailing list:
https://groups.google.com/d/topic/security-onion/JK3SU2frIUw/discussion

The mailing list is the correct place for discussing and troubleshooting things like this.

Thanks!

**Comment by maartendr2018** [comment]
Hi Doug,


My apologies for the inconvenience. I wasn't sure on which to use so i posted it in both. Thanks for the feedback though. In the future I’ll only use the mailing list. ;)



Kind regards,



Maarten De Ridder
Mobile: +324732/96.39.78
Email: maarten.deridder@meanit.be<mailto:maarten.deridder@meanit.be>
www: www.meanit.be<http://www.meanit.be/>

[1510064614289_meanit.JPG]

"Cybersecurity is not a technology problem, it's a people and management problem"


________________________________
