### ISSUE TITLE
Bro http/2 Analyzer Support 

### ISSUE THREAD

**Issue by chriswhitehat** [Security-Onion-Solutions/security-onion#1251]
An increasing number of sites are supporting HTTP 2.0 which manifests very different than HTTP 1.* traffic.  This analyzer adds an http2 log as well as intel framework extensions.  Because it is an analyzer it requires access to the compiled source of Bro to be compiled itself as opposed to a regular bro script.

https://github.com/MITRECND/bro-http2

As the http2 analyzer documentation states, there are two dependencies that would need to be resolved as well.

**Comment by dougburks** [comment]
Hi @chriswhitehat ,

I would think that Bro itself would support http2 by default at some point.  Do you know if they plan to merge this into Bro itself and, if so, when that might happen?
