### ISSUE TITLE
logStash can't start

### ISSUE THREAD

**Issue by cleverchou** [Security-Onion-Solutions/security-onion#1256]
1--->I run "so-logstash-start", 
2--->then get " so-logstash -- Logstash has started, but is still initializing...  [ WARN ]"
3--->/var/log/logstash as following:
       [logstash.agent           ] Failed to execute action                            
            {:action=>LogStash::PipelineAction::Create/pipeline_id:main, 
             :exception=>"Java::JavaLang::OutOfMemoryError",....}
      [2018-06-08T02:28:27,702][ERROR][logstash.agent           ] An exception happened when converging 
            configuration {:exception=>LogStash::Error, :message=>"Don't know how to handle 
            `Java::JavaLang::OutOfMemoryError` for `LogStash::PipelineAction::Create/pipeline_id:main`", 
            :backtrace=>...}
       [2018-06-08T02:28:27,847][ERROR][org.logstash.Logstash    ] java.lang.OutOfMemoryError: Java heap space
4--->run" so-logstash-status" ,showing
        so-logstash                                      [ FAIL ]

**Comment by dougburks** [comment]
Hi @cleverchou ,

Please send a detailed email to our security-onion mailing list, including sostat-redacted output:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!
