### ISSUE TITLE
so-elastalert-create

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1268]
https://github.com/bryant-treacle/Elastalert-Rule-Generator

**Comment by bryant-treacle** [comment]
I just finished  the so-elastalert-create script and ran through initial testing.  The most recent version is on my github.  Let me know what you think.

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-elastic/commit/0097aee52d01a76254600248beb4b5368f22ab3b

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2018/08/elastic-632-now-available-for-security.html
