### ISSUE TITLE
mysql: [ERROR] Could not open required defaults file: /etc/mysql/debian.cnf

### ISSUE THREAD

**Issue by Idriel** [Security-Onion-Solutions/security-onion#1285]
Before sosetup i run sudo soup
after that automated Setup sosetup -f sosetup_master is showing this error. 
mysql: [ERROR] Could not open required defaults file: /etc/mysql/debian.cnf

Please wait while...
 setting OS timezone to UTC...
 setting OSSEC timezone to UTC...
 restarting OSSEC...
 enabling securityonion.service in systemd...
 stopping services...
Enter password:
mysql: [ERROR] Could not open required defaults file: /etc/mysql/debian.cnf
mysql: [ERROR] Fatal error in defaults handling. Program aborted!

**Comment by dougburks** [comment]
Hi @Idriel ,

Please see:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MySQL-Upgrade-Errors

If you have further questions or problems, please use the mailing list instead of this Issue Tracker:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!

**Comment by Idriel** [comment]
tnx. 
sudo systemctl enable mysql.service && sudo apt -f install && sudo systemctl stop mysql.service && sudo systemctl disable mysql.service
After that installation passed just fine.
