### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by JonZeolla** [Security-Onion-Solutions/security-onion#1300]
I would like to start contributing to this project, but I'm not really sure where to start.  I did see the roadmap [here](https://github.com/Security-Onion-Solutions/security-onion/issues) but in poking around I haven't found the scripts that actually build Security Onion itself - the closest I have found is [this](https://github.com/Security-Onion-Solutions/securityonion-setup).  I did look through the wiki, but the closest thing I found to what I want is [this](https://github.com/Security-Onion-Solutions/security-onion/wiki/TeamMembers).  It's very likely I'm being dense and not looking in the right spot(s), so pointers are appreciated.  Regardless, I suggest that it should exist as a [CONTRIBUTING.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) here for posterity.

**Comment by dougburks** [comment]
Hi @JonZeolla ,

Replies inline.

> I would like to start contributing to this project, but I'm not really sure where to start. I did see the roadmap here

You may also want to see https://github.com/Security-Onion-Solutions/security-onion/wiki/2018 as it lists issues in a rough order of prioritization and scheduling.

> but in poking around I haven't found the scripts that actually build Security Onion itself - the closest I have found is this.

Security Onion is currently a collection of Ubuntu packages and Docker images all bundled together into an ISO image.  Ubuntu packages can be found here:
https://launchpad.net/~securityonion/+archive/ubuntu/stable

You can get the source for any of our packages by doing the following at a terminal (replacing PACKAGE-NAME with the name of the package that you want the source for):
```
apt-get source PACKAGE-NAME
```

Some of our packages have their own Github repos at:
https://github.com/Security-Onion-Solutions

Docker images can be found at https://hub.docker.com/u/securityonionsolutions/. Dockerfiles used to build those Docker images can be found at https://github.com/Security-Onion-Solutions/securityonion-docker.

The ISO is built from Ubuntu 16.04 Server using a script called so-iso-build which in turn downloads all packages and Docker images and then builds the final ISO image.

> I did look through the wiki, but the closest thing I found to what I want is this. It's very likely I'm being dense and not looking in the right spot(s), so pointers are appreciated. Regardless, I suggest that it should exist as a CONTRIBUTING.md here for posterity.

I've started with a basic CONTRIBUTING.md:
https://github.com/Security-Onion-Solutions/security-onion/blob/master/CONTRIBUTING.md

We can add more detail later if you have additional questions or feedback.

Thanks!

**Comment by JonZeolla** [comment]
Ah, `so-iso-build` is what I was looking for.  Would you be able to point me to where that is?  [I couldn't find it](https://github.com/search?q=org%3ASecurity-Onion-Solutions+so-iso-build&type=Code).

Also, how are the DEBs created?  I was able to find some of the packages when solving [this issue](https://groups.google.com/forum/#!topic/security-onion/OEHPAlgNOFg) from the forums, but not how they're created.  In this specific scenario, I think a cleaner solution than what I provided on the forums is to distribute a source package, and leverage `apt-get source` or similar.

**Comment by dougburks** [comment]
> Ah, so-iso-build is what I was looking for. Would you be able to point me to where that is? I couldn't find it.

`so-iso-build` is part of the `securityonion-iso` package.  I haven't created a github repo for that package yet, but will plan to do so next week.

> Also, how are the DEBs created? I was able to find some of the packages when solving this issue from the forums, but not how they're created. In this specific scenario, I think a cleaner solution than what I provided on the forums is to distribute a source package, and leverage apt-get source or similar.

We use Launchpad to build and host DEBs.  For more information, please see:
https://help.launchpad.net/Packaging/PPA

Thanks!
