### ISSUE TITLE
Logstash - database path crash

### ISSUE THREAD

**Issue by rowlings** [Security-Onion-Solutions/security-onion#1333]
Hello everybody, 
I'd like to ask how can I use database for geoip filter. I've created new config file for filtering logs, which worked pretty well I guess. Then I tried to redirect to another database GeoLiteCity.dat in /etc/logstash/ writing this in my filter database => "/etc/logstash/GeoLiteCity.dat and it showed me error in Logstash's file telling me that path is wrong or the file could not be read. I even tried the other database format .mmdb and it's not working for me either. Logstash is running on Docker image and /usr/share/logstash folders are missing. But it still works, I suppose Docker uses some symlinks or something (maybe this files /usr/share/GeoIP/*). My actual question would be, where should I put my .dat file to make it read that geoip database and is it possible to edit MaxMind's database somehow (.dat). Thanks for your help :)
 
![geoip](https://user-images.githubusercontent.com/36776505/45705741-fefb0e80-bb3f-11e8-90c1-40ade35b20e8.PNG)

**Comment by dougburks** [comment]
Hi @rowlings ,

Please send all questions to the security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!
