### ISSUE TITLE
securityonion-bro-scripts: add HASSH

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1338]
https://github.com/salesforce/hassh

**Comment by weslambert** [comment]
From: https://github.com/salesforce/hassh/tree/master/bro

>Note that bro currently ( <= v2.5.5) has a bug which reverses the Client/server flag, however the logic in this script reverses and in effect corrects this bug. Therefore once the bro bug is patched, the logic in this script also needs return to the proper form. Failure to update bro and not the script will result in the Server and Client packets being processed incorrectly, in effect swapping around hassh with hassServer.

**Comment by dougburks** [comment]
Logstash config:
https://github.com/Security-Onion-Solutions/securityonion-elastic/pull/34

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/01/bro-261-elastic-654-ja3-and-hassh-now.html
