### ISSUE TITLE
Syslog Does Not Put Some Data in Logstash

### ISSUE THREAD

**Issue by hfakar** [Security-Onion-Solutions/security-onion#1344]
Hello there,

I am sending Microsoft Sysmon logs into the SO from my SIEM appliance. Even though there are 40000 events sent in a day I can only see some portion of the data. 

![image](https://user-images.githubusercontent.com/13640312/46674291-6dce0380-cbe4-11e8-9e63-4872b3c4861d.png)

Is this about some filtering on syslog or maybe logstash?
I made sure that all the logs havecame to syslog.

**Comment by weslambert** [comment]
Hi @hfakar ,

Please pose your question to the Security Onion mailing list before creating an issue.
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists#mailing-lists

In your post, please provide a detailed explanation of the current process you are using to send Sysmon logs to Security Onion.

Thanks,
Wes
