### ISSUE TITLE
pfring upgrade to v17

### ISSUE THREAD

**Issue by andrewalbertson93** [Security-Onion-Solutions/security-onion#1347]
The version of the PF_RING high performance packet capture library that the latest ntopng package uses, is newer than the version Security Onion uses, and is incompatible with it. As a result when you start ntopng it will throw an error like this: "[PF_RING] Wrong RING version: kernel is 16, libpfring was compiled with 17", and if you start it with the "service ntopng start" command it will also throw the error "* Unable to start ntopng". However, ntopng will actually fail over to using plain libpcap for packet capture and continue to work, though with more packet loss if there is much load. Do note that you cannot aggregate capture interfaces if ntopng is failing over to plain libpcap, like with "--interface=eth1,eth2" in the config. That will prevent ntopng from running at all. Once Security Onion is able to take advantage of the newer PF_RING version, these error messages and this aggregation limitation should go away.

**Comment by dougburks** [comment]
There are no plans to upgrade pfring at this time.

Our next generation platform Hybrid Hunter uses AF_PACKET instead of PF_RING.
