### ISSUE TITLE
Some logstash parsing issues when ingesting pfsense filterlog

### ISSUE THREAD

**Issue by StewGoin** [Security-Onion-Solutions/security-onion#1348]
I noticed some grok errors (particularly for items that had sequence numbers w/ : in them for entries that tried to predict the end sequence number). I also noticed that filterlog events were being output to both the logstash-syslog and logstash-firewall indexes, so I made an edit to reduce that duplication.

My setup at home uses a centralized syslog-ng server that's relaying the pfsense logs, but they are kept intact.

I edited `/etc/logstash/conf.d/6201_firewall_pfsense.conf` to handle the unusual sequence number situation... it may not be the most efficient way, but I'm newbish to ELK still:
```
# Author: Wes Lambert
# Last Update: 10/16/2018 by Jason Ashbaugh


filter {
  if [type] == "filterlog" {
    grok {
      match => ["message", "(%{NONNEGINT:rule_number})?\,(%{NONNEGINT:sub_rule_number})?\,(%{DATA:anchor})?\,(%{NONNEGINT:tracker_id})?\,%{DATA:interface}\,%{DATA:reason}\,%{DATA:action}\,%{DATA:direction}\,%{NONNEGINT:ip_version},%{GREEDYDATA:sub_msg}"]
    }
    if [ip_version] =~ "4" {
      csv {
        source => [sub_msg]
	columns => ["ipv4_tos","ipv4_ecn","ipv4_ttl","ipv4_id","ipv4_offset", "ipv4_flags","ipv4_protocol_id","ipv4_protocol","ipv4_protocol_length","source_ip","destination_ip","source_port","destination_port","data_length","tcp_flags","sequence_number","ack","window","urg","options"]
      	separator => ","
      }
    }
    if [ip_version] =~ "6" {
      csv {
        source => [sub_msg]
	columns => ["class","flow_label","hop_limit","protocol","protocol_id","length","source_ip","destination_ip","source_port","destination_port","data_length","tcp_flags","sequence_number","ack","window","urg","options"]
        separator => ","
      }
    }
    if ":" in [sequence_number] {
      grok {
        match => ["sequence_number", "(%{NONNEGINT:sequence_start_number}):(%{NONNEGINT:sequence_end_number})"]
      }
      mutate {
        copy => { "sequence_start_number" => "sequence_number" }
        remove_field => [ "sequence_start_number" ]
      }
    }
    mutate {
      convert => [ "destination_port", "integer" ]
      convert => [ "source_port", "integer" ]
      convert => [ "ip_version", "integer" ]
      replace => { "type" => "firewall" }
      add_tag=>  [ "pfsense","firewall" ]
      remove_field => [ "sub_msg" ]
    }
  }
}
```

I also edited `/etc/logstash/conf.d/9034_output_syslog.conf` to not grab things tagged with `firewall`:
```
# Author: Justin Henderson
#         SANS Instructor and author of SANS SEC555: SIEM and Tactical Analytics
# Updated by: Doug Burks
# Last Update: 10/18/2018 by Jason Ashbaugh

filter {
  if "syslog" in [tags] and "test_data" not in [tags] {
    mutate {
	  ##add_tag => [ "conf_file_9034"]
	}
  }
}
output {
  if "syslog" in [tags] and "test_data" not in [tags] and "firewall" not in [tags] {
    elasticsearch {
      hosts => elasticsearch
      index => "logstash-syslog-%{+YYYY.MM.dd}"
      template_name => "logstash"
      template => "/logstash-template.json"
      template_overwrite => true
    }
  }
}
```

I haven't fully vetted all the Kibana dashboards, etc... to make sure they didn't need the log duplication for some reason, but if so I have to believe it would be more efficient to alter the searches rather than double up on firewall logs in two different indexes.

I haven't yet learned enough to know what I need to do with the new field `sequence_end_number` to make sure the template knows what to do with it, but it's not breaking anything anymore at least!

**Comment by weslambert** [comment]
HI @StewGoin, 

Thank you for reaching out.  I will look into the parsing issue(s) for `sequence_number` et al.  We are aware of duplication for multiple indices, and are planning to address this issue in a little bit different manner.

Thanks,
Wes

**Comment by StewGoin** [comment]
Awesome, let me know if I can do anything to help out with testing / etc...

**Comment by StewGoin** [comment]
Also looks like ICMP messages bork with logstash errors (icmp format differs past the destination_ip) -- I'll take a stab at adding in logic to handle those vs. udp/tcp tomorrow.

**Comment by dougburks** [comment]
We made some recent updates to the pfsense filterlog parsing:
https://github.com/Security-Onion-Solutions/security-onion/issues/1696
https://github.com/Security-Onion-Solutions/security-onion/issues/1698
