### ISSUE TITLE
Not able login squert using same squil username and password

### ISSUE THREAD

**Issue by suchandbabu** [Security-Onion-Solutions/security-onion#1351]
Hi,
Thanks in advance.

I have installed security Onion 16.04.5.3. I am not able to login to squert using the same username and password of Sguil. Squert login Page always shows username or password is wrong.
Can someone please help me to resolve this issue.

This issue tracker is primarily used to track issues that need to be fixed and are added to our Roadmap:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Roadmap

If you are creating an issue just to ask a question, you will likely get faster and better responses by posting to our mailing list instead:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

If you have found a bug in Security Onion, you can continue with creating an issue here, but please make sure you have done the following:
- duplicated the issue on a fresh installation of the latest version
- include sostat-redacted output when relevant
- provide information about your system and how you installed Security Onion

**Comment by weslambert** [comment]
Hi @suchandbabu 

It looks like you've already posted this issue on the Security Onion mailing list:

https://groups.google.com/d/msg/security-onion/4bwou7J9ctM/RwycCpm9CQAJ

Please wait for a response to your previous question.  This issue tracker is used by the Security Onion team to track confirmed issues.

Thanks,
Wes

**Comment by enoshgeorge** [comment]
Hi @suchandbabu and @weslambert 
I am also facing the same issue. Hoping for a solution to come up soon.
Thanks,
Enosh
