### ISSUE TITLE
Login issue on squert

### ISSUE THREAD

**Issue by suchandbabu** [Security-Onion-Solutions/security-onion#1352]
I have installed security Onion 16.04.5.3. I am not able to login to squert using the same username and password of Sguil. Squert login Page always shows username or password is wrong.

Please help me to resolve this.

**Comment by weslambert** [comment]
Hi @suchandbabu 

It looks like you've already posted this issue on the Security Onion mailing list:

https://groups.google.com/d/msg/security-onion/4bwou7J9ctM/RwycCpm9CQAJ

Please wait for a response to your previous question.  This issue tracker is used by the Security Onion team to track confirmed issues.

Thanks,
Wes

**Comment by suchandbabu** [comment]
above link is not posted by me. Also i cant see any solutions for this issue in the above mentioned link.
