### ISSUE TITLE
Wazuh API

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1353]
Investigate what it would take to add the Wazuh API

**Comment by Alleboom** [comment]
Hey Doug, I started building a container for this for our deployments, just need to work on the kibana plug in. Do you have any community container addition guidelines?

**Comment by Alleboom** [comment]
Hey Doug, I'm working on this as well for our deployments. I made a container that supports the wazuh api, but I will need to configure it correctly to modify the host OS files that are appropriate. Do you have any policy on community additions?

**Comment by stondino00** [comment]
Is there any update on when this will be incorporated into security onion?  Right now we feel the host based use of wazuh is not very useful and are forced to run a separate install of wazuh virtual machine to get the api functionality.

**Comment by weslambert** [comment]
Hi @stondino00 ,

We've already incorporated the Wazuh API into our upcoming Hybrid Hunter release, and don't have plans to including the Wazuh API with the current release.  What part of the API functionality are you looking to utilize that you are not able to use at the moment?

Thanks,
Wes

**Comment by dougburks** [comment]
Wazuh API is already included in Hybrid Hunter.
