### ISSUE TITLE
Setup: after configuring network, remind user to run Setup after reboot

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1368]

**Comment by digininja** [comment]
Could you set something on the main user's account that checks if the first stage has been run and pops something up when they log in after the reboot?

**Comment by dougburks** [comment]
Also see:
https://github.com/Security-Onion-Solutions/security-onion/issues/1382
https://github.com/Security-Onion-Solutions/security-onion/issues/1379
https://github.com/Security-Onion-Solutions/security-onion/issues/1383

Once these changes are published it should look like this:

User installs ISO image, reboots, logs in, and is prompted to run Setup:
![1-run-setup](https://user-images.githubusercontent.com/1659467/49394588-52720700-f702-11e8-9f6a-8628d9f94601.PNG)

User runs Setup and configures network interfaces, reboots, logs back, and is prompted to run Setup again to continue to the second phase of Setup:
![2-run-setup-again](https://user-images.githubusercontent.com/1659467/49394652-7df4f180-f702-11e8-94b4-7db437b0e5a9.PNG)

Once the second phase of Setup completes, the default wallpaper with no prompts will be copied into place:
![3-default-wallpaper](https://user-images.githubusercontent.com/1659467/49394677-8fd69480-f702-11e8-8510-248346447367.PNG)

**Comment by digininja** [comment]
Sounds like a good solution to me.

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2018/12/updated-securityonion-iso-securityonion.html
