### ISSUE TITLE
Issue located when installing OS in Spanish languaje

### ISSUE THREAD

**Issue by Escalibur7** [Security-Onion-Solutions/security-onion#1387]
Hey guys, 

spanish developer here, this is just a friendly message as I already have installed this in English because I am quite  familiar with English language.

When trying to install version securityOnion 16.04.5.4 with Spanish languaje the installation cannot finish as there are a problem when copying / installing ubiquiti unifi. 

We have tried in different computers and also in virtual machines, the problem just appear when we set spanish languaje.

computers: 
lenovo t440, processor i5
lenovo t450, processor i5
virtual machines vmware and oracle virtual box running in the same computer.

When installing english languaje, everything ok
When installing spanish languaje, installation stacks when copying ubiquiti unifi.

Regards

**Comment by weslambert** [comment]
Hi @Escalibur7,

Please see the following:

https://github.com/Security-Onion-Solutions/security-onion/wiki/FAQ#why-does-the-installer-crash-when-selecting-a-non-english-language

In the future, if you have an issue, please post a message via the mailing list before creating an issue.

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists#mailing-lists

Thanks!
Wes

**Comment by Escalibur7** [comment]
Oki,

Regards
