### ISSUE TITLE
NSM: nsm_server_configure_sshd should check for existing config

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1396]
We should consider checking for existing config in `/etc/ssh/sshd_config` and consider adding our config to the top of the file so that custom matches aren't affected.
 
https://groups.google.com/d/msg/security-onion/dbKxNrUfGmc/9QoVrAHeBwAJ

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/eUwr6UMHILQ/discussion

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/01/securityonion-nsmnow-admin-scripts.html
