### ISSUE TITLE
Setup: Prevent ES ports from being allocated for snort_agent

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1397]
Prevent ES ports (9200/9300) from being allocated for snort_agent.

This can happen when there are more than 11 entries in sensortab.

https://groups.google.com/d/msg/security-onion/AMceylxvXJY/lL3N9UHmBwAJ
https://github.com/Security-Onion-Solutions/securityonion-setup/pull/40

**Comment by branchnetconsulting** [comment]
I updated the pull request to also exclude Logstash port 9600 from being allocated for snort_agent.

**Comment by dougburks** [comment]
PR:
https://github.com/Security-Onion-Solutions/securityonion-setup/pull/40

Thanks @branchnetconsulting !

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/MWVXKW8Tw3s/discussion

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2018/12/securityonion-setup-20120912.html
