### ISSUE TITLE
securityonion-elastic: enable Java Execution Engine in Logstash

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1436]
Add the following to `logstash.yml`:
```
# Java Execution Engine provides much better performance
pipeline.java_execution: true
```

Add the following to `jvm.options`:
```
# Avoid StackOverflowError when enabling Java Execution Engine
# https://github.com/elastic/logstash/issues/10131
-Xss16M
```

**Comment by mattkaar** [comment]
Just wanted to say thanks for this fix! I was troubleshooting slow Logstash startup (~10m) on a fresh 16.04.5.6 install, and this brought it down to <2m.

**Comment by dougburks** [comment]
Hi @mattkaar ,

Thanks, we're excited about the improved Logstash startup as well!  

Please note that if you're on 16.04.5.6, then you're running Logstash 6.5 and Java Execution Engine is considered `Beta`.  It's been promoted to `GA` in Logstash 6.6 and so we are rolling this out to all users along with our 6.6 Docker images.

**Comment by mattkaar** [comment]
@dougburks Good to know! This is for a training environment, so I'll take the improved startup time over the risks of the beta. Looking forward to the same with Logstash 6.6.

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/FDJ66pUgH8E/discussion

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/05/elastic-672-now-available-for-security.html
