### ISSUE TITLE
Squil is dark when accessing over x11

### ISSUE THREAD

**Issue by austino5308** [Security-Onion-Solutions/security-onion#1440]
I have searched everywhere and for the life of me, I cannot figure out this issue.

My theme is set to "Menta" in Parrot OS which is a light colored theme and when I ssh -x into my security onion box, sguil is a dark theme with white text which makes looking at alerts impossible. Everything else like wireshark and all the other tools I can access over x11 looks fine. 
![image](https://user-images.githubusercontent.com/18233106/52505306-1606cf80-2bb9-11e9-9cd2-42991a5ef458.png)

**Comment by dougburks** [comment]
Hi @austino5308 ,

I'm not sure what would cause that issue, but here are some potential workarounds.  You could try installing the Sguil client locally on your Parrot OS installation.  Alternatively, you could create an Analyst VM and run Sguil locally that way:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Analyst-VM
https://github.com/Security-Onion-Solutions/security-onion/wiki/ConnectingtoSguil#connecting-to-sguild-from-an-analyst-machine

If you have further questions or problems, please send them to our mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!
