### ISSUE TITLE
Kibana: HIDS Alerts Dashboard - Replace syslog-host_from with agent.name

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1442]
Consider replacing `syslog-host_from` field with `agent.name` field in `OSSEC Alerts - Event Summary` visualization.

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/FDJ66pUgH8E/discussion

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/05/elastic-672-now-available-for-security.html
