### ISSUE TITLE
securityonion-web-page: add Security Onion documentation

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1446]
Since we've started to migrate to readthedocs, we have the ability to generate a PDF/HTML.  We should include the documentation locally, to make it easier for folks (especially airgapped) to find and have access to that documentation.

Ex. 

https://media.readthedocs.org/pdf/securityonion/latest/securityonion.pdf
https://readthedocs.org/projects/securityonion/downloads/htmlzip/latest/

This may also relate to:

#571

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/dTf2Fe-0yTc/discussion

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/05/securityonion-web-page-20141015.html
