### ISSUE TITLE
Setup: disable Bro syslog.log by default in Production Mode

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1457]

**Comment by wdpless** [comment]
Is that where our external devices are sending our logs?

**Comment by dougburks** [comment]
As Bro is monitoring your network traffic, if it sees cleartext syslog traffic, it will log that to its `syslog.log` file as if it were the actual syslog collector.  Most networks have syslog traffic on them and this can be quite voluminous.  Many folks find that this duplication of syslog wastes disk space and processing power, so we are considering disabling it by default.  Folks could still enable if they choose to do so.

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/Yyx19UEyCbo/discussion

Published:
https://blog.securityonion.net/2019/02/securityonion-setup-20120912.html
