### ISSUE TITLE
Change Snort start script

### ISSUE THREAD

**Issue by cecklesd** [Security-Onion-Solutions/security-onion#1462]
I would like to run Snort in IPS mode. I understand it's not supported. But, I would like to know where the startup script is or the variables to start snort so I can modify to my needs.

**Comment by dougburks** [comment]
Snort is started by `/usr/sbin/nsm_sensor_ps-start`.  If you modify this file, please note your changes will be overwritten during upgrades.  As you mentioned, we do not provide any support for running in IPS mode.

If you further questions or problems NOT related to IPS mode, please use our mailing list:
https://securityonion.net/docs/mailinglists

Thanks!
