### ISSUE TITLE
securityonion-sostat: implement better error handling for zero packet count

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1464]
See: https://groups.google.com/d/msg/security-onion/1n5iLbO-wI0/0efx-Pm8BQAJ

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/CznWqiFc-gM/discussion

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/03/securityonion-sostat-20120722.html
