### ISSUE TITLE
the commenting out of local.rules

### ISSUE THREAD

**Issue by sdaigl** [Security-Onion-Solutions/security-onion#1466]
This is not really a bug, but I would like to know if it's possible to have a better solution.

I like to test some rules out directly in the console and using the local.rules file.   Starting snort like follows:
commenting out the downloaded rules in the snort.conf file, and enabling local.rules
then executing the following:
so-stop
snort -A  console  -b -i ens160 -c  /etc/nsm/cisco-virtual-machine-ens160/snort.conf 
with this configuration  I can test alot faster.
 the problem I have is that, even if I do a so-stop, the nsm-watchdog cron job is still running
the job calls the script so-nsm-watchdog ou the calls out nsm_sensor_ps-restart who recomments out  local.rules in snort.conf
of course, I can get everything working if I disable the nsm-watchdog manually.
I know this is just to test some rules out. but it would be fun to have a solution specifically not to run the nsm-watchdog script during a so-stop.

**Comment by dougburks** [comment]
Hi @sdaigl ,

Have you considered running `rule-update`?  That should merge `local.rules` into `downloaded.rules`.

For more information, please see:
https://securityonion.net/docs/AddingLocalRules

If you have further questions or problems, please use our mailing list:
https://securityonion.net/docs/MailingLists

Thanks!

**Comment by sdaigl** [comment]
hum, I am looking more of a way to bypass the downloaded rules, to make it faster for testing specific rules of my own. 
  OK I guess I could use disable-sid with a pcre to only enable the local rules the run update-rules etc. they are many ways around it.
but why running a watchdog when the sensor is not running?
