### ISSUE TITLE
Unable to find my keyboard type (Dutch - Belgian - Flemish)

### ISSUE THREAD

**Issue by willemdh** [Security-Onion-Solutions/security-onion#1471]
I'm unable to find my keyboard type (Dutch - Belgian - Flemish), which makes it very hard to properly use Security Onion. On Latest Ubuntu, I do find my keyboard.

![image](https://user-images.githubusercontent.com/6462991/53732342-f4c69580-3e7d-11e9-9672-aa0c3b2b91e5.png)

![image](https://user-images.githubusercontent.com/6462991/53732436-38b99a80-3e7e-11e9-9b45-e4d3fbfcb086.png)

As the Flemish part of Belgium all use the same azerty keyboard, which does not seem available in Security Onion, I'm wondering if it would be possible to add this somehow.

**Comment by dougburks** [comment]
Hi @willemdh ,

If Ubuntu works for you, then you can simply add our packages on top of your Ubuntu 16.04 installation as described here:
https://securityonion.readthedocs.io/en/latest/InstallingOnUbuntu.html

If you have further questions or problems, please use our mailing list:
https://securityonion.readthedocs.io/en/latest/MailingLists.html

Thanks!
