### ISSUE TITLE
[REQ] add Elastic Stack Prometheus exporter docker image to SO

### ISSUE THREAD

**Issue by madeinoz67** [Security-Onion-Solutions/security-onion#1474]
It would be nice to have the ability to independently monitor and alert on Elastic Stack instance in SO via prometheus <https://prometheus.io>

To do this an exporter for prometheus is required and this project -<https://github.com/justwatchcom/elasticsearch_exporter> 
seems to has already solved the problem. 

Could this be integrated within the SO distribution?

**Comment by dougburks** [comment]
Hi @madeinoz67 ,

Our new platform Hybrid Hunter (currently in testing) already has Grafana built in:
https://www.reddit.com/r/securityonion/comments/a1x3wy/security_onion_hybrid_hunter_prealpha_release_104/

**Comment by madeinoz67** [comment]
I was more after the inclusion of the exporter for monitoring and alerting on the underlying elastic stack instance for reliability engineering not really for SO dashboards with grafana, but grafana for dashboards will be awesome

**Comment by dougburks** [comment]
Yes, we included Grafana specifically for reliability engineering.
