### ISSUE TITLE
securityonion-samples-mta: Add/Remove PCAPs

### ISSUE THREAD

**Issue by phil1090** [Security-Onion-Solutions/security-onion#1476]
Remove 2018-06-08-malspam-infection-traffic.pcap
Add 2019-02-28-Fallout-EK-from-HookAds-campaign.pcap - Fix TCP checksums first
Add 2019-02-07-cred-stealer-via-FTP-traffic.pcap
Add 2019-02-12-Hancitor-infection-with-Ursnif.pcap

**Comment by dlee35** [comment]
Add 2018-12-07-Trickbot-infection-traffic-ser1207.pcap
https://www.malware-traffic-analysis.net/2018/12/07/index2.html

**Comment by phil1090** [comment]
Add 2019-02-07-cred-stealer-via-FTP-traffic.pcap

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/TNTNRpwRwKE/discussion

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/05/securityonion-samples-mta-20150103.html
