### ISSUE TITLE
securityonion-elastic: correct separator in 1122_preprocess_bro_socks.conf

### ISSUE THREAD

**Issue by dlee35** [Security-Onion-Solutions/security-onion#1485]
The separator field in 1122_preprocess_bro_socks.conf is current defined as four spaces and should be a tab.

**Comment by dlee35** [comment]
PR #52: https://github.com/Security-Onion-Solutions/securityonion-elastic/pull/52

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/FDJ66pUgH8E/discussion

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/05/elastic-672-now-available-for-security.html
