### ISSUE TITLE
Setup: sudo fails during sosetup if NOPASSWD:ALL not enabled

### ISSUE THREAD

**Issue by jason-green-io** [Security-Onion-Solutions/security-onion#1490]
Under certain circumstances, when sosetup runs the 3 ssh sudo commands to get details for the autossh forward IP config on non master nodes, sudo will fail if a password is required because it doesn't have a tty. This works for the other commands run on the master since it pops open an xfce terminal and allows sudo to ask for the password. I got around this by making the sudo user run commands without the password. If the ssh/sudo user on the master is required to have NOPASSWD:ALL in sudoers, the sosetup dialog and documentation should be explicit. Or sosetup should ensure sudo can grab a password.

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/ABNDFNi_GyU/discussion

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/03/securityonion-setup-20120912.html
