### ISSUE TITLE
Cant Install Security Onion on Ubuntu 18.04.2 

### ISSUE THREAD

**Issue by RichardPhilipsRoy** [Security-Onion-Solutions/security-onion#1492]
E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by dougburks** [comment]
Hi @RichardPhilipsRoy ,

Yes, that's correct.  We only support Ubuntu 16.04 at this time.

For more information, please see:
https://securityonion.readthedocs.io/en/latest/download.html

Thanks!
