### ISSUE TITLE
Apparmor exclude when moving SQL to another drive

### ISSUE THREAD

**Issue by glwallum** [Security-Onion-Solutions/security-onion#1503]
Confused on the AppArmor SQL modifications needed.Any assisstance would be appreciated

**Comment by dougburks** [comment]
Hi @glwallum ,

Please send a detailed email to our mailing list and include details about what you've tried so far and what exactly is confusing.

https://securityonion.readthedocs.io/en/latest/mailing-lists.html

Thanks!
