### ISSUE TITLE
Cloud Install: Command 'sosetup' not found

### ISSUE THREAD

**Issue by srinathganesh** [Security-Onion-Solutions/security-onion#1504]
If you have found a bug in Security Onion, you can continue with creating an issue here, but please make sure you have done the following:
- duplicated the issue on a fresh installation of the latest version [Yes, Fresh Install]
- include sostat-redacted output when relevant [Sorry, I dont know that step]
- provide information about your system and how you installed Security Onion [PROVIDED]

I am Installing Security Onion in EC2 Ubuntu Server using the doc at https://securityonion.readthedocs.io/en/latest/cloud-client.html

There is a step that asks me to execute command sudo sosetup

![image](https://user-images.githubusercontent.com/43715636/56504226-7e691a00-6535-11e9-88fc-8e3a8906141d.png)

This fails with error Command 'sosetup' not found and search for the error online does not give any solutions.

what else do I search? 
![image](https://user-images.githubusercontent.com/43715636/56504212-77420c00-6535-11e9-9e9e-817c792c55c8.png)

**Comment by dougburks** [comment]
Hi @srinathganesh ,

It sounds like you started with Ubuntu 16.04 but haven't installed our packages yet.  You'll want to follow the instructions here:
https://securityonion.readthedocs.io/en/latest/production-deployment.html

If you have further questions or problems, please use our mailing list:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html

Thanks!
