### ISSUE TITLE
When I am doing backup, SMB traffic full the disc

### ISSUE THREAD

**Issue by PericoMele** [Security-Onion-Solutions/security-onion#1511]
Hi people:

When I am doing the backup of the servers, SMB traffic do the disc full. I tried to follow this guide but I continue receiving the smb logs and snmp logs, etc.

[https://thecomputersecurityblog.wordpress.com/2015/04/23/20/](https://thecomputersecurityblog.wordpress.com/2015/04/23/20/)

Anybody could I help me? I am thinking to do a script to clean the snorb logs but before I prefer ask you.

Thanks a lot
Regards
Dani

**Comment by weslambert** [comment]
HI @PericoMele ,

As I mentioned in the following issue:

https://github.com/Security-Onion-Solutions/security-onion/issues/1510#issuecomment-487575281

... please avoid posing your question here, as the mailing list is more suitable for this type of discussion.

Thanks,
Wes
