### ISSUE TITLE
Can we set up Security Onion on AWS to monitor physical devices, servers?

### ISSUE THREAD

**Issue by Vaishag** [Security-Onion-Solutions/security-onion#1513]
This issue tracker is primarily used to track issues that need to be fixed and are added to our Roadmap:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Roadmap

If you are creating an issue just to ask a question, you will likely get faster and better responses by posting to our mailing list instead:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

If you have found a bug in Security Onion, you can continue with creating an issue here, but please make sure you have done the following:
- duplicated the issue on a fresh installation of the latest version
- include sostat-redacted output when relevant
- provide information about your system and how you installed Security Onion

**Comment by dougburks** [comment]
Hi @Vaishag ,

Questions like this should be sent to our mailing list:
https://securityonion.net/docs/mailing-lists

Thanks!
