### ISSUE TITLE
Not authorized to perform this operation: server returned 401

### ISSUE THREAD

**Issue by nauliajati** [Security-Onion-Solutions/security-onion#1526]
Hi all, i have this issue when i'm trying to update script using "soup" command 

Checking Security Onion Docker image status... 
you are not authorized to perform this operation: server returned 401. 
Error checking for so-curator update. 
you are not authorized to perform this operation: server returned 401. 
Error checking for so-domainstats update. 
you are not authorized to perform this operation: server returned 401. 
Error checking for so-elastalert update. 
you are not authorized to perform this operation: server returned 401. 
Error checking for so-elasticsearch update. 
you are not authorized to perform this operation: server returned 401. 
Error checking for so-freqserver update. 
you are not authorized to perform this operation: server returned 401. 
Error checking for so-kibana update. 
you are not authorized to perform this operation: server returned 401. 
Error checking for so-logstash update. 

i used security onion version 16.04.6.1, and i install it on proxmox machine, kibana, squert, and cyberchef is running well.. 
can u guys help me please, Thank you.

**Comment by dougburks** [comment]
Hi @nauliajati ,

It looks like you've already sent this question to the Google Group:
https://groups.google.com/d/topic/security-onion/l4HSo5oM_Jo/discussion

The Google Group is the correct location to discuss questions like these, so I'm closing this issue.

Thanks!
