### ISSUE TITLE
APIKEY - Hang on sostat (Onion v.14.04.5.4)

### ISSUE THREAD

**Issue by Ionut-R** [Security-Onion-Solutions/security-onion#1534]
This procedure is used when you have issues with pairing a sensor to the master. 

THIS IS OFFERED AS IS, WITH NO WARRANTY OR LIABILITY.

On principle, a sensor does not need to be re-installed, it can be swapped across masters without issues.

This scenario applied when we paired the sensor with the master successfully and had the following facts:

It was manageable using salt. Showed in  /opt/onionsalt/salt/top.sls 
It registered in mysql ( run:  sudo mysql --defaults-file=/etc/mysql/debian.cnf -Dsecurityonion_db -e 'select * from sensor')
It didn`t show in /etc/elsa_web.conf
It didn`t show packets in Elsa or showed as a node in the web portal
This was corrected by editing the securityonion_ssh.conf file and adding the next available port number, adding then the entry on the master server (make a backup prior), and then running the register function on the sensor to complete the set-up.

Stop nsm service + apache2 on sensor  + master
sudo service nsm stop
sudo service apache2 stop
On the sensor, run sudo cat /root/.ssh/securityonion_ssh.conf
Add the Elsa port ( should be missing )
![image](https://user-images.githubusercontent.com/51706935/59279897-68422500-8c6d-11e9-9ae8-686343ba2eb5.png)

On the  master, run  sudo vi /etc/elsa_web.conf

Add manual entry for sensor , with port mentioned in sensor and api key random hex (  match length )
![image](https://user-images.githubusercontent.com/51706935/59279978-860f8a00-8c6d-11e9-80a7-fa49568a39a5.png)

Go back to the sensor and run the update api key script
Sudo /usr/bin/securityonion_elsa_register.rb --update-apikey $ELSA_APIKEY
Ex: Sudo /usr/bin/securityonion_elsa_register.rb --update-apikey "111hexapikeyfromabove goeshere)"
Reboot sensor + master
Use sudo so-stat on sensor and master to verify is the APIKEY hang goes away on the sensor and if the tunnel shows on the master.

If everything goes well, you will see a SSH tunnel on the master

 Verify the node in Elsa

**Comment by dougburks** [comment]
Hi @Ionut-R ,

Security Onion 14.04 and ELSA are past End Of Life:
https://securityonion.net/docs/eol

We recommend upgrading to Security Onion 16.04 as soon as possible.

Thanks!
