### ISSUE TITLE
rule-update ossec backup local rules issue

### ISSUE THREAD

**Issue by jason-green-io** [Security-Onion-Solutions/security-onion#1572]
When `LOCAL_HIDS_RULE_TUNING=no` and rule-update runs at least once,
ossec/yazzuh will fail to load if duplicate rules are found in both `local_rules.xml` and `local_rules_orig.xml`.

I think ossec/yazzuh loads all the `.xml` files in the rules folder.

https://github.com/Security-Onion-Solutions/securityonion-rule-update/blob/5b21903a5c9bce7290378e678eea4b785ed435ba/usr/bin/rule-update#L260

**Comment by dougburks** [comment]
Thanks @jason-green-io!

I think we'll change this to move this file into `/var/ossec/rules/backup`.

**Comment by dougburks** [comment]
Upon closer inspection, it looks like the script is already backing up to /var/ossec/rules/backup/ near the beginning of the script:
https://github.com/Security-Onion-Solutions/securityonion-rule-update/blob/master/usr/bin/rule-update#L73-L82

so I think the later copy in line 260 is no longer needed and can be removed altogether.

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/iqsKkvdh4iM/discussion

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/07/securityonion-rule-update-20151201.html
