### ISSUE TITLE
securityonion-squert: increase group_concat_max_len

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1602]
Increase `group_concat_max_len` in securityonion-squert.cnf to `1000000`.

**Comment by dougburks** [comment]
`select GROUP_CONCAT(event.status)` outputs comma-separated statuses so each status actually has a `length` of `2`.  Therefore `group_concat_max_len` needs to be twice as big as the highest number of uncategorized events we want to support.  This means at `1000000`, we can support up to 500K uncategorized events.  We have a daily cron job that should purge down to 100K uncategorized events, but that number could continue to grow through the day if not acted on by analyst(s).  500K is probably a decent ceiling without having to go with a crazy high `group_concat_max_len`.

**Comment by dougburks** [comment]
`securityonion-squert - 20161212-1ubuntu1securityonion43` is now available at `ppa:securityonion/test`.

Please test/verify as follows:

- create a VM using the latest 16.04.6.1 ISO image

- run through Setup choosing Evaluation Mode

- Decrease OSSEC_AGENT_LEVEL to 2:
`sudo sed -i 's|OSSEC_AGENT_LEVEL=5|OSSEC_AGENT_LEVEL=2|g' /etc/nsm/securityonion.conf`

- Restart ossec-agent:
`sudo so-ossec-agent-restart`

- generate 60,000 `fatal` alerts:
`for i in $(seq 1 60000); do logger fatal; done`

- log into Sguil console and verify that Sguil shows CNT as greater than 50001

- log into Squert and verify that QUEUE shows only 50001

- snapshot the VM if possible

- add the test PPA:
`sudo add-apt-repository -y ppa:securityonion/test`

- install all updates:
`sudo soup`

- reboot:
`sudo reboot`

- log into Squert and verify the QUEUE counts are now correct

- anything else we missed?

Thanks in advance for your time and effort!

**Comment by weslambert** [comment]
Looks good from my testing 👍

**Comment by dougburks** [comment]
Thanks @weslambert !

Published:
https://blog.securityonion.net/2019/08/securityonion-squert-20161212.html
