### ISSUE TITLE
sostat: don't show pf_ring output if af_packet in use

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1623]

**Comment by dougburks** [comment]
The following package is now available at `ppa:securityonion/test`:
```
securityonion-sostat - 20120722-0ubuntu0securityonion143
```
Please test as follows:

- install the latest ISO image in a VM

- add the test PPA:
```
sudo add-apt-repository -y ppa:securityonion/test
```
- install updates:
```
sudo soup
```
- run `sostat` and verify that it include the pf_ring section when running pf_ring but does not include the pf_ring section when running af_packet
```
sudo sostat
```
- verify no regressions

- anything else we missed?

Thanks in advance for your time and effort!

**Comment by weslambert** [comment]
Confirmed working as expected.  👍

**Comment by dougburks** [comment]
Thanks @weslambert !

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/04/securityonion-sostat-20120722.html
