### ISSUE TITLE
SR-IOV interface goes down when testing network performance

### ISSUE THREAD

**Issue by ykhanal123** [Security-Onion-Solutions/security-onion#1625]
Hello,
We are testing network performance on KVm with SR-IOV and found that the interface goes down after a certain amount of time in SecurityOnion 16.0.4.

I've attached a link to the bug posted on Ubuntu launchpad for your convenience.

https://bugs.launchpad.net/ubuntu/+bug/1841669

Any help would be appreciated.

Thanks

**Comment by dougburks** [comment]
Closing this issue.

If you have further questions or problems, please use our mailing list:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html

Thanks!
