### ISSUE TITLE
NSM: nsm_server_user-add should require usernames to be alphanumeric

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1627]
Use logic similar to what's already in `sosetup`:

```
        while [ $USERNAME_CONFIRMED = "no" ]; do
                TEXT="Let's create our first user account.\n\nThis account will be used when logging into Kibana, Squert, and Sguil.\n\nWhat would you like the username to be?\n\nPlease use alphanumeric characters only.\n\nYou can create other usernames later using so-user-add."
                SGUIL_CLIENT_USERNAME=$(promptinput "$TEXT")
                [ $? = 1 ] && exit 1
                COMPRESSED="$(echo $SGUIL_CLIENT_USERNAME | sed -e 's/[^[:alnum:]]//g')"
                if [ "$COMPRESSED" != "$SGUIL_CLIENT_USERNAME" ] || [ x$SGUIL_CLIENT_USERNAME = "x" ] ; then
                        prompterror "Invalid username!\n\nPlease use alphanumeric characters only."
                else
                        USERNAME_CONFIRMED="yes"
                        [ $DEBUG -eq 1 ] && echo "DEBUG: Sguil username set."
                fi
        done
```

**Comment by dougburks** [comment]
`securityonion-nsmnow-admin-scripts - 20120724-0ubuntu0securityonion205` is now copying to `ppa:securityonion/test` and should be available for testing within an hour or so.

Please test and verify as follows:

- Install the latest ISO image.  

- Run Setup and choose Evaluation Mode.

- Add the test PPA:
```
sudo add-apt-repository -y ppa:securityonion/test
```
- Install updates:
```
sudo soup
```
- Test nsm_server_user-add:
```
sudo nsm_server_user-add
```
- Entering an empty username should result in an error.

- Entering a non-alphanumeric username should result in an error.

- Entering an alphanumeric username should allow you to create a user.

- `so-user-add` should behave the same way since it just calls `nsm_server_user-add`

- Verify no regressions.

- Anything else we missed?

Thanks in advance for your time and effort!

**Comment by weslambert** [comment]
Looks good from my testing! 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/09/securityonion-nsmnow-admin-scripts.html
