### ISSUE TITLE
securityonion-docker: so-elastalert - update to Python 3

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1629]

**Comment by weslambert** [comment]
Still waiting on Beta branch to be merged to master.  Will update when that occurs.

https://github.com/Yelp/elastalert

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion-docker/pull/7

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion-docker/pull/10

**Comment by defensivedepth** [comment]
Looks good to me

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/11/elastic-684-now-available-for-security.html
