### ISSUE TITLE
securityonion-sostat: update Elastic verbiage for when components are not running

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1633]
Example:

Kibana is not running.

Try starting it with:

`sudo so-elastic-start`
 OR
**sudo docker start so-kibana**

......

should be updated to `sudo so-kibana-start`.

**Comment by dougburks** [comment]
Please test/verify as follows:

- create a VM using the new 16.04.6.2 ISO

- run Setup and choose Evaluation Mode

- snapshot the VM

- add the test PPA:
```
sudo add-apt-repository -y ppa:securityonion/test
```
- install updates:
```
sudo soup
```
- stop all Elastic services:
```
sudo so-elastic-stop
```
- run sostat and verify the new verbiage at the end of the output
```
sudo sostat
```
- verify no regressions

- anything else we missed?

Thanks in advance for your time and effort!

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/10/securityonion-sostat-20120722.html
