### ISSUE TITLE
NSM: Error when running nsm_sensor with --start and --sensor-name

### ISSUE THREAD

**Issue by petiepooo** [Security-Onion-Solutions/security-onion#1637]
I can stop just the sensor apps (netsniff-ng through barnyard2) using any of these commands:

> nsm --sensor --stop --sensor-name=myhost-eno2
> nsm_sensor --stop --sensor-name=myhost-eno2
> nsm_sensor_ps-stop --sensor-name=myhost-eno2

These commands leave the sguild server, bro, and elastic apps running, which is what I expected to happen.

When I use the equivalent command to start them:

> nsm --sensor --start --sensor-name=myhost-eno2
> nsm_sensor --start --sensor-name=myhost-eno2

the right range of apps are started as expected, but there's another call to some script that gives the following error:

> OOPS: Unknown option "--sensor-name=myhost-eno2" found!
> 
> The NSMnow Administration scripts are designed to easily configure and manage
> your NSM installation. Bugs, comments and flames can be directed to the
> SXL team at dev@securixlive.com
> 
> The NSMnow Administration scripts come with ABSOLUTELY NO WARRANTY.
> 
> Usage: /usr/sbin/nsm_sensor [options]
> .......

Interestingly, this command works without the error:

> sudo nsm_sensor_ps-start --sensor-name=myhost-eno2

**Comment by dougburks** [comment]
Hi @petiepooo ,

Can you try out https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/commit/5309f5af222e399b3a46c5d4862e88dd957ef8ac and see if that resolves the issue for you?

**Comment by weslambert** [comment]
Looks good from my testing 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/10/securityonion-nsmnow-admin-scripts.html
