### ISSUE TITLE
securityonion-elastic: reconcile additional geo fields in ingest node

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1640]
Ingest node geoip includes `continent_name` and `country_iso_code`.  These fields are not defined in our Elasticsearch template, so we should remove the extra fields from the ingest node parser config.

**Comment by weslambert** [comment]
Looks good 👍 .

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/11/elastic-684-now-available-for-security.html
