### ISSUE TITLE
Monitoring AWS cloudtrail using security onion

### ISSUE THREAD

**Issue by Parthasarathi7722** [Security-Onion-Solutions/security-onion#1641]
Hi, 

I would like to know if there is possibility's to monitor cloudtrail using security onion. Tried finding in web however no luck.

**Comment by dougburks** [comment]
Hi @Parthasarathi7722 ,

Questions like these should go to the mailing list:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html

Thanks!
