### ISSUE TITLE
so-import-pcap: only decrease ES heap if less than 9GB  RAM

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1642]

**Comment by dougburks** [comment]
https://groups.google.com/d/topic/security-onion/D0wVB49QWoI/discussion

**Comment by weslambert** [comment]
Looks like this is set to look for less than 9GB?

We may need to s/`9000`/`8000` for `TOTAL_MEM`.

Ref: https://github.com/Security-Onion-Solutions/securityonion-elastic/commit/556946533240042f967f8e55992bda3ae6aa4139#diff-44df288646dd8caeedfa1e99760337b1R307

**Comment by dougburks** [comment]
Good catch!  I decided while working on this that we need to keep the lower heap size if RAM is 8GB, so I changed the threshold to 9GB.  I've updated the title of this issue to reflect that.

**Comment by weslambert** [comment]
In that case, it is working as intended 👍 .

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/11/elastic-684-now-available-for-security.html
