### ISSUE TITLE
Squert: improve consistency of username handling

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1643]

**Comment by dougburks** [comment]
Please test/verify as follows:

- create a VM using the new 16.04.6.2 ISO

- run `so-import-pcap` just to get a quick setup going:
```
sudo so-import-pcap /opt/samples/markofu/outbound.pcap
```

- verify that Squert is case-sensitive for username but Kibana, CapMe, and Sguil are not

- snapshot the VM

- add the test PPA:
```
sudo add-apt-repository -y ppa:securityonion/test
```

- install updates:
```
sudo soup
```

- verify that Squert now matches username same as Kibana, CapMe, and Sguil

- verify no regressions

- anything else we missed?

Thanks in advance for your time and effort!

**Comment by weslambert** [comment]
Confirmed username works across all apps with both upper and lowercase.

Thanks,
Wes

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/09/securityonion-squert-20161212.html
