### ISSUE TITLE
securityonion-sostat: block docker 19.03.3 packages

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1652]
https://blog.securityonion.net/2019/10/docker-package-issues-please-do-not.html

**Comment by dougburks** [comment]
Docker 19.03.3 had a regression for the `DOCKER-USER` iptables chain:
https://github.com/docker/for-linux/issues/810

This new `securityonion-sostat` package creates `/etc/apt/preferences.d/securityonion-docker-block` with the following:
```
Package: docker-ce
Pin: version 5:19.03.3~3-0~ubuntu-xenial
Pin-Priority: -1

Package: docker-ce-cli
Pin: version 5:19.03.3~3-0~ubuntu-xenial
Pin-Priority: -1
```
It then has a `postinst` script that does this:
```
# Emergency check for docker issue
if dpkg -l |grep docker |grep -q "5:19.03.3~3-0~ubuntu-xenial"; then
        echo
        echo "Docker 19.03.3 detected! This version has issues:"
        echo "https://blog.securityonion.net/2019/10/docker-package-issues-please-do-not.html"
        echo
        echo "We've blocked this version in /etc/apt/preferences.d/securityonion-docker-block."
        echo
        echo "We recommend removing the docker-ce and docker-ce-cli packages and re-installing:"
        echo "sudo apt purge docker-ce docker-ce-cli && sudo apt install docker-ce docker-ce-cli"
fi
```
`soup` also contains the same exact code snippet.

So when you install the updated securityonion-sostat, it will immediately notify you if you have Docker 19.03.3 and future runs of `soup` are prevented from installing that Docker version.

It should be noted that if a user runs `soup` today to get the new `securityonion-sostat`, then they're running the old version of `soup` before the block is placed, so they will get Docker 19.03.3 (at least until 19.03.4 is released), but `postinst` should still detect this and output the message above.

**Comment by weslambert** [comment]
Looks good from my testing. 👍

**Comment by dlee35** [comment]
Tested on vanilla Ubuntu 16.04.6 Server installation.

Post installation (pre testing):
![image](https://user-images.githubusercontent.com/7849311/66921662-a8d2f600-eff3-11e9-914f-84b98793be55.png)

After adding test repo and running `sudo soup -y`:
![image](https://user-images.githubusercontent.com/7849311/66921622-9a84da00-eff3-11e9-8f39-f07ab146ff4e.png)

After running `sudo apt purge -y docker-ce docker-ce-cli && sudo apt install -y docker-ce docker-ce-cli`:
![image](https://user-images.githubusercontent.com/7849311/66921712-bf794d00-eff3-11e9-9923-4996ea66a423.png)

IPTables output for DOCKER-USER chain post update:
![image](https://user-images.githubusercontent.com/7849311/66921748-ce5fff80-eff3-11e9-9572-9661ec92f944.png)

IPTables output for DOCKER-USER chain after adding Beats endpoint:
![image](https://user-images.githubusercontent.com/7849311/66921795-de77df00-eff3-11e9-9713-c41944be0482.png)

**Comment by dougburks** [comment]
Thanks @weslambert and @dlee35 !

Published:
https://blog.securityonion.net/2019/10/securityonion-sostat-20120722.html
