### ISSUE TITLE
NSM: replace pcap ls with find

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1654]
https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/pull/27

**Comment by dougburks** [comment]
`securityonion-nsmnow-admin-scripts - 20120724-0ubuntu0securityonion208` is now ready for testing!

Please test/verify as follows:

- start with a current ISO installation

- run through Setup, choosing Evaluation Mode

- snapshot the VM if possible

- add the test PPA:
```
sudo add-apt-repository -y ppa:securityonion/test
```
- install all updates:
```
sudo soup -y
```
- replay some traffic:
```
for i in `seq 1 10`; do sudo so-test; done
```
- determine current disk usage:
```
df -h
```
- watch log file:
```
tail -f /var/log/nsm/sensor_clean.log
```
- edit `/etc/nsm/securityonion.conf` and set `CRIT_DISK_USAGE` to just under your current disk usage

- wait for next run of cron job and watch log file to ensure it's deleting properly

- anything else we missed?

Thanks in advance for your time and effort!

**Comment by weslambert** [comment]
Looks good from my testing 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/10/securityonion-nsmnow-admin-scripts.html
