### ISSUE TITLE
securityonion-elastic: so-kibana-start needs to wait on .kibana shard

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1655]
For existing installations, `so-kibana-start` needs to do the following after Elasticsearch starts listening but before we try to start Kibana:
```
curl ${ELASTICSEARCH_AUTH} --output /dev/null --silent http://"$ELASTICSEARCH_HOST":"$ELASTICSEARCH_PORT"/_cluster/health/.kibana?wait_for_status=green'&'timeout=240s
```

**Comment by weslambert** [comment]
Looks good 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/11/elastic-684-now-available-for-security.html
