### ISSUE TITLE
Extended Zeek ICS Protocol Support

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1658]
Consider support for additional Zeek parsers, LS config, and default hunting dashboards in Kibana.

https://github.com/amzn/zeek-plugin-tds
https://github.com/amzn/zeek-plugin-s7comm
https://github.com/amzn/zeek-plugin-profinet
https://github.com/amzn/zeek-plugin-bacnet
https://github.com/amzn/zeek-plugin-enip

**Comment by KSJakobsen** [comment]
Second that.... Would be awesome for our installation of SO
