### ISSUE TITLE
Setup: remind user to keep LOG_SIZE_LIMIT under 90%

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1659]
Per discussion here:
https://github.com/Security-Onion-Solutions/securityonion-elastic/pull/70

**Comment by dougburks** [comment]
The following package is now available at ppa:securityonion/test:
```
securityonion-setup - 20120912-0ubuntu0securityonion316
```

Please test as follows:

- install the latest ISO image in a VM

- add the test PPA:
```
sudo add-apt-repository -y ppa:securityonion/test
```

- install updates:
```
sudo soup
```

- run Setup and verify that the LOG_SIZE_LIMIT screen keeps the value under 90% of disk space

- verify no regressions

- anything else we missed?

Thanks in advance for your time and effort!

**Comment by weslambert** [comment]
Looks good 👍 .

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/11/securityonion-setup-20120912.html
