### ISSUE TITLE
securityonion-sostat: check for syslog-ng drops

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1660]
https://groups.google.com/d/topic/security-onion/G-phEjqoiuU/discussion

sostat should check for syslog-ng drops via `syslog-ng-ctl stats`

**Comment by weslambert** [comment]
Looks good from my testing 👍

**Comment by dougburks** [comment]
Thanks @weslambert !

Published:
https://blog.securityonion.net/2019/11/securityonion-sostat-20120722.html
