### ISSUE TITLE
securityonion-setup: include SOSTATADDRESS in so-email.conf

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1665]
`SOSTATADDRESS` needs to be in so-email.conf so that when folks run so-email via CLI, sostat email works properly.

**Comment by dougburks** [comment]
The following package is now available at ppa:securityonion/test:
```
securityonion-setup - 20120912-0ubuntu0securityonion316
```

Please test as follows:

- install the latest ISO image in a VM

- add the test PPA:
```
sudo add-apt-repository -y ppa:securityonion/test
```

- install updates:
```
sudo soup
```

- create a copy of `/usr/share/securityonion/so-email.conf` and edit as appropriate 

- run `so-email` with `/usr/share/securityonion/so-email.conf` and verify `SOSTATADDRESS` is set properly in resulting cron job

- verify no regressions

- anything else we missed?

Thanks in advance for your time and effort!

**Comment by weslambert** [comment]
Looks good 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/11/securityonion-setup-20120912.html
