### ISSUE TITLE
securityonion-elastic: update dns domain info for elasticsearch ingest

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1667]

**Comment by dougburks** [comment]
Full logstash config includes fields like:
highest_registered_domain
subdomain_length
tld.subdomain
subdomain
top_level_domain
parent_domain_length

These are related to logstash `tld` filter plugin:
https://www.elastic.co/guide/en/logstash/current/plugins-filters-tld.html

There may not be a readily available equivalent processor for elasticsearch ingest.

**Comment by dougburks** [comment]
Jim shared a `painless` script to get the domain info missing in the bro_dns pipeline into ES:
```
{ "script" :
    {   
        "lang": "painless",
        "source": """
            def dparts = /\\./.split(ctx.query);
            if (dparts.length > 1) {
                def dps = new ArrayList();
                for (int i = 0; i < dparts.length; i++) {
                    dps.add(dparts[i])
                }
                def domain; def trd; def tld; def sld;
                int le = dparts.length - 1 ;
                for (int i = le; i >= 0; i--) {
                    if (i == le) {
                        tld = dps.remove(i)
                    } else if (i == le - 1) {
                        sld = dps.remove(i)
                    }
                }
                ctx.top_level_domain = tld;
                ctx.parent_domain = sld;
                ctx.highest_registered_domain = sld + '.' + tld;
                if (dps.size() > 0) {
                    ctx.subdomain = String.join('.', dps)
                }
            }
        """,
        "if"  : "ctx.query_type_name != 'NB' && ctx.query_type_name != 'TKEY' && ctx.query_type_name != 'NBSTAT' && ctx.query_type_name != 'PTR'",
        "on_failure" : [
            {   
                "set" : { "field" : "error", "value" : "{{ _ingest.on_failure_message }}" }
            }
        ]
    }
}
```

and Jim said:
>This could probably be done better, but it seems to work, finally
Some notes:
The triple quotes don't work with curl
oops
If you assign a value to an already defined 'dotted' value (like tld which has tld.subdomain), you'll get no error in either the ES logs, or in the event itself as the event is just dropped

**Comment by dougburks** [comment]
Note from Jim:
```
BTW, that painless script for bro_dns also works well for bro_http/virtual_host
```

**Comment by jimhranicky** [comment]
When used with the bro_http/virtual_host, the "if" field should be changed
to something like this: 

    "if": "!(ctx.virtual_host =~ /^\\d+\\.\\d+\\.\\d+\\.\\d+$/)",

**Comment by jimhranicky** [comment]
Well, that causes problems: 

    "if": "ctx.virtual_host != null && !(ctx.virtual_host =~ /^\\d+\\.\\d+\\.\\d+\\.\\d+$/)",

**Comment by dougburks** [comment]
Hi @jimhranicky ,

I discovered that a combination of lastIndexOf and substring made this a little easier to work into our existing ingest parser format.  Please take a look at https://github.com/Security-Onion-Solutions/securityonion-elastic/commit/13f7527a04905a32642962827bb2b76d6373359b and let me know what you think.

Thanks!

**Comment by defensivedepth** [comment]
Looks like these are parsing out just fine from what I can see.

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/02/zeek-301-elastic-686-and-cyberchef-9120.html
