### ISSUE TITLE
securityonion-elastic: Bro HTTP Logs "user" field not mapped in Elasticsearch template 

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1672]
Need to map this field in the template or change the field to be `username` in the 1106 config.

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion-elastic/commit/6f2384f223b32d39721f8fec84dcfda74e44425b

**Comment by weslambert** [comment]
Looks good 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/02/zeek-301-elastic-686-and-cyberchef-9120.html
