### ISSUE TITLE
securityonion-sostat: improve netsniff packet loss calculation

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1673]

**Comment by dougburks** [comment]
The following package is now available at `ppa:securityonion/test`:
```
securityonion-sostat - 20120722-0ubuntu0securityonion137
```
Please test as follows:

- install the latest ISO image in a VM

- add the test PPA:
```
sudo add-apt-repository -y ppa:securityonion/test
```
- install updates:
```
sudo soup
```
- run `sostat` and verify that it can more quickly calculate netsniff packet loss on systems with and without packet loss:
```
sudo sostat
```
- verify no regressions

- anything else we missed?

Thanks in advance for your time and effort!

**Comment by weslambert** [comment]
Looks good from my testing, and much quicker than the previous! 👍

**Comment by dougburks** [comment]
Thanks @weslambert !

Published:
https://blog.securityonion.net/2019/12/securityonion-sostat-20120722.html
