### ISSUE TITLE
securityonion-elastic: migrate script.* settings from elasticsearch.yml.bak to elasticsearch.yml

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1676]
Jim Hranicky asked about retaining the following setting in `/etc/elasticsearch/elasticsearch.yml` when updating via `soup`:
```
script.painless.regex.enabled: true
```

We currently migrate other common settings from `elasticsearch.yml.bak` to `elasticsearch.yml` here:
https://github.com/Security-Onion-Solutions/securityonion-elastic/blob/master/usr/sbin/so-elastic-configure-stack#L73-L98

So we should be able to do something similar for `script.*`:
```
grep "^script.*:" $ES_YAML_BAK >> $ES_YAML
```

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion-elastic/commit/6f2384f223b32d39721f8fec84dcfda74e44425b

**Comment by weslambert** [comment]
Confirmed setting gets migrated from backed up file to new file. 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/02/zeek-301-elastic-686-and-cyberchef-9120.html
