### ISSUE TITLE
ISO DOWNLOAD FAILURE

### ISSUE THREAD

**Issue by ndekere254** [Security-Onion-Solutions/security-onion#1678]
I dont know where you've hosted the ISO. It's just taking forever to download!!/Fails to download at all.

**Comment by dougburks** [comment]
Hi @ndekere254 ,

I just tested and was able to download the ISO image in under 2 minutes.

To confirm, what is the exact URL you are downloading from?

Where are you located?

Have you tried downloading from a different network?

**Comment by dougburks** [comment]
Closing due to lack of response.  

If you have further questions or problems, please use our mailing list:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html

Thanks!
