### ISSUE TITLE
Setup: change Bro references to Zeek

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1681]

**Comment by defensivedepth** [comment]
`sosetup` via cli -  


![image](https://user-images.githubusercontent.com/954732/72091525-5cd7da80-32de-11ea-86ab-174f77317777.png)

**Comment by defensivedepth** [comment]
Looks good!

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/02/zeek-301-elastic-686-and-cyberchef-9120.html
