### ISSUE TITLE
securityonion-elastic: container status scripts should check system uptime before declaring fail

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1686]
If a user runs `so-status` right after the system boots, all Elastic containers are marked `FAIL`.  This may be misleading and may cause the user to try to manually start the containers.  

Update the status scripts so that if the container is not yet running, then check the system uptime.  If it has recently booted, then show container status as `WARN`.

**Comment by defensivedepth** [comment]
Looks good!

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/02/zeek-301-elastic-686-and-cyberchef-9120.html
