### ISSUE TITLE
securityonion-sostat: migrate from Bro to Zeek

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1692]

**Comment by weslambert** [comment]
Confirmed `sostat` contains no instance of `[Bb]ro` other than the following lines that are cleaned up from the `zeekctl` response:

 `su sguil -c '/opt/zeek/bin/zeekctl netstats 2>&1 | grep -v "Warning: ZeekControl plugin uses legacy BroControl API. Use" | grep -v "import BroControl.plugin" | grep -v "^$" ' > $TMP`

Looks good 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/02/zeek-301-elastic-686-and-cyberchef-9120.html
