### ISSUE TITLE
securityonion-elastic: improve postinst update check

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1699]
Some folks have reported forward nodes running Elastic services after running soup:
https://groups.google.com/d/topic/security-onion/jk0f0mTRjxc/discussion

Still not sure exactly what the root cause is, but we're going to add some more checking to try to prevent this in the future.

**Comment by weslambert** [comment]
Looks good 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/02/zeek-301-elastic-686-and-cyberchef-9120.html
