### ISSUE TITLE
Elastalert - Update new_term.yaml

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1706]
INFO:elastalert:Queried rule Security Onion Elastalert - New Term Alert from 2020-01-14 12:49 UTC to 2020-01-14 12:50 UTC: 0 hits
ERROR:root:Traceback (most recent call last):
  File "/opt/elastalert/elastalert/elastalert.py", line 1270, in handle_rule_execution
    num_matches = self.run_rule(rule, endtime, rule.get('initial_starttime'))
  File "/opt/elastalert/elastalert/elastalert.py", line 905, in run_rule
    if not self.run_query(rule, rule['starttime'], endtime):
  File "/opt/elastalert/elastalert/elastalert.py", line 645, in run_query
    rule_inst.add_count_data(data)
  File "/opt/elastalert/elastalert/ruletypes.py", line 84, in add_count_data
    raise NotImplementedError()
NotImplementedError

**Comment by weslambert** [comment]
It seems that we need to remark/remove `use_count_query`

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion-elastic/pull/72

**Comment by dougburks** [comment]
This is included in `securityonion-elastic - 20190510-1ubuntu1securityonion83` which is now available for testing at ppa:securityonion/test.

**Comment by weslambert** [comment]
Looks good 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/02/zeek-301-elastic-686-and-cyberchef-9120.html
