### ISSUE TITLE
NSM: increase timeout in /etc/systemd/system/securityonion.service

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1708]
https://github.com/Security-Onion-Solutions/security-onion/issues/1695#issuecomment-574401343

**Comment by dougburks** [comment]
`securityonion-nsmnow-admin-scripts - 20120724-0ubuntu0securityonion224` is now available for testing at `ppa:securityonion/test`.

**Comment by weslambert** [comment]
Looks good 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/02/zeek-301-elastic-686-and-cyberchef-9120.html
