### ISSUE TITLE
securityonion-bro-scripts: improve postinst to avoid errors when reinstalling

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1711]
The postinst script was producing errors when reinstalling via:
```
sudo apt install --reinstall securityonion-bro-scripts
```

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion-bro-scripts/commit/ee8fbc0f23857018ccdcdcb410299c6936f8480e

**Comment by dougburks** [comment]
To test this, install the new package, verify no errors, then reinstall the package via:
```
sudo apt install --reinstall securityonion-bro-scripts
```
It should reinstall cleanly with no errors.

**Comment by weslambert** [comment]
No errors when re-installing. 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/02/zeek-301-elastic-686-and-cyberchef-9120.html
