### ISSUE TITLE
NSM: broctl and zeekctl need to check if parameters were passed

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1713]
`/usr/sbin/broctl` and `/usr/sbin/zeekctl` are user convenience shims that call the real `/opt/bro/bin/zeekctl`.  We recently added some greps to these shims to clean up some of the unnecessary warnings.  However, grep is preventing the user from running the zeekctl shell interactively.  The easiest fix is to check for parameters and only pipe into grep if parameters were passed.

**Comment by dougburks** [comment]
After installing `securityonion-nsmnow-admin-scripts - 20120724-0ubuntu0securityonion225`, please test as follows:

- verify that `sudo broctl` and `sudo zeekctl` both start the `zeekctl` shell and you're able to interact with it

- verify that you can pass parameters like `sudo zeekctl status` and get just the status information without any unnecessary warnings

**Comment by defensivedepth** [comment]
Looks good to me!

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/02/zeek-301-elastic-686-and-cyberchef-9120.html
