### ISSUE TITLE
Unable to get past installation step

### ISSUE THREAD

**Issue by mandraid** [Security-Onion-Solutions/security-onion#1716]
I am trying to install SO in AWS, with a EC2 instance running a single network interface.  I am doing the trial mode rather than the production mode.  This is where I am getting stuck at:
![image](https://user-images.githubusercontent.com/59519373/74109053-18926100-4b4e-11ea-96a6-53c3415d1389.png)

**Comment by dougburks** [comment]
Hi @mandraid ,

Here are a few things you can try:

- check the sosetup log file in /tmp or /var/log/nsm/ for additional clues
- use multiple network interfaces if possible
- try production mode
- install Security Onion in a local VM and compare it to your EC2 instance

If you have further questions or problems, please send a detailed message to our mailing list:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html

Thanks!
