### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by austinsonger** [Security-Onion-Solutions/security-onion#1722]
Is there going to be a Ubuntu 18.04 version released?

**Comment by dougburks** [comment]
Hi @austinsonger ,

Yes, we plan to add support for Ubuntu 18.04 to Security Onion Hybrid Hunter.

You can read more about Hybrid Hunter here:
https://blog.securityonion.net/2020/02/security-onion-hybrid-hunter-114-alpha.html

If you have further questions or problems about our traditional Security Onion platform, please use our mailing list:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html

If you have further questions or problems about our new Hybrid Hunter platform, please use reddit:
https://www.reddit.com/r/securityonion/

Thanks!
