### ISSUE TITLE
sosetup-minimal: remove old check for securityonion_ssh.conf

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1731]
sosetup-minimal was based on so-import-pcap and still includes an old check from there for securityonion_ssh.conf.

**Comment by dougburks** [comment]
To test, build a master server and storage node using the current ISO (no updates installed) and then try to re-run sosetup-minimal on the storage node and it should exit with the following error:
```
This machine appears to be a sensor connected to a distributed deployment.
This script was designed for standalone systems designated for so-import-pcap.
```
Install the new `securityonion-setup` package, re-run sosetup-minimal and it should no longer exit but instead allow you to proceed.

**Comment by bryant-treacle** [comment]
No issues with my testing!

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/03/security-onion-160465-iso-image-now.html
