### ISSUE TITLE
Suricata 5.0.1 in IPS mode

### ISSUE THREAD

**Issue by LazaroCruz** [Security-Onion-Solutions/security-onion#1734]
I have Suricata 5.0.1 on Ubuntu 18.04 and I need to enable IPS mode. I have looked for information about this and I have tried it in different ways but it does not work for me. Could someone help me with this. Thank you !!!

**Comment by dougburks** [comment]
Hi @LazaroCruz ,

I'm not sure I understand.  

Security Onion does not support IPS:
https://securityonion.readthedocs.io/en/latest/nids.html#nips

Furthermore, it sounds like you're not using Security Onion at all.  Instead, it sounds like you've manually installed Suricata on your own installation of Ubuntu 18.04.  If you need help with your own installation of Suricata, then you should probably reach out to the Suricata community:
https://suricata-ids.org/support/

Hope that helps!

**Comment by LazaroCruz** [comment]
Thanks you !!!
