### ISSUE TITLE
securityonion-elastic: so-elastic-reset needs to disable elastalert and then re-enable afterward

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1735]
https://github.com/Security-Onion-Solutions/securityonion-elastic/pull/75

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion-elastic/pull/79

**Comment by weslambert** [comment]
Looks good since last PR! 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/04/elastic-688-now-available-for-security.html
