### ISSUE TITLE
so-import-pcap-configure: running alone results in error

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1740]
`so-import-pcap` calls `so-import-pcap-configure` if necessary.  However, if you try to run `so-import-pcap-configure` on its own and then run `so-import-pcap`, it will result in error.

**Comment by weslambert** [comment]
Looks good from my testing! 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/04/elastic-688-now-available-for-security.html
