### ISSUE TITLE
securityonion-elastic: bro_files file_ip should be copied to source_ip

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1742]
We should copy `file_ip` to `source_ip` so that we can build more congruent searches/tables, but retain the existing `file_ip` visualizations and dashboard config.

**Comment by weslambert** [comment]
````
mutate {
         copy => { "file_ip" => "source_ip" }
}
````

**Comment by dougburks** [comment]
Don't forget about elasticsearch ingest node parsing!

**Comment by weslambert** [comment]
D'oh! Truth.

**Comment by dougburks** [comment]
The ingest parser above resulted in errors.  I had to change to:
```
{
      "set": {
        "field": "source_ip",
        "value": "{{file_ip.0}}"
      }
}

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/04/elastic-688-now-available-for-security.html
