### ISSUE TITLE
Could you add sha256 checksum with each of your release?

### ISSUE THREAD

**Issue by orange888** [Security-Onion-Solutions/security-onion#1745]
6df3b23388c366ca411912da641c4f43ce1fa0ce201819def6aae3a15cabc494  securityonion-16.04.6.5.iso

Thanks.

**Comment by dougburks** [comment]
Hi @orange888 ,

sha256 checksums are already available in checksums.txt:
https://github.com/Security-Onion-Solutions/security-onion/blob/master/checksums.txt

We recommend that folks verify ISO images using our gpg signature as described here:
https://github.com/Security-Onion-Solutions/security-onion/blob/master/Verify_ISO.md

Thanks!
