### ISSUE TITLE
securityonion-setup: change /nsm/bro to /nsm/zeek in a few user facing messages

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1753]

**Comment by dougburks** [comment]
The following package is now available at `ppa:securityonion/test`:
```
securityonion-setup - 20120912-0ubuntu0securityonion328
```
Please test as follows:

- install the latest ISO image in a VM

- add the test PPA:
```
sudo add-apt-repository -y ppa:securityonion/test
```
- install updates:
```
sudo soup
```
- run through Setup and verify that all user facing messages referring to /nsm/bro have been updated to /nsm/zeek

- verify no regressions

- anything else we missed?

Thanks in advance for your time and effort!

**Comment by weslambert** [comment]
Confirmed during my testing 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/04/securityonion-setup-20120912.html
