### ISSUE TITLE
securityonion-elastic: so-elastic-reset does not remove closed indices

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1759]
In this line

https://github.com/Security-Onion-Solutions/securityonion-elastic/blob/master/usr/sbin/so-elastic-reset#L93

we should change the following

`_cat/indices?v | egrep 'logstash|elastalert' | awk '{ print $3 }'`

to

`_cat/indices?h=status,index | egrep 'logstash|elastalert' | awk '{ print $2 }'`

**Comment by weslambert** [comment]
No issues during my testing 👍

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/04/elastic-688-now-available-for-security.html
