### ISSUE TITLE
First boot, stuck at login manager , qemu

### ISSUE THREAD

**Issue by n0a110w** [Security-Onion-Solutions/security-onion#1761]
image: `securityonion-16.04.6.5.iso`
First boot of image and I can't get around the login manager. ttys show login prompt also.
From what i understand, there is no default user/pass.  Is that so? 
![image](https://user-images.githubusercontent.com/51530570/80299695-5de52880-8764-11ea-9c8c-7d7671246825.png)

I'm booting in qemu with virt-manager
Has anyone else encountered this?

**Comment by dougburks** [comment]
Hi @n0a110w ,

Questions and problems like this should go to our mailing list:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html

Thanks!
