### ISSUE TITLE
Error when try DDoS attack

### ISSUE THREAD

**Issue by hoanglongslvp** [Security-Onion-Solutions/security-onion#1766]
when i try ping between 2 PC, it ok. But when i try DDoS attack between that 2 PC, Onion cannot capture the packet. Anybody can help me? Thanks!

**Comment by hoanglongslvp** [comment]
![image](https://user-images.githubusercontent.com/37032813/82009930-d9b6fe80-969a-11ea-84af-c5a4f75946e0.png)

**Comment by dougburks** [comment]
For questions like this, please post a detailed message to our Google Group:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html
