### ISSUE TITLE
Can not verify signature.

### ISSUE THREAD

**Issue by Alex-0293** [Security-Onion-Solutions/security-onion#1768]
I try to verify iso image. Cant import keys in gpg under windows 10
dir
-a----       22.05.2020     14:58           6252 KEYS
gpg --import KEYS

gpg: [don't know]: partial length invalid for packet type 63
gpg: read_block: read error: Недопустимый пакет
gpg: import from 'KEYS' failed: Неверная таблица ключей
gpg: Всего обработано: 0

**Comment by dougburks** [comment]
Please try verifying on a Linux distro using the steps here:
https://github.com/Security-Onion-Solutions/security-onion/blob/master/Verify_ISO.md

If you have further questions or problems, please send a detailed message to our Google Group:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html
