### ISSUE TITLE
Question : What is the amount of traffic monitoring capability of Security Onion ?

### ISSUE THREAD

**Issue by NRGLine4Sec** [Security-Onion-Solutions/security-onion#1769]
What is the amount of traffic monitoring capability of Security Onion ?
Could you add more details about that in the documentation ? And what about hardware requirements for a 10Gb/s link for example ?

For example, elastiflow give the capability of flow monitoring according to hardware resources such as RAM :
https://github.com/robcowart/elastiflow/blob/master/INSTALL.md#requirements

**Comment by dougburks** [comment]
Hi @NRGLine4Sec ,

Please see the Hardware Requirements section of our documentation:
https://securityonion.readthedocs.io/en/latest/hardware.html

If you have further questions or problems, please post a message to our Google Group:
https://securityonion.readthedocs.io/en/latest/mailing-lists.html

Thanks!
