### ISSUE TITLE
Request for file scanning framework integration in Security Onion

### ISSUE THREAD

**Issue by stevewillson** [Security-Onion-Solutions/security-onion#1775]
I request that the file scanning framework FSF (https://github.com/EmersonElectricCo/fsf) be integrated in to Security Onion.

**Comment by weslambert** [comment]
Hi @stevewillson, 

We have actually integrated a file scanning framework called [Strelka](https://github.com/target/strelka) into the upcoming Security Onion 2.0 release: https://github.com/Security-Onion-Solutions/securityonion
