### ISSUE TITLE
Add Wazuh Kibana Plugin

### ISSUE THREAD

**Issue by NRGLine4Sec** [Security-Onion-Solutions/security-onion#1777]
Could you explain how to add Wazuh Plugin to Kibana (https://github.com/wazuh/wazuh-kibana-app) in Security Onion ?
It's not explain in the doc : https://docs.securityonion.net/en/latest/wazuh.html

**Comment by weslambert** [comment]
Hi, we don't currently support this unfortunately, however we may decide to do so in the next version of Security Onion (which does include Wazuh API):

https://github.com/Security-Onion-Solutions/securityonion

**Comment by NRGLine4Sec** [comment]
Ok thank you for the answer
