### ISSUE TITLE
LOGSTASH stuck in WARN won't finish initializing?

### ISSUE THREAD

**Issue by pepperc1** [Security-Onion-Solutions/security-onion#1785]
This is a new install of SO, I've update the distribution as well as "soup", I've restarted logstash numerous times via the so-logstash-restart command but it never completes "initializing".

Any help is appreciated!

-pepper

**Comment by dougburks** [comment]
Hi @pepperc1 ,

Please post a detailed message to our mailing list:
https://docs.securityonion.net/en/16.04/mailing-lists.html

Thanks!
