### ISSUE TITLE
securityonion-elastic: Migrate indices.* settings for elasticsearch.yml

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/security-onion#1786]

**Comment by dougburks** [comment]
Insert the following at line 103 (https://github.com/Security-Onion-Solutions/securityonion-elastic/blob/master/usr/sbin/so-elastic-configure-stack#L103):
```
grep "^indices.*:" $ES_YAML_BAK >> $ES_YAML
```

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/11/elastic-stack-793-now-available-for.html
