### ISSUE TITLE
Salt Stack - salt-master not listening on 4505/4506 

### ISSUE THREAD

**Issue by BustedSec** [Security-Onion-Solutions/security-onion#1791]
I've been trying to troubleshoot this for a while. I have a SO ManagerSearch node up and I'm trying to install a forward node. During the Forward node install it cruds out so I did some digging and it's a communication issue with salt-minion and the ManagerSearch server. I've tried popping the salt-master in debug mode and watching it - I've added an IP tables rule to ensure the traffic get to the box on the right ports, I've conducted tcpdumps on the boxes and I can see the traffic gets from the forward to the managersearch just fine - despite ports 4506 and 4505 being open on the managersearch box I confirmed they are not allowing connections with nc -v -z which times out.  An nmap scan shows the ports as "filtered" I dug into salt and tried a bunch of stuff to fix it but nothing has worked. Any help you can offer would greatly help.

**Comment by dougburks** [comment]
Instead of creating issues in this issue tracker, please post to the community support forum:
https://www.reddit.com/r/securityonion/

Thanks!
