### ISSUE TITLE
securityonion-sostat: update links to documentation

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1794]
Docs now default to Security Onion 2.  16.04 needs to point specifically to the 16.04 version.

**Comment by cm-ops** [comment]
All locations for links verified on Eval, Prod Standalone, and Distributed.

**Comment by dougburks** [comment]
Thanks @cm-ops !

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/11/elastic-stack-793-now-available-for.html
