### ISSUE TITLE
Email configuration issues

### ISSUE THREAD

**Issue by ldceven** [Security-Onion-Solutions/security-onion#1795]
Hello, is there a way for Security Onion to configure email alert notifications (including wazuh/zeek/NIDS)? I tried to configure according to the so-email guide, but did not receive any warning emails. What other configurations need to be done?

Do I need to configure the configuration files of wazuh and zeek separately after running so-email?

I am currently using v16.04.7.1 and I am trying to test with postfix, and the test email is sent successfully.

**Comment by dougburks** [comment]
If you have questions about Security Onion 16.04, please use the 16.04 Google Group (instead of this issue tracker) as described here:
https://docs.securityonion.net/en/16.04/mailing-lists.html

Thanks!
