### ISSUE TITLE
Kibana [error visualization cannot read property '2' ]

### ISSUE THREAD

**Issue by donishee** [Security-Onion-Solutions/security-onion#1797]
Hello,  i create a lab with kali, windows and security-onion (4gb ram) on virtualbox everything was fine, sguil and squert work fine; but i have a problem with kibana, when i open kibana it says " security onion error in visualization cannot read property '2' of undefined" pls help me i have no clue. Thanks

**Comment by dougburks** [comment]
Security Onion 16.04 questions should go to the Security Onion 16.04 mailing list as described here:
https://docs.securityonion.net/en/16.04/mailing-lists.html

Thanks!
