### ISSUE TITLE
soup: work around Docker change

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1804]
Docker 20.10 added multi-user.target to After= in unit file:
https://github.com/moby/moby/pull/41297

When Security Onion 16.04 updates to Docker 20.10 and reboots, this causes a delay with the Docker service and ultimately the Elastic services that require Docker will fail. We don't want to modify /lib/systemd/system/docker.service directly, so the current plan is to:

- check to see if /lib/systemd/system/docker.service includes multi-user.target in the After= line
- if so, copy /lib/systemd/system/docker.service to /etc/systemd/system/ and remove multi-user-target from there

**Comment by dougburks** [comment]
To test, install the latest ISO image and run through Setup but do NOT install updates. Snapshot the VM. Run `soup` which will install the new Docker packages. When you reboot, Elastic services will not start properly. Revert to snapshot, add the test PPA, then run `soup`, reboot, and verify that Elastic services now start properly.

**Comment by cm-ops** [comment]
VM set up according to guidance above. Tested using `soup` and reboot. Verified Elastic services did not start properly. Reverted the snapshot, added test PPA, and ran `soup` with a reboot. Verified Elastic services started properly and showed okay. Tested twice will same results both times.

**Comment by dougburks** [comment]
Thanks @cm-ops !

**Comment by dougburks** [comment]
securityonion-sostat - 20120722-0ubuntu0securityonion148 now available for Security Onion 16.04!
https://blog.securityonion.net/2020/12/securityonion-sostat-20120722.html
