### ISSUE TITLE
ubuntu 18.04 security onion the repository does not have a release file

### ISSUE THREAD

**Issue by Kat35601** [Security-Onion-Solutions/security-onion#1808]

**Comment by Kat35601** [comment]
[ERROR   ] Command '['apt-get', '-q', 'update']' failed with return code: 100
[ERROR   ] stdout: Hit:1 http://repo.saltstack.com/py3/ubuntu/18.04/amd64/archive/3002.2 bionic InRelease
[ERROR   ] stderr: E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.
[ERROR   ] retcode: 100
[ERROR   ] An error was encountered while checking the newest available version of package(s): E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.
[ERROR   ] Command '['apt-get', '-q', 'update']' failed with return code: 100
[ERROR   ] stdout: Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
[ERROR   ] stderr: E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.
[ERROR   ] retcode: 100
[ERROR   ] An error was encountered while installing package(s): E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.
[ERROR   ] Command '['apt-get', '-q', 'update']' failed with return code: 100
[ERROR   ] stdout: Hit:1 http://repo.saltstack.com/py3/ubuntu/18.04/amd64/archive/3002.2 bionic InRelease
[ERROR   ] stderr: E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.
[ERROR   ] retcode: 100
[ERROR   ] An error was encountered while installing package(s): E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.
[ERROR   ] Command '['apt-get', '-q', 'update']' failed with return code: 100
[ERROR   ] stdout: Hit:1 http://repo.saltstack.com/py3/ubuntu/18.04/amd64/archive/3002.2 bionic InRelease
[ERROR   ] stderr: E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.
[ERROR   ] retcode: 100
[ERROR   ] An error was encountered while installing package(s): E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.

**Comment by dougburks** [comment]
Security Onion 16.04 is only compatible with Ubuntu 16.04. If you want to run Ubuntu 18.04, then you'll want Security Onion 2:
https://github.com/Security-Onion-Solutions/securityonion

**Comment by Kat35601** [comment]
this is what I used 

git clone https://github.com/Security-Onion-Solutions/securityonion
cd securityonion
sudo bash so-setup-network

that is under the heading ubuntu 18.04

**Comment by Kat35601** [comment]
ERROR ] Command '['apt-get', '-q', 'update']' failed with return code: 100
[ERROR ] stdout: Hit:1 http://repo.saltstack.com/py3/ubuntu/18.04/amd64/archive/3002.2 bionic InRelease
[ERROR ] stderr: E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.
[ERROR ] retcode: 100
[ERROR ] An error was encountered while checking the newest available version of package(s): E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.
[ERROR ] Command '['apt-get', '-q', 'update']' failed with return code: 100
[ERROR ] stdout: Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
[ERROR ] stderr: E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.
[ERROR ] retcode: 100
[ERROR ] An error was encountered while installing package(s): E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.
[ERROR ] Command '['apt-get', '-q', 'update']' failed with return code: 100
[ERROR ] stdout: Hit:1 http://repo.saltstack.com/py3/ubuntu/18.04/amd64/archive/3002.2 bionic InRelease
[ERROR ] stderr: E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.
[ERROR ] retcode: 100
[ERROR ] An error was encountered while installing package(s): E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.
[ERROR ] Command '['apt-get', '-q', 'update']' failed with return code: 100
[ERROR ] stdout: Hit:1 http://repo.saltstack.com/py3/ubuntu/18.04/amd64/archive/3002.2 bionic InRelease
[ERROR ] stderr: E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.
[ERROR ] retcode: 100
[ERROR ] An error was encountered while installing package(s): E: The repository 'http://ppa.launchpad.net/securityonion/stable/ubuntu bionic Release' does not have a Release file.

**Comment by dougburks** [comment]
Again, this github repo is for Security Onion 16.04 which is only compatible with Ubuntu 16.04. If you want to run Ubuntu 18.04, then you'll want Security Onion 2 which is a totally separate repo:
https://github.com/Security-Onion-Solutions/securityonion

**Comment by Kat35601** [comment]
what am I missing

Installation on Ubuntu or CentOS
If you want to install Security Onion on CentOS 7 or Ubuntu 18.04 (not using our Security Onion ISO image), follow these steps:

Review the Hardware Requirements section.

Download the ISO image for your preferred flavor of Ubuntu 18.04 64-bit or CentOS 7 64-bit, verify the ISO image, and boot from it.

Follow the prompts in the installer. If you’re building a production deployment, you’ll probably want to use LVM and dedicate most of your disk space to /nsm as discussed in the Partitioning section.

Reboot into your new installation.

Login using the username and password you specified during installation.

If using CentOS 7 Minimal, install git:

sudo yum -y install git
Once you have git, then do the following:

git clone https://github.com/Security-Onion-Solutions/securityonion
cd securityonion
sudo bash so-setup-network
Proceed to the Configuration section.

**Comment by dougburks** [comment]
This issue is closed. Please do not comment on it anymore. If you want to run Ubuntu 18.04, then you'll want Security Onion 2 which is a totally separate github repo:
https://github.com/Security-Onion-Solutions/securityonion
