### ISSUE TITLE
NSM scripts should have a timeout period when stopping services

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#241]
```
Occasionally, a process hangs when the NSM scripts request a graceful 
termination.  We need to implement a timeout period (perhaps 30 seconds) such 
that if the process hasn't gracefully terminated, we forcibly kill it.

```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 26 Mar 2012 at 10:21

**Comment by dougburks** [comment]
Merged:
https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/commit/9e017d132e347ac26d08e14fd3505b7a6fbcc7af

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/-cbA8FgH7lg/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/05/new-nsm-package-resolves-three-issues.html
