### ISSUE TITLE
securityonion-elsa: update dependencies

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#331]
```
securityonion-elsa should depend on mysql
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 7 May 2013 at 10:35

**Comment by weslambert** [comment]
Is this still applicable?

Thanks,
Wes

**Comment by dougburks** [comment]
Hi Wes,

Yes, these changes still need to happen at some point.

**Comment by weslambert** [comment]
Thanks, Doug!
