### ISSUE TITLE
Patch for lib-nsm-common-utils from Mark Seiden

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#392]
```
Patch for lib-nsm-common-utils from Mark Seiden:
https://groups.google.com/d/topic/security-onion/aq0pABN1lHA/discussion
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 18 Sep 2013 at 2:29

**Comment by dougburks** [comment]
Merged:
https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/commit/9e017d132e347ac26d08e14fd3505b7a6fbcc7af

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/-cbA8FgH7lg/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/05/new-nsm-package-resolves-three-issues.html
