### ISSUE TITLE
netsniff-ng 0.6.4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#418]
```
also consider compiling the entire toolkit

```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 7 Nov 2013 at 7:52

**Comment by dougburks** [comment]
https://groups.google.com/d/topic/netsniff-ng/sCHVE_UIspU/discussion

**Comment by dougburks** [comment]
http://article.gmane.org/gmane.linux.network.netsniff-ng/1258

**Comment by dougburks** [comment]
https://groups.google.com/d/topic/netsniff-ng/PvbU9Cy-lCE/discussion

**Comment by dougburks** [comment]
https://groups.google.com/d/topic/netsniff-ng/GCpf_o-vDQ0/discussion

https://github.com/netsniff-ng/netsniff-ng/releases/tag/v0.6.3

**Comment by dougburks** [comment]
https://github.com/netsniff-ng/netsniff-ng/releases/tag/v0.6.4

**Comment by dougburks** [comment]
This was done as part of the 16.04 transition.
