### ISSUE TITLE
CapMe needs to handle UDP better

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#492]
```
CapMe needs to handle UDP better
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 27 Feb 2014 at 1:47

**Comment by dougburks** [comment]
/usr/lib/sguild/SguildTranscript.tcl
llength == 8
lassign add proto
BroScriptRequest change 6 to $proto

/var/www/so/capme/.scripts/cliscriptbro.tcl
add proto as parameter

/var/www/so/capme/.inc/callback.php
default to cliscriptbro for first run and send proto parameter

**Comment by dougburks** [comment]
commits:

https://github.com/Security-Onion-Solutions/securityonion-capme/commit/f15bf56debd14da5d5ffa7ba303d2811a954e3f9

https://github.com/Security-Onion-Solutions/securityonion-capme/commit/3a34788aa7f9d1fbe577af6f63506d0af27568a5

https://github.com/Security-Onion-Solutions/securityonion-capme/commit/861c08880b6ec4c97bcd3576ef0e82a774dcda29

https://github.com/Security-Onion-Solutions/securityonion-capme/commit/abe051132c981a7e40c854602553fc5391799248

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/nn_GW47PtkE/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2016/12/capme-101-is-now-available-and-supports.html
