### ISSUE TITLE
CapMe: send credentials interactively to avoid exposing on command line

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#493]
```
CapMe: send credentials interactively to avoid exposing on command line
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 27 Feb 2014 at 6:33

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-capme/commit/0685aeffb6fe2d1e0284e5db013932dec4892588

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/32lozOUC_JA/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2016/05/securityonion-capme-20121213.html
