### ISSUE TITLE
Setup: restart starman

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#500]
```
Setup: restart starman
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 7 Mar 2014 at 12:04

**Comment by dougburks** [comment]
Updated:
https://github.com/Security-Onion-Solutions/securityonion-setup/commit/8bf745a267cf81dbbe13c5e6f313cc7161eb02e1

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/PBY2wJH9ruo/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/06/elsa-1205-now-available.html
