### ISSUE TITLE
Setup: avoid writing ELSA_PORT twice in SSH_CONF

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#504]
```
Setup: avoid running securityonion_elsa_register.rb twice
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 8 Mar 2014 at 11:57

**Comment by dougburks** [comment]
https://groups.google.com/d/topic/security-onion/7Y2YJG0S3FM/discussion

**Comment by dougburks** [comment]
Updated code:
https://github.com/Security-Onion-Solutions/securityonion-setup/commit/2bc32cd6cdd1db00888d6af5ad519b5ba5e650ad

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/PBY2wJH9ruo/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/06/elsa-1205-now-available.html
