### ISSUE TITLE
ELSA syslog-ng.conf filter f_bro_headers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#512]
```
ELSA syslog-ng.conf filter f_bro_headers
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 19 Mar 2014 at 4:16

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/OHhNEapIUgE/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/06/elsa-1205-now-available.html
