### ISSUE TITLE
Setup: if enabling salt on a sensor, check top.sls to make sure it doesn't already exist

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#547]
```
Setup: if enabling salt on a sensor, check top.sls to make sure it doesn't 
already exist
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 5 Jun 2014 at 3:19

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/OHhNEapIUgE/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/06/elsa-1205-now-available.html
