### ISSUE TITLE
Add VirusTotal uploader

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#558]
```
http://blog.virustotal.com/2014/07/virustotal-open-sources-uploader-for.html
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 10 Jul 2014 at 1:58

**Comment by dougburks** [comment]
Most folks do not want to upload files to VirusTotal as this may be an opsec issue, signaling to the adversary that the malware has been discovered.
