### ISSUE TITLE
nsm_server_backup-config should check FORCE_YES

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#561]
```
nsm_server_backup-config should check FORCE_YES
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 22 Jul 2014 at 12:39

**Comment by dougburks** [comment]
https://groups.google.com/d/topic/security-onion/nxd6u8m4itc/discussion

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/pull/6

commit:
Security-Onion-Solutions/securityonion-nsmnow-admin-scripts@4f66917

submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/tGXKlYusqLg/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2016/07/securityonion-nsmnow-admin-scripts.html
