### ISSUE TITLE
securityonion-web-page: add Security Onion cheat sheet PDF

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#571]
```
securityonion-web-page: add Security Onion cheat sheet PDF
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 1 Aug 2014 at 7:14

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/dTf2Fe-0yTc/discussion

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/05/securityonion-web-page-20141015.html
