### ISSUE TITLE
Setup: add -y option

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#592]
```
Setup: add -y option
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 16 Sep 2014 at 6:22

**Comment by weslambert** [comment]
Submitted: https://github.com/Security-Onion-Solutions/securityonion-setup/pull/22

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/bN-9Pgb19w8/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2016/08/securityonion-setup-20120912.html
