### ISSUE TITLE
Setup: sensor should stop/disable Apache and Snorby worker

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#596]
```
Setup: sensor should stop/disable Apache and Snorby worker
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 18 Sep 2014 at 12:25

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-setup/commit/ca6314c2950eb20f3e551dfb479aa54f0ea3ec1c

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/HBWNcVaE8L4/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/07/new-securityonion-setup-package-allows.html
