### ISSUE TITLE
Setup: replace tmp with mktemp

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#605]
```
Setup: replace tmp with mktemp
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 24 Sep 2014 at 4:20

**Comment by dougburks** [comment]
commits:

https://github.com/Security-Onion-Solutions/securityonion-setup/commit/fa0f98f2454c5ac11bc002aa33c70d828832c617

https://github.com/Security-Onion-Solutions/securityonion-setup/commit/2ce727eaf3e2b7cf0261e2dc5004bae0b5b80281

https://github.com/Security-Onion-Solutions/securityonion-setup/commit/6c210131629b1bf27359c1e638ebfa779c8e334c

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/HBWNcVaE8L4/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/07/new-securityonion-setup-package-allows.html
