### ISSUE TITLE
Update bash scripts to use /bin/sh

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#608]
```
checkbashisms
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 25 Sep 2014 at 12:26

**Comment by weslambert** [comment]
Is this still intended to be completed? :)

**Comment by dougburks** [comment]
Yes, this is still a good idea, although it will be a major undertaking to convert all the bashisms to work under sh.
