### ISSUE TITLE
ELSA: starman restart doesn't work properly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#651]
```
ELSA: starman restart doesn't work properly
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 5 Dec 2014 at 3:16

**Comment by weslambert** [comment]
Has this already been resolved?

Looks like maybe related to:
https://groups.google.com/d/msg/security-onion/K_5vWQpd8VM/KY-HVxzXldYJ
https://github.com/Security-Onion-Solutions/security-onion/issues/500

Looks like it was (maybe?) resolved here:
http://blog.securityonion.net/2015/06/elsa-1205-now-available.html

Thanks,
Wes

**Comment by dougburks** [comment]
Hi Wes,

I think this particular issue has to do with the fact that `sudo service starman restart` doesn't actually restart the starman processes correctly.  Currently, you have to do `sudo service starman stop` followed by `sudo service starman start`.

**Comment by weslambert** [comment]
Thanks, Doug!
