### ISSUE TITLE
NSM: barnyard sending blank interface to syslog output

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#652]
```
NSM: barnyard sending blank interface to ELSA
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 9 Dec 2014 at 12:04

**Comment by dougburks** [comment]
discussion:
https://groups.google.com/d/topic/security-onion/eaR5XCPeQg4/discussion

**Comment by dougburks** [comment]
Code Changes:

https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/pull/16

https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/commit/95c2ede98e93b6b8704de9c93f6f4531cb40a36b

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/F0ywBbJ9jvo/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2017/08/securityonion-nsmnow-admin-scripts.html
