### ISSUE TITLE
ELSA 1205

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#657]
```
ELSA: email check
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 22 Dec 2014 at 6:11

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/OHhNEapIUgE/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/06/elsa-1205-now-available.html
