### ISSUE TITLE
ELSA: update bro_notice parser to parse src and dst fields

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#674]
```
ELSA: update bro_notice parser to parse src and dst fields
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 15 Jan 2015 at 2:38

**Comment by dougburks** [comment]
Re-opening since it won't be fixed on the Bro side until Bro 2.5:
https://bro-tracker.atlassian.net/browse/BIT-1339?page=com.atlassian.jira.plugin.system.issuetabpanels:changehistory-tabpanel

**Comment by dougburks** [comment]
Parser from Simone Bonetti:
https://groups.google.com/d/topic/security-onion/xpDYjNppSGY/discussion

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/OHhNEapIUgE/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/06/elsa-1205-now-available.html
