### ISSUE TITLE
rule-update: create /usr/local/lib/snort_dynamicrules/ if it doesn't already exist

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#677]
```
mkdir -p /usr/local/lib/snort_dynamicrules/
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 20 Jan 2015 at 2:43

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/nlxZDG_tPJ0/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/04/new-securityonion-rule-update-package.html
