### ISSUE TITLE
rule-update: /etc/cron.d/rule-update should have 2>&1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#678]
```
rule-update: /etc/cron.d/rule-update should have 2>&1
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 21 Jan 2015 at 3:06

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/nlxZDG_tPJ0/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/04/new-securityonion-rule-update-package.html
