### ISSUE TITLE
rule-update: wipe snort_dynamicrules directory on sensor

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#681]
```
rule-update: wipe snort_dynamicrules directory on sensor
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 28 Jan 2015 at 8:03

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/nlxZDG_tPJ0/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/04/new-securityonion-rule-update-package.html
