### ISSUE TITLE
sostat: list number of ELSA buffers in queue and warn if higher than 10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#692]
```
sostat: list number of ELSA buffers in queue and warn if higher than 10
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 6 Feb 2015 at 1:16

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/E9ql7fPtmqg/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/04/new-securityonion-sostat-package.html
