### ISSUE TITLE
sosetup: improve input validation for email address

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#693]
```
sosetup: improve input validation for email address
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 18 Feb 2015 at 2:39

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-setup/commit/24f7241caad4dbd886e2980136877da66e661539

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/HBWNcVaE8L4/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/07/new-securityonion-setup-package-allows.html
