### ISSUE TITLE
rule-update: log snorby reference table update to barnyard2-snorby.log

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#697]
```
rule-update: log snorby reference table update to barnyard2-snorby.log
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 9 Mar 2015 at 1:17

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/nlxZDG_tPJ0/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/04/new-securityonion-rule-update-package.html
