### ISSUE TITLE
sostat: include number of CPU cores

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#701]
```
sostat: include number of CPU cores
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 12 Mar 2015 at 10:03

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/E9ql7fPtmqg/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/04/new-securityonion-sostat-package.html
