### ISSUE TITLE
Move from Google Code to Github

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#703]
```
Move from Google Code to Github
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 13 Mar 2015 at 10:24

**Comment by dougburks** [comment]
Submitted for feedback:
https://groups.google.com/d/topic/security-onion/pcsPxWRR6TM/discussion

**Comment by dougburks** [comment]
Need to update securityonion-web-page package as well.

**Comment by dougburks** [comment]
Need to update Setup package as well.

**Comment by dougburks** [comment]
Need to update sostat as well.

**Comment by dougburks** [comment]
Submitted packages for testing:
https://groups.google.com/d/topic/security-onion-testing/lYDQrSxu3us/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/03/four-package-updates.html
