### ISSUE TITLE
ossec_agent: improvements from Brian Kellogg

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Security-Onion-Solutions/security-onion#705]
```
https://groups.google.com/d/topic/security-onion/QZ1aVC58LYo/discussion
```

Original issue reported on code.google.com by `doug.bu...@gmail.com` on 18 Mar 2015 at 1:41

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/N5gpeSHmIlk/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/05/new-securityonion-sguil-agent-ossec.html
