### ISSUE TITLE
Question regarding OSSec and Security Onion Alerts

### ISSUE THREAD

**Issue by bryanbent2717** [Security-Onion-Solutions/security-onion#713]
I am trying to get SO to log OSSEC events. I have a client attached but no events are showing in ELSA and Sguil. The steps below are what I have done in order to resolve the issue.

System consists of one SO box standalone and a Windows 7 client 
Created placeholder and key in Security Onion Installed the OSSEC 
client on the Win7 box, entered the required info into to get it to sync: Name, IP and Key.
The logs on the win7 box show it as connected to the server 
When running "sudo /var/ossec/bin/list_agents -c" it shows the client I've restarted the SO and client box.
I've ran wireshark and can see traffic from the client box to SO on port 1514 
There is no firewall on the client I did not change Security 
Onion's firewall because it looked like port 1514 was open and verified through wireshark
I ran "sudo tail -f /var/ossec/logs/archives/archives.log" and could see events in the log file from the client.

I don't really know what I am supposed to be seeing as events, since there are none. Is it supposed to generate logs to Sguil, ELSA and in other programs? Also will SO log everything or just specific alerts and how do i manage those alerts? Thank you for your time and help.

**Comment by dougburks** [comment]
Please send all questions and problems to our mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!
