### ISSUE TITLE
`securityonion-libcapture-tiny-perl` should `Provides: libcapture-tiny-perl`

### ISSUE THREAD

**Issue by Ionic** [Security-Onion-Solutions/security-onion#728]
Hi

Our users have been running into this problem for quite some time, but obviously no one ever created a proper bug report.

The package `securityonion-libcapture-tiny-perl` should have a `Provides: libcapture-tiny-perl` statement to not break whenever third party packages depend upon `libcapture-tiny-perl`.

Thanks for looking into this in advance.

Mihai

**Comment by Ionic** [comment]
That said, maybe it should also `Conflicts: libcapture-tiny-perl` and `Replaces: libcapture-tiny-perl`, but I'm not sure if that's actually a good thing to do.

**Comment by dougburks** [comment]
Hi Mihai,

Who are your users and what else are they running that uses libcapture-tiny-perl?

**Comment by Ionic** [comment]
Hi Doug,

I'm upstream for X2Go, a remote desktop solution based upon a fork of NX 3.5 we also maintain.

One of the packages (`libx2go-server-perl`: [debian/control in the git archive] (http://code.x2go.org/gitweb?p=x2goserver.git;a=blob;f=debian/control;h=0eab5c2f2502fe10a9c8e02e22dc137cbc4430de;hb=HEAD#l100)) depends upon libcapture-tiny-perl, which not co-installable with your `securityonion-libcapture-tiny-perl` package. The semantics of this dependency is met by your package, though.



Mihai

**Comment by trcns** [comment]
Mihai
Were you able to resolve an issue with X2Go? if you did can you please guide me through?

**Comment by Ionic** [comment]
Depends on what issue you mean. This one specifically? If you make sure that `securityonion-libcapture-tiny-perl` is installed, you can "safely" force-install x2goserver. I won't guide you through it, though, because that procedure is risky still and there will leave the dpkg DB in a "bad state".

**Comment by trcns** [comment]
Any update, if x2goserver will work or not with security onion?

**Comment by dougburks** [comment]
Please see my response to you on the mailing list:

"Per Issue 728, I'll be updating the securityonion-libcapture-tiny-perl 
package to avoid this issue in the future.  In the meantime, there may 
be a way to manually workaround, but I haven't had time to test. "

https://groups.google.com/d/topic/security-onion/VQJF3lv0uZ4/discussion

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/jvHXVpgo6fM/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/08/new-securityonion-libcapture-tiny-perl.html
