### ISSUE TITLE
Setup: add option for pivot URL

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#729]
Populate field with IP address of management interface but allow user to change

This will be used when pivoting:
from ELSA to CapMe
from Squert to ELSA

**Comment by rootwars** [comment]
Upvote.  This would be really useful for our deployment, where a valid cert is used for all webapps in the SO environment and we access via FQDN.

**Comment by dougburks** [comment]
Hi @rootwars,

You know you can manually update these values today, right?

**Comment by dougburks** [comment]
In BDR2, we are configuring Apache to proxy from https://your.security.onion.box/elsa-query/ to the ELSA listener on port 3154 so from a user perspective all traffic will remain on port 443 and all hyperlinks will be relative.  This means that you'll be able to connect via IP or FQDN and everything will just work with no further configuration.  Closing this issue.

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2016/01/security-onion-140431-iso-image-now.html
