### ISSUE TITLE
Unable to boot  - Stuck on main screen

### ISSUE THREAD

**Issue by makflwana** [Security-Onion-Solutions/security-onion#750]
Hello Guys,

I am trying to install security onion - 12.04.5.1 on my computer and running with following issues :+1: 

1. Downloaded iso does not match checksum. Tried 2 still the same. (Torrent and direct)
2. Continue without checcksum works on my MacBook but new download on PC does not work.
3. All other virtual machine is working. My PC is having windows 7 64 bit and 16 GB memory and 16 core processors.

Can anybody assist.

![image](https://cloud.githubusercontent.com/assets/12878182/8146787/e3f2f596-128f-11e5-914d-0deec364e79e.png)

**Comment by dougburks** [comment]
Please send all questions to the security-onion mailing list.

Thanks!

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
