### ISSUE TITLE
ufw logging

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#770]
https://groups.google.com/d/topic/security-onion/pQjto_mF5aY/discussion

**Comment by SMAPPER** [comment]
Adding the following lines to the bottom of syslog-ng.conf fixes this issue:

source s_kmsg { file("/proc/kmsg"); };
filter f_ufw { match("\\[UFW " value("MESSAGE")); };
destination d_ufw { file("/var/log/ufw.log"); };
log { source(s_kmsg); filter(f_ufw); destination(d_ufw); };

Shane Castle deserves full credit. Here's a script I used to push this to multiple sensors with salt:

#!/bin/bash
if grep -q 'f_ufw' /etc/syslog-ng/syslog-ng.conf
then
  echo "UFW is already configured for syslog-ng"
else
  echo "Configuring UFW for syslog-ng"
  echo 'source s_kmsg { file("/proc/kmsg"); };' | sudo tee -a /etc/syslog-ng/syslog-ng.conf
  echo 'filter f_ufw { match("\\[UFW " value("MESSAGE")); };' | sudo tee -a /etc/syslog-ng/syslog-ng.conf
  echo 'destination d_ufw { file("/var/log/ufw.log"); };' | sudo tee -a /etc/syslog-ng/syslog-ng.conf
  echo 'log { source(s_kmsg); filter(f_ufw); destination(d_ufw); };' | sudo tee -a /etc/syslog-ng/syslog-ng.conf
  sudo service syslog-ng restart
fi

This allowed me to run it against the same sensor more than once without accidentally messing up syslog-ng.conf.
