### ISSUE TITLE
securityonion-elsa-extras: update sysmon parser

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#782]
https://github.com/Security-Onion-Solutions/securityonion-elsa-extras/pull/5

**Comment by defensivedepth** [comment]
Sysmon 3.1 was released yesterday, and this parser may require another edit to be compatible with both 3.0 & 3.1, so please hold on this for now.

**Comment by dougburks** [comment]
Will do, thanks!

**Comment by defensivedepth** [comment]
I have confirmed that this parser is compatible with both 3.0 & 3.1. It can be released.

Thanks,

**Comment by defensivedepth** [comment]
New PR, sorry for the confusion:

https://github.com/Security-Onion-Solutions/securityonion-elsa-extras/pull/8

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/fPWJbPBkIww/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2015/09/new-securityonion-elsa-extras-and.html
