### ISSUE TITLE
I just installed XRDP, But I don't see SecurityOnion in remote window?

### ISSUE THREAD

**Issue by trcns** [Security-Onion-Solutions/security-onion#783]
I just installed XRDP server on SecurityOnion Console. When I remote-in I don't security onion in the menu. But I login locally it there. Any suggestion?

**Comment by ozirus** [comment]
Port 3389 open from ufw?
21 Tem 2015 Sal, saat 22:53 tarihinde trcns <notifications@github.com> şunu
yazdı:

**Comment by trcns** [comment]
Port is open I have session established, I have all the icons and folders "Accessories", "Games" etc, but "Security Onion".

**Comment by trcns** [comment]
In Remote session all application under the Group "SecurityOnion" moved into "Others"

**Comment by dougburks** [comment]
If you have further questions, please send them to our mailing list instead.  

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!
