### ISSUE TITLE
sostat: remove snorby

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#790]

**Comment by KeyboardMonkey** [comment]
Hi @dougburks, how can I contribute to this project? I'm currently using SO for a mid-sized network and I can help you with testing or anything else you may need.

**Comment by dougburks** [comment]
Hi @KeyboardMonkey, you can join the testing group:
https://github.com/Security-Onion-Solutions/security-onion/wiki/TeamMembers

**Comment by KeyboardMonkey** [comment]
Thank you @dougburks !
You guys are doing an awesome job (Y)

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-sostat/commit/0d5adfb6944ba1225c8df6d8d036c789b1671bda

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2016/01/security-onion-140431-iso-image-now.html
