### ISSUE TITLE
The ppa is not found

### ISSUE THREAD

**Issue by amlwwalker** [Security-Onion-Solutions/security-onion#809]
When following the instructions on Ubuntu to install Security Onion, adding the ppa and updating aptitude repositories, it is not found...

```
W: Failed to fetch http://ppa.launchpad.net/securityonion/stable/ubuntu/dists/vivid/main/binary-i386/Packages  404  Not Found
```
Any ideas why? This is as a result of running:

```
sudo add-apt-repository -y ppa:securityonion/stable
sudo apt-get update
```

**Comment by dougburks** [comment]
Hi Alex,

Looks like you're running Ubuntu 15.04 Vivid.

Please see:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Installation

"Please keep in mind that our PPA and packages are only compatible with Ubuntu 12.04."

If you have further questions or problems, please use our security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

**Comment by amlwwalker** [comment]
such a shame.  Ubuntu is moving on. whats missing? Is Security Onion going to support 15?

**Comment by dougburks** [comment]
Ubuntu 12.04 is a Long Term Support release and is still supported.  We will be moving to the next Long Term Support release (14.04) soon.  

If you have further questions or problems, please use our security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
