### ISSUE TITLE
securityonion-sostat: awk division error when Bro doesn't report stats correctly

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#817]
https://groups.google.com/d/topic/security-onion/6wlDJUtPVXg/discussion

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion-sostat/pull/32

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/CznWqiFc-gM/discussion

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2019/03/securityonion-sostat-20120722.html
