### ISSUE TITLE
Error with built-in ELSA queries on Sysmon events

### ISSUE THREAD

**Issue by mpilking** [Security-Onion-Solutions/security-onion#823]
I played around with Sysmon, OSSEC, and ELSA recently.  The OSSEC forwarding worked once I got the right version of the Windows agent.  ELSA parsing worked at that point.  However, the built-in ELSA query produced the error "No positive value in query".  

For example, ELSA > Report On > SYSMON_PROCESS > image

The resulting search produced the following query, which failed with the error "No positive value in query.":

   groupby:SYSMON_PROCESS.image

If I change the query to this, it works without error:

   class:"SYSMON_PROCESS" groupby:image

The same occurred when searching by user (groupby:SYSMON_NETWORK.user should be class:"SYSMON_NETWORK" groupby:user)

Thanks,
Mike

**Comment by mpilking** [comment]
After writing this, it occurred to me that this is an ELSA built-in query, not a Security Onion query necessarily.  Let me know if I should move this to the ELSA repository.

**Comment by dougburks** [comment]
Hi Mike,

Were you trying to do a groupby by itself?  ELSA can only do a groupby if there are search results to group.  

One of the reasons why I built the ELSA query links on the left side was so that users wouldn't have to use the "Report On" dropdowns and run into issues like these.

**Comment by mpilking** [comment]
Yes, I guess I was doing a groupby by itself.  I didn't realize that pull down was specifically for groupby.  I never use ELSA that way. I usually start with a free-form query or with your built-in queries and then groupby by clicking the relevant field from the results.  Since there's not yet a Sysmon Security Onion search, I started looking in the middle pull down and found it there.  But duh, that's groupby.  Chalk this one up to user error :)

Thanks,
Mike
