### ISSUE TITLE
pulledport.pl refinement

### ISSUE THREAD

**Issue by Middle-Siggy** [Security-Onion-Solutions/security-onion#832]
Found an issue with pulled pork not pulling down the latest signatures because there was another line with the word ENGINE in /etc/nsm/securityonion.conf (IDS_ENGINE_ENABLED="yes"). 

Solution was to refine the grep statement inside the pulledpork.pl file.

Diff:
```
diff pulledpork.pl pulledpork.pl.orig
1853c1853
<                     my $Engine = `grep -E "^ENGINE" /etc/nsm/securityonion.conf | cut -d\= -f2`;
---
>                     my $Engine = `grep ENGINE /etc/nsm/securityonion.conf | cut -d\= -f2`;
```

**Comment by dougburks** [comment]
Added to Roadmap:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Roadmap

**Comment by dougburks** [comment]
Submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/AJEDNmzC6LU/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2016/03/securityonion-pulledpork-070.html
