### ISSUE TITLE
soup: error checking

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#833]

**Comment by weslambert** [comment]
Is this in regard to any specific packages/actions?

**Comment by dougburks** [comment]
Hi Wes,

This issue is for adding code to soup that will check the exit status of each individual command such as `purge-old-kernels` and each `apt-get` invocation.  The main thing I'm looking for here is for the user to be prompted if there is something wrong with their apt configuration, rather than them just thinking that there are no updates available.

**Comment by weslambert** [comment]
Thanks, Doug!
