### ISSUE TITLE
2.6.3 Background Classification Not Working

### ISSUE THREAD

**Issue by bboklewski** [Security-Onion-Solutions/security-onion#834]
Not sure if anyone else is having issues, but background classification is not working for me in 2.6.3.   It will reclassify existing events, they just won't run in the background.

**Comment by dougburks** [comment]
Are you referring to Snorby?  It is now considered unmaintained and is being removed in the next release of Security Onion.

I'd recommend that you go ahead and disable Snorby and start using Squert/Sguil/ELSA instead:
https://github.com/Security-Onion-Solutions/security-onion/wiki/DisablingProcesses#disabling-snorby

**Comment by bboklewski** [comment]
Thanks for the reply Doug, I didn't know that.  I will work with the other tools instead.  I am new to SO and as a side question are you still doing training for SO?  Is there anything in the works for in depth training videos for free/purchase?  I would be interested either way.

**Comment by dougburks** [comment]
Training will start back up in early 2016.  Please subscribe to one or more of our social media channels to be notified when training is announced.  Thanks!

**Comment by bboklewski** [comment]
Any reason why Bro wouldn’t be working.  I just get a spinning wheel in the BRO window when drilling down through the alert id of an event.

 

 

 

Bob Boklewski

Network Administrator

847-947-6919



 

Past performance is not necessarily indicative of future results. Futures trading is not for everyone. There is always a risk of loss.

**Comment by dougburks** [comment]
Please see:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Support
