### ISSUE TITLE
Cannot Load SO on HP Z440

### ISSUE THREAD

**Issue by trcns** [Security-Onion-Solutions/security-onion#837]
I bought an HP Z440 computer loaded with five NIC's and 16 (4x4) Tara Bytes of HD.

Now I have a dead end. HP verifies that Ubuntu 14.04 is supported but does want to help Ubuntu 12.04.

I tried every possible way to get help, but I am not having any luck. In the mean while I holding on to this useless machine from last six months.

Can someone please help?

**Comment by dougburks** [comment]
Hi trcns,

Our new version of Security Onion based on Ubuntu 14.04 should be released soon.  You can test it today:
http://blog.securityonion.net/2015/12/bdr2-iso-testers-wanted.html

If you have further questions or problems, please use our mailing list(s):
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
