### ISSUE TITLE
Move downloads from SourceForge to Github

### ISSUE THREAD

**Issue by kruug** [Security-Onion-Solutions/security-onion#838]
You've got the repo with the hosting space, use it...

**Comment by dougburks** [comment]
Hi kruug,

Yes, we're using Github Releases for the upcoming 14.04 release:
https://github.com/Security-Onion-Solutions/security-onion/releases

**Comment by almusaddar** [comment]
Hi Doug,
Please add release link to security onion blog post.
Also make plan to update your tutorial on youtube.

Thanks

**Comment by dougburks** [comment]
Hi almusaddar,

Yes, I've already planned to do this :)

**Comment by almusaddar** [comment]
Hi Doug,
Can you plan also to create a tutorial on integration with pfsense specially barnyard2 setting on pfsense, I managed to connect pfsense NIDS logs to snorby on Security Onion, Also i suggest to create pfsense as source for IDS in the setup script. This will create ultimate open source security framework.

**Comment by dougburks** [comment]
Snorby is now considered un-maintained and will not be in the next release of Security Onion.

If you have further comments or questions, please use our security-onion mailing list instead of this Issue Tracker:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!

**Comment by kruug** [comment]
Will you also be moving source code and cleaning up the installation instructions in the Wiki?  Maybe adding a quick-start to the README?

**Comment by dougburks** [comment]
Hi kruug,

No source code is stored on SourceForge.

The vast majority of our source code is already available on github at:
https://github.com/Security-Onion-Solutions

I've already created the following wiki pages:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Security-Onion-14.04-Release-Notes
https://github.com/Security-Onion-Solutions/security-onion/wiki/Upgrading-from-12.04-to-14.04

Please feel free to add to or edit the wiki as you see fit.

**Comment by kruug** [comment]
Wouldn't it make more sense to store the source code here? https://github.com/Security-Onion-Solutions/security-onion ?

**Comment by dougburks** [comment]
No, individual packages need their own individual git repo.

**Comment by kruug** [comment]
Oh, I guess I didn't think that way.  Since it's a collection of other packages, that makes sense.

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2016/01/security-onion-140431-iso-image-now.html
