### ISSUE TITLE
Can the latest Security Onion be installed on CentOS

### ISSUE THREAD

**Issue by spindell** [Security-Onion-Solutions/security-onion#851]
Can Security Onion be installed on a server who's operating system is CentOS?

**Comment by dougburks** [comment]
Hi Stacee,

I just replied to your email.  Security Onion is based on Ubuntu and so it's not designed to run on CentOS.  You could however install Security Onion in a VM on top of CentOS.

**Comment by spindell** [comment]
Thanks Doug.  I am taking this information to my supervisor.

On Tue, Feb 2, 2016 at 10:26 AM, Doug Burks <notifications@github.com>
wrote:

> Hi Stacee,
>
> I just replied to your email. Security Onion is based on Ubuntu and so
> it's not designed to run on CentOS. You could however install Security
> Onion in a VM on top of CentOS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Security-Onion-Solutions/security-onion/issues/851#issuecomment-178632825>
> .
>



-- 

*Stacee R. Pindell CASP, Security+, C|EH, C|HFI, FITSP-O, CFCP, SnortCP*
*Information Systems Security Engineer*
*CyberCore Technologies*
*410-854-9670 (work)*
*443-867-7033 (cell)*
