### ISSUE TITLE
NSM: Squert object_mappings table has wrong permissions

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#866]
https://groups.google.com/d/topic/security-onion/h_WbwuZAvX4/discussion

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/commit/de645b440900f2a17b5e94d7d5fd7b640fa55934

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/NPr4iqxNy68/discussion

**Comment by b-u-g-s** [comment]
Thanks Doug,
Will try to test tomorrow. Is it easy to apply a test patch and remove? Or do I need a completely separate testing VM instance of SO?

---
S.

**Comment by dougburks** [comment]
Testing should be done in a test VM. Please see the instructions at the
testing link.  Thanks!

On Sunday, March 13, 2016, Bugs <notifications@github.com> wrote:

> Thanks Doug,
> Will try to test tomorrow. Is it easy to apply a test patch and remove? Or
> do I need a completely separate testing VM instance of SO?
>
> ---
> S.
>
> > On 11 Mar 2016, at 21:22, Doug Burks <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > submitted for testing:
> >
> https://groups.google.com/d/topic/security-onion-testing/NPr4iqxNy68/discussion
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Security-Onion-Solutions/security-onion/issues/866#issuecomment-196046641>
> .
>


-- 
Doug Burks

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2016/03/securityonion-nsmnow-admin-scripts.html

**Comment by b-u-g-s** [comment]
Hi Doug,

I wasn’t fast enough to test it :)
But I now have a testing VM that should allow me to be faster in future.
Not that it helps but I tested on my “production” VM with the official update an it works well! :)

Thanks,
S.
PS: Interesting that you sending me that email to this email address as I was using a different one for the google SO group. Not an issue, I just have too many different email addresses ;)

**Comment by dougburks** [comment]
If you received an email from Github, it would have been to whatever email address you used to sign up for Github.
