### ISSUE TITLE
CapMe: add session support to avoid re-authenticating every time

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#871]

**Comment by weslambert** [comment]
I'd be happy to  look into this if no one else is already pursuing it.

Thanks,
Wes

**Comment by dougburks** [comment]
Go for it!  Thanks, Wes!

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-capme/commit/ce820f0c77b4cd9c23cab8c7fb46333b480daca4

**Comment by weslambert** [comment]
Nice!  Sorry I wasn't able to get to this.  Can't wait to try it out!

Thanks,
Wes

**Comment by dougburks** [comment]
No problem, Wes.  I had forgotten that you had expressed interest back in February until I added the commit comment on this page.  

This is just a first pass and may require a few iterations of testing to get it just right.  Look for an email to the testing list later today or tomorrow.

Thanks!

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/rNPDXmH4hp8/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2016/06/new-capme-and-squert-packages-resolve.html
