### ISSUE TITLE
Security Onion 14.04, want to Use Raid 5 for PCAPs

### ISSUE THREAD

**Issue by trcns** [Security-Onion-Solutions/security-onion#872]
I had 4 disks of 4 Tara bytes, Since I could not install and boot Security Onion from Raid 5, I used first stand alone disk to install security onion. Than I created an 8 Tara byte of Raid 5  using rest of 3 disks named (\Storage). All the setting are default and now I ran out of disk space from the first 4 tara byte disk. Can I extend my disk space by adding the disk space from Raid 5, and how? If not, than how can I change setting so all captured packets should store on Raid drive (/Storage)?

**Comment by dougburks** [comment]
Hi trcns,

Please see:
https://github.com/Security-Onion-Solutions/security-onion/wiki/NewDisk

If you have further questions or problems, please see:
https://github.com/Security-Onion-Solutions/security-onion/wiki/Support
