### ISSUE TITLE
Setup: division by 0 error on SNIFFING_INTERFACES if master server (no sniffing)

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#876]

**Comment by dougburks** [comment]
@weslambert, can you take a look at this, please?
https://github.com/Security-Onion-Solutions/securityonion-setup/blob/master/bin/sosetup#L74

Thanks!

**Comment by weslambert** [comment]
Sure thing, Doug--I will take a look.

Thanks!

**Comment by dougburks** [comment]
Thanks, Wes!

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/S5OtvZOTcfQ/discussion

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2016/03/securityonion-setup-20120912_17.html
