### ISSUE TITLE
Switch to Chrony from ntpd

### ISSUE THREAD

**Issue by jollyrogue** [Security-Onion-Solutions/security-onion#877]
Chrony works well on servers and devices that are powered off for random periods of time versus ntpd which is really designed for just server use.

While Chrony doesn't benefit servers much, it does provides quite a few benefits to Analyst VMs/Workstations. It's been design to handle situations where the install has been powered off or unsynced for large and small periods of time, and it can easily handle clocks that are skewed by quite a bit. 

ntpd is designed for always on devices, and it's good at that. It's just not good at handling clocks with large skews, and it takes a while to bring the device back inline.

**Comment by dougburks** [comment]
Hi Ryan,

Thanks for the suggestion!  

However, I haven't had any complaints about ntpd.  We'll stick with ntpd for now.  If we ever decide to look at alternatives, I'll definitely keep chrony in mind.

Thanks!
