### ISSUE TITLE
Security Onion and VMware 10 - MAC Addresses changing randomly

### ISSUE THREAD

**Issue by Paton1** [Security-Onion-Solutions/security-onion#878]
Hi,

Having an issue where my network interfaces are being cycled around randomly. I noticed this by identifying that the MAC addresses were changing when I reboot the VM. 

 I would like to set my eth0 as NAT, eth1 and eth2 as monitoring interfaces, eth3 as management (which I don't need really but setup asks for) and eth4 as a seperate network.

What's the best way to implement this permanently?

Many thanks,

Ian

**Comment by dougburks** [comment]
Hi Ian,

Please send all questions/problems like this to our security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!

**Comment by Paton1** [comment]
Cool, cheers
