### ISSUE TITLE
How to Run OSSEC in SO V14.4?

### ISSUE THREAD

**Issue by trcns** [Security-Onion-Solutions/security-onion#885]
How do I access OSSEC, I do not find OSSEC icon for it?

Status: securityonion
  * sguil server                                                       [  OK  ]
Status: HIDS
  * ossec_agent (sguil)                                                [  OK  ]
Status: Bro
Getting process status ...
Getting peer status ...
Name         Type    Host             Status    Pid    Peers  Started
manager      manager localhost        running   7340   5      17 Mar 17:58:51
proxy        proxy   localhost        running   7534   5      17 Mar 17:58:54
cicny-is-onion01-eth1-1 worker  localhost        running   8455   2      17 Mar 17:59:02
cicny-is-onion01-eth2-1 worker  localhost        running   8459   2      17 Mar 17:59:02
cicny-is-onion01-eth3-1 worker  localhost        running   8466   2      17 Mar 17:59:02
cicny-is-onion01-eth4-1 worker  localhost        running   8463   2      17 Mar 17:59:02
Status: cicny-is-onion01-eth1
  * netsniff-ng (full packet data)                                     [  OK  ]
  * pcap_agent (sguil)                                                 [  OK  ]
  * snort_agent (sguil)                                                [  OK  ]
  * suricata (alert data)                                              [  OK  ]
  * barnyard2 (spooler, unified2 format)                               [  OK  ]
  * prads (sessions/assets)                                            [  OK  ]
  * sancp_agent (sguil)                                                [  OK  ]
  * pads_agent (sguil)                                                 [  OK  ]
  * http_agent (sguil)                                                 [  OK  ]
Status: cicny-is-onion01-eth2
  * netsniff-ng (full packet data)                                     [  OK  ]
  * pcap_agent (sguil)                                                 [  OK  ]
  * snort_agent (sguil)                                                [  OK  ]
  * suricata (alert data)                                              [  OK  ]
  * barnyard2 (spooler, unified2 format)                               [  OK  ]
  * prads (sessions/assets)                                            [  OK  ]
  * sancp_agent (sguil)                                                [  OK  ]
  * pads_agent (sguil)                                                 [  OK  ]
  * http_agent (sguil)                                                 [  OK  ]
Status: cicny-is-onion01-eth3
  * netsniff-ng (full packet data)                                     [  OK  ]
  * pcap_agent (sguil)                                                 [  OK  ]
  * snort_agent (sguil)                                                [  OK  ]
  * suricata (alert data)                                              [  OK  ]
  * barnyard2 (spooler, unified2 format)                               [  OK  ]
  * prads (sessions/assets)                                            [  OK  ]
  * sancp_agent (sguil)                                                [  OK  ]
  * pads_agent (sguil)                                                 [  OK  ]
  * http_agent (sguil)                                                 [  OK  ]
Status: cicny-is-onion01-eth4
  * netsniff-ng (full packet data)                                     [  OK  ]
  * pcap_agent (sguil)                                                 [  OK  ]
  * snort_agent (sguil)                                                [  OK  ]
  * suricata (alert data)                                              [  OK  ]
  * barnyard2 (spooler, unified2 format)                               [  OK  ]
  * prads (sessions/assets)                                            [  OK  ]
  * sancp_agent (sguil)                                                [  OK  ]
  * pads_agent (sguil)                                                 [  OK  ]
  * http_agent (sguil)

**Comment by dougburks** [comment]
Please send questions to the security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
