### ISSUE TITLE
How to create multiple windows sensor windows in Sguil?

### ISSUE THREAD

**Issue by trcns** [Security-Onion-Solutions/security-onion#886]
I was watching to Sguil tutorial on YouTube, in which Sguil had separate window for each sensor or based criticality of alerts
![screen shot 03-22-16 at 08 38 am](https://cloud.githubusercontent.com/assets/13152149/13952148/28126460-f00b-11e5-8b71-448e893fb452.PNG)
 as shown in attached image, I am unable figure out to create similar windows, can some one please help?

**Comment by dougburks** [comment]
Please send questions to the security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
