### ISSUE TITLE
Where will I find all my PCAP's?

### ISSUE THREAD

**Issue by trcns** [Security-Onion-Solutions/security-onion#889]
I installed SO v 14.4, and i am capturing full PCAP since last two months. I can see the packets in Sguil, but when I try searching *.pcap I don't find them. I need to upload a specific days PCAP into wireshark, where do I find these pcap's?

**Comment by ozirus** [comment]
You can ask this questions to SO mail list.

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
