### ISSUE TITLE
OSSEC Manager - Max Agents

### ISSUE THREAD

**Issue by brianhaugli** [Security-Onion-Solutions/security-onion#895]
Set OSSEC manager on default SO install to allow for max agents.

http://ossec-docs.readthedocs.org/en/latest/faq/ossec.html#can-an-ossec-manager-have-more-than-256-agents

**Comment by dougburks** [comment]
Hi Brian,

I believe we already increase this to 1024.

On Sunday, April 3, 2016, brianhaugli <notifications@github.com> wrote:

> Set OSSEC manager on default SO install to allow for max agents.
>
>
> http://ossec-docs.readthedocs.org/en/latest/faq/ossec.html#can-an-ossec-manager-have-more-than-256-agents
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Security-Onion-Solutions/security-onion/issues/895>
>


-- 
Doug Burks

**Comment by dougburks** [comment]
You can verify that we already increase the default number of maxagents to 1024 with the following command:
sudo grep "Maximum number of agents" /var/ossec/logs/ossec.log 

For more information, please see:
https://groups.google.com/d/topic/security-onion-testing/iNknDr7fq_I/discussion
