### ISSUE TITLE
Snort_Agent-# question

### ISSUE THREAD

**Issue by hhittjs** [Security-Onion-Solutions/security-onion#897]
I have box with two nics and after upgrading from 12 to 14 I notice multiple agents.
snort_agent -1 thru snort_agent-6 all with (squil)

Question is - Can I simply remove 2 - 6, since they appear to be duplicates?

Thanks

**Comment by dougburks** [comment]
Hi hhittjs,

Please send all questions to our security-onion mailing list:

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

On Thursday, April 7, 2016, hhittjs <notifications@github.com> wrote:

> I have box with two nics and after upgrading from 12 to 14 I notice
> multiple agents.
> snort_agent -1 thru snort_agent-6 all with (squil)
>
> Question is - Can I simply remove 2 - 6, since they appear to be
> duplicates?
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Security-Onion-Solutions/security-onion/issues/897>
>


-- 
Doug Burks
