### ISSUE TITLE
IPS mode

### ISSUE THREAD

**Issue by Pouya47** [Security-Onion-Solutions/security-onion#900]
How can use Security Onion in IPS mode?
For example the eth0 is wan and eth1 is lan port.

**Comment by dougburks** [comment]
Please see the FAQ:
https://github.com/Security-Onion-Solutions/security-onion/wiki/FAQ#can-security-onion-run-in-ips-mode

If you have further questions, please use our security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
