### ISSUE TITLE
redis installation path

### ISSUE THREAD

**Issue by binups** [Security-Onion-Solutions/security-onion#912]
For redis plugin installation purpose i need "path_to_bro_build" can you tell the path

**Comment by dougburks** [comment]
Hi binups,

Bro is installed at /opt/bro/.

We don't support redis, so we won't be able to provide any more assistance than this.

If you have non-redis questions, please use our security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
