### ISSUE TITLE
Add nDPI with ntopng

### ISSUE THREAD

**Issue by PowerPress** [Security-Onion-Solutions/security-onion#920]
This always a much greater enhancement to ntopng monitoring as well as possible IPS based uses.

See these articles:

http://www.ntop.org/ntopng/monitoring-bittorrent-traffic-with-ntopng/

http://www.ntop.org/ndpi/how-to-enforce-layer-7-traffic-policies-using-ntopng/

**Comment by dougburks** [comment]
Hi @PowerPress ,

You can manually install ntopng:
https://github.com/Security-Onion-Solutions/security-onion/wiki/DeployingNtopng
