### ISSUE TITLE
CapME - Error: No pcap_agent found

### ISSUE THREAD

**Issue by pssrml** [Security-Onion-Solutions/security-onion#921]
When I'm trying to retrieve the pcap file through ELSA I receive the error "Error: No pcap_agent found"

I'm uploading the sostat files and a print screen. Any help is welcome

Thanks in advance

[sostat_output.txt](https://github.com/Security-Onion-Solutions/security-onion/files/271589/sostat_output.txt)
[sostat-redacted.txt](https://github.com/Security-Onion-Solutions/security-onion/files/271590/sostat-redacted.txt)
![capme](https://cloud.githubusercontent.com/assets/749139/15378035/f84572f2-1d57-11e6-8146-8dacaadda7b4.JPG)

**Comment by dougburks** [comment]
Hi pssrml,

As the message says, there is no pcap_agent shown in your sostat output. If
you want to be able to pivot to full packet capture, then you'll need to
enable pcap_agent and netsniff-ng. If you have further questions or
problems, please use the security-onion mailing list:

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

On Wednesday, May 18, 2016, pssrml <notifications@github.com> wrote:

> When I'm trying to retrieve the pcap file through ELSA I receive the error
> "Error: No pcap_agent found"
>
> I'm uploading the sostat files and a print screen. Any help is welcome
>
> Thanks in advance
>
> sostat_output.txt
> <https://github.com/Security-Onion-Solutions/security-onion/files/271589/sostat_output.txt>
> sostat-redacted.txt
> <https://github.com/Security-Onion-Solutions/security-onion/files/271590/sostat-redacted.txt>
> [image: capme]
> <https://cloud.githubusercontent.com/assets/749139/15378035/f84572f2-1d57-11e6-8146-8dacaadda7b4.JPG>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Security-Onion-Solutions/security-onion/issues/921>
>


-- 
Doug Burks

**Comment by weslambert** [comment]
Would it be worth considering to add a note to sosetup (Sensor/Standalone --> Custom) about not being able to use CapME or Sguil to pivot to PCAP if the user chooses to leave FPC functionality disabled?

Thanks,
Wes

**Comment by dougburks** [comment]
Hi Wes,

If you'd like to add that, please feel free to submit a Pull Request.

Thanks!
