### ISSUE TITLE
NSM: backup scripts should not prompt when run with --force-yes

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#944]
https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/pull/6

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/commit/4f66917f0c00a044b13fc5b9c65e1c881e2128a0

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/tGXKlYusqLg/discussion

**Comment by weslambert** [comment]
Is this related to: https://github.com/Security-Onion-Solutions/security-onion/issues/561?

**Comment by dougburks** [comment]
Yep!  Here's the mailing list thread that prompted #561:
https://groups.google.com/d/topic/security-onion/nxd6u8m4itc/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2016/07/securityonion-nsmnow-admin-scripts.html
