### ISSUE TITLE
ELSA query syntax causing server reboot

### ISSUE THREAD

**Issue by ehollis** [Security-Onion-Solutions/security-onion#954]
I have run into an issue when I run a query that I have defined within /var/www/so/elsa/local.php. Note that this query runs fine if manually run as an ELSA query (also note that we have a separate issue where $MyOrg is not working properly):
limit:3000 class=BRO_CONN -BRO_CONN.dstip>10.33.1.0 -BRO_CONN.dstip<10.33.255.255 AND -BRO_CONN.dstip>10.43.1.0 -BRO_CONN.dstip<10.43.255.255 AND -BRO_CONN.dstip>192.168.1.0 -BRO_CONN.dstip<192.168.255.255 AND -BRO_CONN.dstip>161.182.1.0 -BRO_CONN.dstip<161.182.255.255 AND -BRO_CONN.dstip>10.34.1.0 -BRO_CONN.dstip<10.34.255.255 AND -BRO_CONN.dstip>172.1.0.0 -BRO_CONN.dstip<172.255.255.255 AND -dstip=10.32.254.11 -resp_country_code=- -resp_country_code=US groupby:srcip

Next, I defined this query in my local.php file and restarted apache2. Note that I tried to double quote the undefined resp_country_code as follows: -resp_country_code="-", but the query fails when I run it from the left hand nav bar because it says that resp_country_code cannot be undefined. I then wrapped the dash in single quotes, which does not throw the error. While no error occurs, I immediately get booted from the SSH session I have with the server saying that a remote host has triggered a reboot! Here is the exact copy within my local.php file:

<a href="/elsa-query/?query_string=limit:3000 class=BRO_CONN -BRO_CONN.dstip>10.33.1.0 -BRO_CONN.dstip<10.33.255.255 AND -BRO_CONN.dstip>10.43.1.0 -BRO_CONN.dstip<10.43.255.255 AND -BRO_CONN.dstip>192.168.1.0 -BRO_CONN.dstip<192.168.255.255 AND -BRO_CONN.dstip>161.182.1.0 -BRO_CONN.dstip<161.182.255.255 AND -BRO_CONN.dstip>10.34.1.0 -BRO_CONN.dstip<10.34.255.255 AND -BRO_CONN.dstip>172.1.0.0 -BRO_CONN.dstip<172.255.255.255 AND -dstip=10.32.254.11 -resp_country_code='-' -resp_country_code=US groupby:srcip" target="dynamic" onclick="turnBackBold (this);">Top connections outside of
 US</a><br>

-Eric

**Comment by dougburks** [comment]
Hi Eric,

Please send all questions to our security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!
