### ISSUE TITLE
Squert: OSSEC HIDS alerts display NIDS rules

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#958]
https://groups.google.com/d/topic/security-onion/lvFNqF-sjX8/discussion

**Comment by ozirus** [comment]
Squert's displaying wrong alert displays also for NIDS rules.

![image](https://cloud.githubusercontent.com/assets/72383/18660095/51e059d2-7f17-11e6-86e4-a73dfe3d8ef9.png)

**Comment by dougburks** [comment]
commit:
https://github.com/Security-Onion-Solutions/securityonion-squert/commit/8c9fbff2dcd2bfa88b1f57f5e39998ea19420ff6

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/NYyykot_AiU/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2016/12/squert-163-now-available-for-security.html
