### ISSUE TITLE
Can we setup Security Onion in Amazon AWS to monitor AWS instances

### ISSUE THREAD

**Issue by jeewanthasas** [Security-Onion-Solutions/security-onion#959]
Can we setup Security Onion in Amazon AWS to monitor AWS instances?

Thanks

**Comment by dougburks** [comment]
Yes, please see:
https://github.com/Security-Onion-Solutions/security-onion/wiki/CloudClient

If you have further questions or problems, please use the security-onion mailing list instead of this Issue Tracker:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
