### ISSUE TITLE
Pivoting to CapME from Squert not working: Invalid start time

### ISSUE THREAD

**Issue by hostingnuggets** [Security-Onion-Solutions/security-onion#965]
I just installed SO on Ubuntu 14.04 LTS and unfortunately the pivoting from Squert to CapME by clicking on the event ID does not work. I get "Invalid start time" as error message.

It seems that the URL behind the event ID in Squert is wrong as the stime and etime contains NaN as you can see here below:

```
https://192.168.100.100/capme/?sip=xx.xx.xx.xx&dip=yy.yy.yy.yy&spt=53366&dpt=1433&stime=NaN&etime=NaN&filename=squert
```

any ideas what could be wrong?

**Comment by weslambert** [comment]
hostingnuggets,

Please use the security-onion mailing list instead of this Issue Tracker to post your questions:

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
https://groups.google.com/forum/#!forum/security-onion

Thanks,
Wes

**Comment by hostingnuggets** [comment]
It's not really a question, it's more of a bug report. I don't think NaN as start time and end time is normal...

**Comment by weslambert** [comment]
hostingnuggets,

To avoid clutter within the Issue Tracker and allow other folks to more easily search for answers to problems they may face, folks will usually (first) post their concerns/issues on the Security Onion mailing list.  Once it is reviewed, if it is confirmed to be reproducible and not just a result of misconfiguration, filesystem corruption, unintentional deletion/modification, etc.,  an Issue will be opened for it here.   

- I'm not having any issue pivoting from Squert to CapMe (with stime, etime, etc.) in my testing.  

- Your particular issue may not be with specifically with Squert, but possibly at another point in the data collection/presentation chain.  

- Do you experience a problem with only a specific alert, a certain type of alerts, or all alerts?  

- What kind of browser are you using?

- Are you running the latest version of Security Onion (14.04)?  

- Have you made any modifications to the existing scripts/programs/functions of Security Onion?

Please provide these answers and the output of sostat-redacted (attached as a .txt file or using a service like Pastebin.com) in a new thread on the Security Onion mailing list.

Thanks,
Wes
