### ISSUE TITLE
Setup: sosetup.conf needs to include MTU

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#966]

**Comment by dougburks** [comment]
https://groups.google.com/d/topic/security-onion-testing/bN-9Pgb19w8/discussion

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion-setup/pull/22/commits/d882f9a20fd10af835cb460ad84a7a5e8f536551

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2016/08/securityonion-setup-20120912.html
