### ISSUE TITLE
NSM: configure Snort snaplen via command line argument

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#975]

**Comment by weslambert** [comment]
Is this related to configuring the snaplen for VLAN-tagging, etc., for those who do not re-run setup or have a new installation (in regard to the most recent updates)?

**Comment by dougburks** [comment]
Hi Wes,

Yes, even in the case of a new installation with latest version of Setup that configures snaplen in snort.conf, that snort.conf gets overwritten on the next Snort release, so we need nsm_sensor_ps-start and nsm_sensor_ps-restart to configure snaplen just like Setup does.

**Comment by weslambert** [comment]
Gotcha--thanks!

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion-nsmnow-admin-scripts/pull/8

**Comment by dougburks** [comment]
submitted for testing:
https://groups.google.com/d/topic/security-onion-testing/0LDLmdRKLx4/discussion

**Comment by dougburks** [comment]
published: http://blog.securityonion.net/2016/08/securityonion-nsmnow-admin-scripts_23.html
