### ISSUE TITLE
syslog-ng.conf should include conf.d directory

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#978]
```
###
# Include all config files in /etc/syslog-ng/conf.d/
###
@include "/etc/syslog-ng/conf.d/*.conf"
```

**Comment by dspruell** [comment]
@dougburks - this is a good idea; looking at some of the config changes I want to make with a deployment for relaying to another system it would be helpful to just be able to drop a file in the conf.d/ directory and not have to modify the stock syslog-ng.conf.
