### ISSUE TITLE
Reoccurring install issue

### ISSUE THREAD

**Issue by mtech3** [Security-Onion-Solutions/security-onion#982]
I have installed and wiped my drive 5 times now. I have an issue that I can't stop from occurring. I install from scratch to a clean drive, I boot and use Byobu to run 'soup' and upgrade the system. I reboot. I go into the setup and run and configure my 2 network cards then reboot. I then open setup again and choose (I have tried evaluation mode and stand alone modes) and tried Snort and Suricata both. I have tried the rules that don't need an Oinkcode and ones that DO need the code. The only way I can get the system to halfway work is NOT TO UPDATE. It kinda works IF I don't update. Something is breaking it but I am not smart enough to figure it out. I have a sostat-redacted attached. Any hints at what is causing the issue and what I can do to end it would be greatly appreciated.
[sostat-redacted.txt](https://github.com/Security-Onion-Solutions/security-onion/files/416333/sostat-redacted.txt)

**Comment by dougburks** [comment]
Hi mtech3,

Please send all questions/problems to our security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists
